// M9b's quiet-window timings, in one command (PLAN §20 D380: M9b must not release slower than `dev` at 256²).
//
//   node investigation/m9b/quiet-window.mjs                  the whole run (about 2 hours; --plan says exactly)
//   node investigation/m9b/quiet-window.mjs --plan           the work counts and the estimated time; times nothing
//   node investigation/m9b/quiet-window.mjs --smoke          tiny inputs through the whole pipeline (not timings)
//   node investigation/m9b/quiet-window.mjs --summarize DIR  the summary again from a run's results
//
// Run it only in the window Kyler names, with nothing else heavy on the machine: it waits for the
// machine to be quiet first (CPU load low for a minute, no other vitest/playwright/tsc/Timberborn, no busy
// node/chrome/browser/python/cargo process) and gives up after --wait-max-min (default 90) saying so. While
// it runs it watches the load, pauses when something else starts (and gives up after --pause-max-min), and
// marks any timing taken under foreign load as noisy; a noisy unit is run again once.
//
// What it times (each map generated by a persistent, warmed-up process per variant, the variants of one
// map taken one after the other in a rotating order, three repeats, `gc()` before each; CPU is the
// process's CPU time, wall the call's, first look the first `onLand`):
//
//   large  256², all seven themes, seeds 1-8:  dev, ss, r1, r2, tip       (timing 4: tip against dev, D380;
//                                                                          round 1 = ss -> r1; round 2 = r1 -> r2)
//   lake   Lake Basin, seeds 1-20, 96² 128² 256²:  tip, tip+lb             (timing 3: Lake Basin round 2)
//   small  96² and 128², all themes, seeds 1-8:  pre-ss, ss, r1, r2, tip   (timing 1: small starts' first look
//                                                                          pre-ss -> tip; timing 2 at the small sizes)
//
//   variant  state                                                      ref
//   pre-ss   before small starts (dev merged, one mine-site check)      4a785170
//   ss       + small starts (#153)                                      affe89b9
//   r1       + generation speed round 1 (#155)                          37e144b2
//   r2       + generation speed round 2 (#155)                          892cc5c2
//   tip      the branch as it is (the 128² gate and everything since)   HEAD (--tip REF)
//   tip+lb   tip + Lake Basin round 2 (quiet-window/lake-basin-round2.patch, ported to the tip)
//   dev      origin/dev (--dev REF)
//
// Results: investigation/m9b/local/quiet-window/<stamp>/ (gitignored, D195): results.jsonl (every timing, with
// the machine's load beside it), warmups.jsonl, load.jsonl (the load, one line per second), gates.log,
// config.json and summary.md (also printed). The snapshots of each ref's src/core are built once, into
// local/quiet-window/snaps/, and kept. Once per machine: npm ci (typescript and fflate from the root's
// node_modules). Never launches Timberborn, never touches saves or mods.
//
// Options: --only large,lake,small  --reps N  --lanes N (concurrent single-threaded lanes, default 3)
//   --seeds A-B  --sizes 96,128  --themes any,delta  (override every group)  --budget-min N (start no new
//   unit after N minutes; partial results are summarised)  --resume DIR  --fetch (git fetch origin first)
//   --tip REF  --dev REF  --wait-max-min N  --pause-max-min N  --skip-quiet-check (for tests only).

import { execFileSync, fork, spawnSync } from 'node:child_process';
import { appendFileSync, cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..', '..');
const argv = process.argv.slice(2);
const has = (n) => argv.includes('--' + n);
const arg = (n, d) => {
  const i = argv.indexOf('--' + n);
  return i >= 0 && argv[i + 1] !== undefined ? argv[i + 1] : d;
};

// ------------------------------------------------------------------------------------ a worker process
// (one per variant per lane: it loads that variant's src/core once, then generates the maps it is sent)

if (has('child')) {
  const require = createRequire(import.meta.url);
  require('node:module').Module._initPaths();
  const ts = require('typescript');
  require.extensions['.ts'] = (mod, file) => {
    const out = ts.transpileModule(readFileSync(file, 'utf8'), {
      compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS, esModuleInterop: true, resolveJsonModule: true },
      fileName: file,
    });
    mod._compile(out.outputText, file);
  };
  const snap = path.resolve(arg('snap', ''));
  const gen = require(path.join(snap, 'src/core/gen/generate.ts'));
  const spec = require(path.join(snap, 'src/core/spec/mapspec.ts'));
  process.on('message', (msg) => {
    const { id, theme, seed, size } = msg;
    try {
      const s = spec.makeSpec({ seed, theme, size: { x: size, y: size } });
      if (global.gc) global.gc();
      let firstLook = -1;
      let firstLookCpu = -1;
      let lands = 0;
      const c0 = process.cpuUsage();
      const t0 = performance.now();
      const r = gen.generate(s, {
        onLand: () => {
          lands++;
          if (firstLook < 0) {
            firstLook = performance.now() - t0;
            const c = process.cpuUsage(c0);
            firstLookCpu = (c.user + c.system) / 1000;
          }
        },
      });
      const wall = performance.now() - t0;
      const c = process.cpuUsage(c0);
      // (everything below is outside the timed call)
      process.send({
        id,
        wall,
        cpu: (c.user + c.system) / 1000,
        firstLook,
        firstLookCpu,
        lands,
        ok: !!r.report?.passed,
        attempts: r.attempts ?? -1,
        inner: r.timings ? { firstLook: r.timings.firstLook, firstWater: r.timings.firstWater, final: r.timings.final } : null,
        hash: r.bytes && r.bytes.length ? createHash('sha256').update(r.bytes).digest('hex').slice(0, 16) : '',
      });
    } catch (e) {
      process.send({ id, error: String(e?.stack ?? e).slice(0, 500) });
    }
  });
  process.on('disconnect', () => process.exit(0));
  process.send({ id: 'ready' });
}

// ------------------------------------------------------------------------------------ configuration

const ALL_THEMES = ['any', 'riverValley', 'canyon', 'highlands', 'lakeBasin', 'delta', 'islands'];
const range = (a, b) => Array.from({ length: b - a + 1 }, (_, k) => a + k);

function variantsOf(tip, dev) {
  return {
    'pre-ss': { ref: '4a785170', label: 'before small starts' },
    ss: { ref: 'affe89b9', label: '+ small starts (#153)' },
    r1: { ref: '37e144b2', label: '+ generation speed round 1' },
    r2: { ref: '892cc5c2', label: '+ generation speed round 2' },
    tip: { ref: tip, label: 'the branch tip' },
    'tip+lb': { ref: tip, patch: path.join(HERE, 'quiet-window', 'lake-basin-round2.patch'), label: 'tip + Lake Basin round 2' },
    dev: { ref: dev, label: 'origin/dev' },
  };
}

// Each group: variants taken together on the same maps. Order = priority (the decision-critical first, so
// a window that ends early still has the most important numbers).
const GROUPS = {
  large: { variants: ['dev', 'tip', 'r2', 'r1', 'ss'], sizes: [256], themes: ALL_THEMES, seeds: range(1, 8), reps: 3 },
  lake: { variants: ['tip', 'tip+lb'], sizes: [96, 128, 256], themes: ['lakeBasin'], seeds: range(1, 20), reps: 3 },
  small: { variants: ['pre-ss', 'ss', 'r1', 'r2', 'tip'], sizes: [96, 128], themes: ALL_THEMES, seeds: range(1, 8), reps: 3 },
};

// The comparisons (before = a, after = b), each over the maps both variants have; metrics in the order shown.
const COMPARISONS = [
  { id: 'T4  tip against dev at 256² (D380)', a: 'dev', b: 'tip', sizes: [256], metrics: ['map wall', 'map cpu', 'first look'] },
  { id: 'T3  Lake Basin round 2 (tip -> tip+lb)', a: 'tip', b: 'tip+lb', sizes: [96, 128, 256], metrics: ['map wall', 'map cpu', 'first look'] },
  { id: 'T1  small starts, first look (pre-ss -> tip)', a: 'pre-ss', b: 'tip', sizes: [96, 128], metrics: ['first look', 'first look cpu', 'map wall'] },
  { id: 'T2a generation speed round 1 (ss -> r1)', a: 'ss', b: 'r1', sizes: [96, 128, 256], metrics: ['map cpu', 'map wall', 'first look'] },
  { id: 'T2b generation speed round 2 (r1 -> r2)', a: 'r1', b: 'r2', sizes: [96, 128, 256], metrics: ['map cpu', 'map wall', 'first look'] },
  { id: 'T2c round 1 and 2 together, small starts included (pre-ss -> r2)', a: 'pre-ss', b: 'r2', sizes: [96, 128], metrics: ['map cpu', 'map wall'] },
];

// Seconds a map takes on this machine when quiet, per theme and size: gen-speed round 2's settled-return
// medians (the investigation's table, a loaded 9800X3D) times FACTOR, which brings them to this machine's
// quiet medians and mean-over-median tails (docs/progress/m9b.md: 128² the map 2.6 s median, 256² 10.6 s
// median / 22.7 p90). Used only for the estimate; the run measures the real times.
const MAP_S = {
  96: { any: 1.14, riverValley: 0.93, canyon: 1.47, highlands: 1.84, lakeBasin: 1.38, delta: 0.88, islands: 2.54 },
  128: { any: 1.82, riverValley: 1.71, canyon: 2.64, highlands: 2.66, lakeBasin: 2.38, delta: 1.92, islands: 4.98 },
  256: { any: 8.5, riverValley: 7.37, canyon: 8.09, highlands: 7.92, lakeBasin: 11.76, delta: 5.85, islands: 20.24 },
};
const FACTOR = 1.3;
const VARIANT_FACTOR = { 'tip+lb': 1.5 }; // pessimistic: Lake Basin round 2's own report saw it slower under load

const T = {
  quietMinutes: 1, // the quiet check's window
  loadMean: Number(arg('load-mean', 6)), // % of all threads, mean over the window
  loadPeak: Number(arg('load-peak', 25)), // % of all threads, any one second
  busyProcess: 3, // % of one core: another process this busy is "something else running"
  pauseForeign: 15, // % of all threads (estimated foreign) over 10 s: pause the lanes
  noisyMean: 10, // a timing whose foreign load averaged more than this is noisy
  noisyPeak: 35,
  ownPerRun: 1.05, // threads one running generation uses (JS main thread plus its GC helpers)
};

// ------------------------------------------------------------------------------------ small helpers

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const stamp = () => new Date().toISOString().replace(/[-:]/g, '').replace(/\..*/, '').replace('T', '-');
const hhmm = (ms) => (ms < 90000 ? `${Math.round(ms / 1000)} s` : ms < 5400000 ? `${(ms / 60000).toFixed(0)} min` : `${(ms / 3600000).toFixed(1)} h`);
const THREADS = os.cpus().length;

function git(args, opts = {}) {
  return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8', maxBuffer: 1 << 28, ...opts });
}
const median = (v) => {
  if (!v.length) return NaN;
  const s = v.slice().sort((a, b) => a - b);
  const m = s.length >> 1;
  return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2;
};
const mean = (v) => (v.length ? v.reduce((a, b) => a + b, 0) / v.length : NaN);
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
function bootstrap(pairs, stat, n = 2000) {
  // 90% interval of stat(pairs) over resamples of the maps
  if (pairs.length < 3) return [NaN, NaN];
  const rand = rng(12345);
  const out = [];
  for (let k = 0; k < n; k++) {
    const s = [];
    for (let i = 0; i < pairs.length; i++) s.push(pairs[Math.floor(rand() * pairs.length)]);
    out.push(stat(s));
  }
  out.sort((a, b) => a - b);
  return [out[Math.floor(0.05 * n)], out[Math.floor(0.95 * n)]];
}

// ------------------------------------------------------------------------------------ the machine's load

const mon = { samples: [], active: 0, last: null, timer: null, file: null };
function cpuNow() {
  let idle = 0;
  let total = 0;
  for (const c of os.cpus()) {
    for (const k of Object.keys(c.times)) total += c.times[k];
    idle += c.times.idle;
  }
  return { idle, total };
}
function startMonitor(file) {
  mon.file = file;
  mon.last = cpuNow();
  mon.timer = setInterval(() => {
    const n = cpuNow();
    const dt = n.total - mon.last.total;
    const busy = dt > 0 ? 100 * (1 - (n.idle - mon.last.idle) / dt) : 0;
    mon.last = n;
    const s = { t: Date.now(), busy: Math.round(busy * 10) / 10, active: mon.active };
    s.foreign = Math.max(0, Math.round((busy - (100 * mon.active * T.ownPerRun) / THREADS) * 10) / 10);
    mon.samples.push(s);
    if (mon.file) appendFileSync(mon.file, JSON.stringify(s) + '\n');
  }, 1000);
}
function stopMonitor() {
  clearInterval(mon.timer);
}
const loadOver = (t0, t1) => {
  let s = mon.samples.filter((x) => x.t > t0 && x.t <= t1 + 1000);
  if (!s.length) s = mon.samples.slice(-1);
  if (!s.length) return null;
  const b = s.map((x) => x.busy);
  const f = s.map((x) => x.foreign);
  return { mean: Math.round(mean(b) * 10) / 10, peak: Math.max(...b), foreignMean: Math.round(mean(f) * 10) / 10, foreignPeak: Math.max(...f), n: s.length };
};
const recentForeign = (secs) => {
  const s = mon.samples.slice(-secs);
  return s.length ? mean(s.map((x) => x.foreign)) : 0;
};

// Other processes that would disturb a timing (Windows: CIM; elsewhere ps). Own descendants and ancestors don't count.
function processes() {
  const parse = (j) => (Array.isArray(j) ? j : j ? [j] : []);
  try {
    if (process.platform === 'win32') {
      const ps = "Get-CimInstance Win32_Process | ForEach-Object { [pscustomobject]@{ pid = $_.ProcessId; ppid = $_.ParentProcessId; name = $_.Name; cmd = $_.CommandLine; cpu = [double]($_.KernelModeTime + $_.UserModeTime) } } | ConvertTo-Json -Compress";
      const r = spawnSync('powershell', ['-NoProfile', '-NonInteractive', '-Command', ps], { encoding: 'utf8', maxBuffer: 1 << 26 });
      return parse(JSON.parse(r.stdout)).map((p) => ({ ...p, cpu: p.cpu / 1e7 })); // seconds of CPU
    }
    const r = spawnSync('ps', ['-A', '-o', 'pid=,ppid=,comm=,cputimes=,args='], { encoding: 'utf8', maxBuffer: 1 << 26 });
    return r.stdout.split('\n').filter(Boolean).map((l) => {
      const m = /^\s*(\d+)\s+(\d+)\s+(\S+)\s+(\d+)\s+(.*)$/.exec(l);
      return m ? { pid: +m[1], ppid: +m[2], name: m[3], cpu: +m[4], cmd: m[5] } : null;
    }).filter(Boolean);
  } catch {
    return null;
  }
}
const WATCHED = /^(node|chrome|chromium|msedge|firefox|electron|vitest|playwright|cargo|rustc|python|esbuild|dotnet|tsc|git)(\.exe)?$/i;
const ALWAYS = /vitest|playwright|\btsc\b|vite build|vite\.js|cargo|rustc|timberborn|workspace\.exe/i;
async function otherHeavy() {
  const a = processes();
  if (!a) return { ok: true, notes: ['process list unavailable: only the CPU load was checked'], busy: [] };
  const t0 = Date.now();
  await sleep(3000);
  const b = processes();
  const dt = (Date.now() - t0) / 1000;
  const byPid = new Map(b.map((p) => [p.pid, p]));
  const mine = new Set([process.pid]);
  for (let grew = true; grew; ) {
    grew = false;
    for (const p of b) if (mine.has(p.ppid) && !mine.has(p.pid)) (mine.add(p.pid), (grew = true));
  }
  const ancestors = new Set();
  for (let p = byPid.get(process.pid); p && p.ppid && !ancestors.has(p.ppid); p = byPid.get(p.ppid)) ancestors.add(p.ppid);
  const before = new Map(a.map((p) => [p.pid, p]));
  const busy = [];
  const idle = [];
  for (const p of b) {
    if (mine.has(p.pid)) continue;
    const timberborn = /timberborn/i.test(p.name);
    const watched = WATCHED.test(p.name) || timberborn;
    if (!watched) continue;
    const pct = before.has(p.pid) ? (100 * (p.cpu - before.get(p.pid).cpu)) / dt : 0;
    const where = (/DamGoodMaps[-\w]*/i.exec(p.cmd ?? '') ?? [''])[0];
    const row = { pid: p.pid, name: p.name, pct: Math.round(pct * 10) / 10, where, cmd: String(p.cmd ?? '').slice(0, 110) };
    if (ancestors.has(p.pid)) {
      if (pct >= T.busyProcess) busy.push({ ...row, why: 'an ancestor of this runner, busy' });
      continue;
    }
    if (timberborn) busy.push({ ...row, why: 'Timberborn is running' });
    else if (pct >= T.busyProcess) busy.push({ ...row, why: 'busy' });
    else if (ALWAYS.test(p.cmd ?? '')) busy.push({ ...row, why: 'a test/build tool is running' });
    else idle.push(row);
  }
  return { ok: !busy.length, busy, notes: idle.length ? [`${idle.length} idle watched process(es) ignored: ${idle.slice(0, 6).map((p) => `${p.name}#${p.pid}${p.where ? ' ' + p.where : ''}`).join(', ')}`] : [] };
}

async function waitQuiet(label, log, maxMin, windowMin) {
  // true when quiet (mean and peak load under the thresholds for windowMin, and nothing else heavy); false on giving up
  const t0 = Date.now();
  let lastSay = 0;
  for (;;) {
    const need = windowMin * 60;
    const w = mon.samples.slice(-need);
    const full = w.length >= need && w[w.length - 1].t - w[0].t >= (need - 3) * 1000;
    const m = w.length ? mean(w.map((x) => x.busy)) : 100;
    const pk = w.length ? Math.max(...w.map((x) => x.busy)) : 100;
    let procs = { ok: true, busy: [], notes: [] };
    if (full && m <= T.loadMean && pk <= T.loadPeak) procs = await otherHeavy();
    const quiet = full && m <= T.loadMean && pk <= T.loadPeak && procs.ok;
    if (quiet) {
      log(`${label}: quiet (load ${m.toFixed(1)}% mean, ${pk.toFixed(0)}% peak over ${windowMin} min)${procs.notes.length ? '; ' + procs.notes.join('; ') : ''}`);
      return true;
    }
    if (Date.now() - t0 > maxMin * 60000) {
      log(`${label}: GAVE UP after ${maxMin} min: the machine was not quiet (load ${m.toFixed(1)}% mean, ${pk.toFixed(0)}% peak; limits ${T.loadMean}% / ${T.loadPeak}%)${procs.busy.length ? '; ' + procs.busy.map((p) => `${p.name}#${p.pid} ${p.pct}% ${p.why} ${p.where}`).join('; ') : ''}`);
      return false;
    }
    if (Date.now() - lastSay > 60000) {
      lastSay = Date.now();
      log(`${label}: waiting for quiet (load ${m.toFixed(1)}% mean / ${pk.toFixed(0)}% peak over the last ${Math.min(windowMin, Math.round(w.length / 60 * 10) / 10)} min${full ? '' : ', window filling'})${procs.busy.length ? '; ' + procs.busy.map((p) => `${p.name}#${p.pid} ${p.pct}% ${p.why} ${p.where}`).join('; ') : ''}`);
    }
    await sleep(5000);
  }
}

// ------------------------------------------------------------------------------------ the snapshots

function prepareSnapshots(variants, names, snapRoot, log) {
  mkdirSync(snapRoot, { recursive: true });
  const out = {};
  for (const name of names) {
    const v = variants[name];
    const sha = git(['rev-parse', '--verify', `${v.ref}^{commit}`]).trim();
    const patchHash = v.patch ? createHash('sha256').update(readFileSync(v.patch)).digest('hex').slice(0, 8) : '';
    const dir = path.join(snapRoot, `${name.replace(/\W+/g, '_')}-${sha.slice(0, 12)}${patchHash ? '-p' + patchHash : ''}`);
    out[name] = { dir, sha, ref: v.ref, patch: !!v.patch, label: v.label };
    if (existsSync(path.join(dir, 'src/core/gen/generate.ts'))) continue;
    log(`snapshot ${name}: ${v.ref} (${sha.slice(0, 8)})${v.patch ? ' + patch' : ''} -> ${path.relative(ROOT, dir)}`);
    const tmp = mkdtempSync(path.join(os.tmpdir(), 'dgm-qw-'));
    try {
      // (tar reads "C:" as a host name, so it runs inside the folder with relative names)
      const tar = path.join(tmp, 'src.tar');
      git(['archive', '--format=tar', '-o', tar, sha, 'src/core']);
      const r = spawnSync('tar', ['-xf', 'src.tar'], { cwd: tmp, encoding: 'utf8' });
      if (r.status !== 0) throw new Error(`tar failed: ${r.stderr}`);
      rmSync(tar);
      if (v.patch) {
        // (outside any repository, so the patch's paths are taken as they are)
        const a = spawnSync('git', ['apply', '--ignore-space-change', v.patch], { cwd: tmp, encoding: 'utf8' });
        if (a.status !== 0) throw new Error(`${path.basename(v.patch)} does not apply to ${sha.slice(0, 8)}: ${a.stderr}\nThe tip has moved: port the patch's generate.ts hunk (it is one call after leanGenome) and regenerate the patch.`);
      }
      mkdirSync(dir, { recursive: true });
      cpSync(path.join(tmp, 'src'), path.join(dir, 'src'), { recursive: true });
    } finally {
      rmSync(tmp, { recursive: true, force: true });
    }
  }
  return out;
}

// ------------------------------------------------------------------------------------ worker handles

class Worker {
  constructor(name, snap) {
    this.name = name;
    this.snap = snap;
    this.seq = 0;
    this.pending = new Map();
    this.dead = false;
  }
  start() {
    return new Promise((resolve, reject) => {
      const nodePath = [path.join(ROOT, 'node_modules'), process.env.NODE_PATH].filter(Boolean).join(path.delimiter);
      this.proc = fork(fileURLToPath(import.meta.url), ['--child', '--snap', this.snap.dir], {
        execArgv: ['--expose-gc', '--max-old-space-size=6144'],
        env: { ...process.env, NODE_PATH: nodePath },
        stdio: ['ignore', 'inherit', 'inherit', 'ipc'],
      });
      this.proc.on('message', (m) => {
        if (m.id === 'ready') return resolve();
        const p = this.pending.get(m.id);
        if (p) (this.pending.delete(m.id), p(m));
      });
      this.proc.on('exit', (code) => {
        this.dead = true;
        for (const [, p] of this.pending) p({ error: `worker exited (${code})` });
        this.pending.clear();
        reject(new Error(`worker ${this.name} exited (${code}) before it was ready`));
      });
    });
  }
  run(job, timeoutMs) {
    return new Promise((resolve) => {
      const id = ++this.seq;
      const timer = setTimeout(() => {
        this.pending.delete(id);
        this.proc.kill();
        resolve({ error: `timeout after ${timeoutMs / 1000} s` });
      }, timeoutMs);
      this.pending.set(id, (m) => (clearTimeout(timer), resolve(m)));
      this.proc.send({ id, ...job });
    });
  }
  stop() {
    this.proc.removeAllListeners('exit');
    this.proc.kill();
  }
}

// ------------------------------------------------------------------------------------ the estimate

function mapSeconds(variant, theme, size) {
  return MAP_S[size][theme] * FACTOR * (VARIANT_FACTOR[variant] ?? 1);
}
function estimate(groups, lanes) {
  const rows = [];
  let total = 90; // snapshots, the quiet minute, the process check
  for (const [name, g] of Object.entries(groups)) {
    const maps = g.sizes.length * g.themes.length * g.seeds.length;
    let lane = 0;
    for (const size of g.sizes) for (const theme of g.themes) for (const v of g.variants) lane += g.seeds.length * g.reps * mapSeconds(v, theme, size);
    let warm = 0;
    for (const v of g.variants) for (const size of g.sizes) warm += mapSeconds(v, g.themes[0], size) + 6; // the warm-up map and loading the source
    const tail = g.sizes.includes(256) ? 90 : 20; // the last long map, no lane to share it with
    const wall = (lane / lanes) * 1.07 + warm + tail + 60; // 7% for the noisy units run again
    rows.push({ name, maps, runs: maps * g.reps * g.variants.length, lane, warm, wall });
    total += wall;
  }
  return { rows, total };
}
function planText(groups, lanes) {
  const e = estimate(groups, lanes);
  const lines = [`Estimated on this machine when quiet (${THREADS} threads, ${lanes} lanes), from the work counts: maps x reps x variants x per-map seconds`,
    `(gen-speed round 2's per-theme medians x ${FACTOR}, which matches this machine's quiet 128² and 256² medians in docs/progress/m9b.md; Lake Basin round 2 taken 1.5x; +7% for noisy reruns; +warm-ups; accuracy about +-30%):`, ''];
  lines.push('| group | maps | timed runs | lane-seconds | wall |', '|---|---:|---:|---:|---:|');
  for (const r of e.rows) lines.push(`| ${r.name} (${groups[r.name].variants.join(', ')}; ${groups[r.name].sizes.join('/')}²; ${groups[r.name].themes.length} theme(s) x ${groups[r.name].seeds.length} seeds x ${groups[r.name].reps} reps) | ${r.maps} | ${r.runs} | ${Math.round(r.lane)} | ${hhmm(r.wall * 1000)} |`);
  lines.push(`| setup (snapshots, quiet check) | | | | 1.5 min |`, `| **total** | | ${e.rows.reduce((a, r) => a + r.runs, 0)} | | **${hhmm(e.total * 1000)}** |`);
  return lines.join('\n');
}

// ------------------------------------------------------------------------------------ the run

async function main() {
  if (has('summarize')) {
    const dir = path.resolve(arg('summarize', ''));
    const text = summarize(dir);
    writeFileSync(path.join(dir, 'summary.md'), text);
    console.log(text);
    return;
  }
  const smoke = has('smoke');
  const tipRef = arg('tip', 'HEAD');
  const devRef = arg('dev', 'origin/dev');
  const lanes = Math.max(1, Number(arg('lanes', smoke ? 2 : 3)));
  const only = arg('only', '').split(',').filter(Boolean);
  const groups = {};
  for (const [name, g0] of Object.entries(GROUPS)) {
    if (only.length && !only.includes(name)) continue;
    const g = { ...g0 };
    if (smoke) Object.assign(g, { sizes: [96], themes: g.themes.length === 1 ? g.themes : ['delta', 'riverValley'], seeds: [1, 2], reps: 2 });
    if (has('reps')) g.reps = Number(arg('reps', 3));
    if (has('sizes')) g.sizes = arg('sizes', '').split(',').map(Number);
    if (has('themes')) g.themes = arg('themes', '').split(',');
    if (has('seeds')) {
      const m = /^(\d+)-(\d+)$/.exec(arg('seeds', ''));
      g.seeds = m ? range(+m[1], +m[2]) : arg('seeds', '').split(',').map(Number);
    }
    if (name === 'lake' && has('themes')) g.themes = g.themes.filter((t) => t === 'lakeBasin');
    groups[name] = g;
  }
  if (!Object.keys(groups).length) throw new Error('no group selected');
  if (has('plan')) {
    console.log(planText(groups, lanes));
    return;
  }

  if (has('fetch')) git(['fetch', 'origin', 'dev', 'feature/m9b']);
  const variants = variantsOf(tipRef, devRef);
  const needed = [...new Set(Object.values(groups).flatMap((g) => g.variants))];
  const runName = (smoke ? 'smoke-' : '') + stamp();
  const dir = has('resume') ? path.resolve(arg('resume', '')) : path.join(ROOT, 'investigation/m9b/local/quiet-window', runName);
  mkdirSync(dir, { recursive: true });
  const logFile = path.join(dir, 'gates.log');
  const log = (s) => {
    const line = `[${new Date().toTimeString().slice(0, 8)}] ${s}`;
    console.log(line);
    appendFileSync(logFile, line + '\n');
  };
  log(`${smoke ? 'SMOKE RUN (tiny inputs, not timings) ' : ''}quiet-window runner, results in ${path.relative(ROOT, dir)}`);
  const snaps = prepareSnapshots(variants, needed, path.join(ROOT, 'investigation/m9b/local/quiet-window/snaps'), log);
  const est = estimate(groups, lanes);
  log(`estimated duration ${hhmm(est.total * 1000)} (--plan for the breakdown)`);
  writeFileSync(path.join(dir, 'config.json'), JSON.stringify({
    started: new Date().toISOString(), smoke, lanes, groups, snaps: Object.fromEntries(Object.entries(snaps).map(([k, v]) => [k, { ref: v.ref, sha: v.sha, patch: v.patch, label: v.label }])),
    machine: { cpu: os.cpus()[0].model.trim(), threads: THREADS, mem: Math.round(os.totalmem() / 2 ** 30) + ' GiB', node: process.version, platform: process.platform },
    thresholds: T, estimateSeconds: Math.round(est.total),
  }, null, 2));

  startMonitor(path.join(dir, 'load.jsonl'));
  const resultsFile = path.join(dir, 'results.jsonl');
  const warmFile = path.join(dir, 'warmups.jsonl');
  const done = new Set();
  if (has('resume') && existsSync(resultsFile))
    for (const l of readFileSync(resultsFile, 'utf8').split('\n')) if (l.startsWith('{')) {
      const r = JSON.parse(l);
      if (!r.error && !r.noisy) done.add(`${r.g}|${r.v}|${r.theme}|${r.size}|${r.seed}|${r.rep}`);
    }
  const unchecked = smoke || has('skip-quiet-check');
  const t0 = Date.now();
  const budgetMs = has('budget-min') ? Number(arg('budget-min', 0)) * 60000 : Infinity;
  const pauseMax = Number(arg('pause-max-min', 20));
  let abort = '';
  let stoppedByBudget = false;
  const stop = (why) => {
    if (!abort) (abort = why, log(`STOPPING: ${why}`));
  };
  process.on('SIGINT', () => {
    stop('interrupted (Ctrl-C)');
  });

  // 1. the machine must be quiet before anything is timed
  if (smoke || has('skip-quiet-check')) log(has('skip-quiet-check') ? 'WARNING: --skip-quiet-check, the machine was NOT checked; these are not decision timings' : 'smoke: the quiet check is skipped');
  else if (!(await waitQuiet('start', log, Number(arg('wait-max-min', 90)), T.quietMinutes))) {
    stopMonitor();
    log('nothing was timed. Run it again when nothing else is running.');
    process.exitCode = 3;
    return;
  }

  for (const [gname, g] of Object.entries(groups)) {
    if (abort) break;
    if (!smoke && !has('skip-quiet-check') && gname !== Object.keys(groups)[0] && !(await waitQuiet(`before ${gname}`, log, Number(arg('wait-max-min', 90)), 0.5))) {
      stop('the machine did not go quiet before group ' + gname);
      break;
    }
    log(`group ${gname}: ${g.variants.join(', ')} at ${g.sizes.join('/')}², ${g.themes.length} theme(s), seeds ${g.seeds[0]}-${g.seeds[g.seeds.length - 1]}, ${g.reps} reps, ${lanes} lanes`);
    // units: one map, one rep; rep-major so an early end still has balanced coverage; the long maps first within a rep
    const units = [];
    for (let rep = 1; rep <= g.reps; rep++) {
      const list = [];
      for (const size of g.sizes) for (const theme of g.themes) for (const seed of g.seeds) list.push({ size, theme, seed, rep, attempt: 1 });
      list.sort((a, b) => b.size - a.size);
      units.push(...list);
    }
    const queue = units.filter((u) => g.variants.some((v) => !done.has(`${gname}|${v}|${u.theme}|${u.size}|${u.seed}|${u.rep}`)));
    const retry = [];
    let index = 0;
    let finished = 0;
    let retried = 0;
    const total = queue.length;
    const lane = async (laneNo) => {
      const workers = {};
      try {
        // (the warm-up: a few maps through each variant's own process, one per size, before any timing)
        for (const v of g.variants) {
          const w = new Worker(v, snaps[v]);
          await w.start();
          workers[v] = w;
          mon.active++;
          for (const size of g.sizes) {
            const a = Date.now();
            const r = await w.run({ theme: g.themes[0], seed: 101, size }, 600000);
            appendFileSync(warmFile, JSON.stringify({ g: gname, v, lane: laneNo, theme: g.themes[0], size, ...r, t: new Date().toISOString(), took: Date.now() - a }) + '\n');
            if (r.error) log(`warm-up ${v} ${size}² failed: ${r.error.split('\n')[0]}`);
          }
          mon.active--;
        }
        for (;;) {
          if (abort) return;
          if (Date.now() - t0 > budgetMs) {
            stoppedByBudget = true;
            return;
          }
          const u = queue.length ? queue.shift() : retry.shift();
          if (!u) return;
          const k = index++;
          // pause while something else is running
          const w0 = Date.now();
          while (!unchecked && recentForeign(10) > T.pauseForeign && !abort) {
            if (Date.now() - w0 > pauseMax * 60000) {
              stop(`foreign load stayed above ${T.pauseForeign}% for ${pauseMax} min`);
              return;
            }
            if ((Date.now() - w0) % 60000 < 2100) log(`lane ${laneNo}: paused, foreign load ${recentForeign(10).toFixed(0)}%`);
            await sleep(2000);
          }
          const order = g.variants.map((_, i) => g.variants[(i + k + u.rep) % g.variants.length]);
          let noisy = false;
          for (const v of order) {
            if (abort) return;
            if (u.attempt === 1 && done.has(`${gname}|${v}|${u.theme}|${u.size}|${u.seed}|${u.rep}`)) continue;
            const a = Date.now();
            mon.active++;
            const r = await workers[v].run({ theme: u.theme, seed: u.seed, size: u.size }, 900000);
            mon.active--;
            const b = Date.now();
            const load = loadOver(a, b);
            const isNoisy = !!load && (load.foreignMean > T.noisyMean || load.foreignPeak > T.noisyPeak);
            noisy ||= isNoisy;
            const rec = { g: gname, v, theme: u.theme, size: u.size, seed: u.seed, rep: u.rep, attempt: u.attempt, lane: laneNo, order: order.indexOf(v), t0: a, t1: b, load, noisy: isNoisy, ...r };
            appendFileSync(resultsFile, JSON.stringify(rec) + '\n');
            if (r.error) {
              log(`ERROR ${v} ${u.theme} ${u.size}² seed ${u.seed}: ${r.error.split('\n')[0]}`);
              if (workers[v].dead) {
                const w = new Worker(v, snaps[v]);
                await w.start();
                workers[v] = w;
              }
            }
          }
          if (noisy && u.attempt === 1) (retry.push({ ...u, attempt: 2 }), retried++);
          finished++;
          if (finished % 10 === 0 || finished === total)
            log(`${gname}: ${finished}/${total + retried} units, ${hhmm(Date.now() - t0)} elapsed, load now ${(mon.samples.at(-1)?.busy ?? 0).toFixed(0)}% (foreign ${recentForeign(10).toFixed(0)}%)`);
        }
      } catch (e) {
        stop(`lane ${laneNo} failed: ${String(e?.message ?? e).split('\n')[0]}`);
      } finally {
        for (const w of Object.values(workers)) if (!w.dead) w.stop();
      }
    };
    await Promise.all(range(1, lanes).map(lane));
    if (stoppedByBudget) {
      log(`budget of ${arg('budget-min', 0)} min reached: no new units; summarising what was timed`);
      break;
    }
  }
  stopMonitor();
  const text = summarize(dir, { smoke, abort, stoppedByBudget, elapsedMs: Date.now() - t0, quietChecked: !(smoke || has('skip-quiet-check')) });
  writeFileSync(path.join(dir, 'summary.md'), text);
  console.log('\n' + text);
  log(`done in ${hhmm(Date.now() - t0)}; ${path.relative(ROOT, path.join(dir, 'summary.md'))}`);
  if (abort) process.exitCode = 4;
}

// ------------------------------------------------------------------------------------ the summary

function summarize(dir, run = {}) {
  const lines0 = readFileSync(path.join(dir, 'results.jsonl'), 'utf8').split('\n').filter((l) => l.startsWith('{'));
  const recs = lines0.map((l) => JSON.parse(l));
  const cfg = existsSync(path.join(dir, 'config.json')) ? JSON.parse(readFileSync(path.join(dir, 'config.json'), 'utf8')) : null;
  const good = recs.filter((r) => !r.error);
  const errors = recs.filter((r) => r.error);
  // per (variant, map): the clean repeats (else all of them, flagged)
  const cells = new Map();
  for (const r of good) {
    const key = `${r.v}|${r.theme}|${r.size}|${r.seed}`;
    if (!cells.has(key)) cells.set(key, []);
    cells.get(key).push(r);
  }
  const cell = (key) => {
    const all = cells.get(key);
    if (!all) return null;
    const clean = all.filter((r) => !r.noisy);
    const use = clean.length ? clean : all;
    const m = (f) => median(use.map(f).filter((x) => x >= 0));
    const spread = (f) => {
      const v = use.map(f).filter((x) => x > 0);
      return v.length > 1 ? (Math.max(...v) - Math.min(...v)) / median(v) : NaN;
    };
    return {
      n: use.length,
      noisyOnly: !clean.length,
      'map wall': m((r) => r.wall),
      'map cpu': m((r) => r.cpu),
      'first look': m((r) => r.firstLook),
      'first look cpu': m((r) => r.firstLookCpu),
      spread: spread((r) => r.wall),
      hash: use.map((r) => r.hash).join(','),
      hashes: [...new Set(use.map((r) => r.hash))],
      ok: use.every((r) => r.ok),
    };
  };
  const out = [];
  const w = (s = '') => out.push(s);
  w(`# M9b quiet-window timings${run.smoke || cfg?.smoke ? ' (SMOKE: tiny inputs through the pipeline, not timings)' : ''}`);
  w();
  if (cfg) {
    w(`${cfg.machine.cpu}, ${cfg.machine.threads} threads, ${cfg.machine.mem}, Node ${cfg.machine.node}; ${cfg.lanes} lane(s); started ${cfg.started}.`);
    w(`Variants: ${Object.entries(cfg.snaps).map(([k, v]) => `${k} = ${v.ref}${v.ref.length < 12 ? '' : ''} (${v.sha.slice(0, 8)}${v.patch ? ' + patch' : ''})`).join('; ')}.`);
  }
  const loads = good.map((r) => r.load).filter(Boolean);
  const noisyN = good.filter((r) => r.noisy).length;
  const sampleFile = path.join(dir, 'load.jsonl');
  const lsamples = existsSync(sampleFile) ? readFileSync(sampleFile, 'utf8').split('\n').filter(Boolean).map((l) => JSON.parse(l)) : [];
  w(`Timed runs: ${good.length}${errors.length ? `, ${errors.length} failed` : ''}; machine load while timing: mean ${mean(loads.map((l) => l.mean)).toFixed(1)}% (foreign, after our own lanes' share: ${mean(loads.map((l) => l.foreignMean)).toFixed(1)}% mean, worst second ${Math.max(0, ...loads.map((l) => l.foreignPeak)).toFixed(0)}%); noisy runs (foreign load over ${T.noisyMean}% mean or ${T.noisyPeak}% for a second) ${noisyN}, run again where they could be.`);
  if (lsamples.length) w(`Whole-run load: mean ${mean(lsamples.map((s) => s.busy)).toFixed(1)}%, foreign mean ${mean(lsamples.map((s) => s.foreign)).toFixed(1)}%, p95 foreign ${lsamples.map((s) => s.foreign).sort((a, b) => a - b)[Math.floor(0.95 * lsamples.length)]}%.`);
  if (run.quietChecked === false) w('**The quiet check was skipped: not decision timings.**');
  if (run.abort) w(`**Stopped early: ${run.abort}.** The table is what was timed.`);
  if (run.stoppedByBudget) w('**Stopped at the time budget; the table is what was timed.**');
  if (errors.length) w(`Errors: ${[...new Set(errors.map((e) => `${e.v}: ${e.error.split('\n')[0]}`))].slice(0, 5).join(' | ')}`);
  w();
  w('Times are per map in seconds, median over the maps of each map\'s median over its clean repeats. Ratio = after / before for the same map, over the maps both variants timed: the median of the per-map ratios [90% bootstrap interval over maps], and the ratio of the mean times (the time per map in production) [interval]. A change is called slower or faster only when the interval of the ratio of means excludes 1.');
  w();
  const verdicts = [];
  for (const c of COMPARISONS) {
    const sizes = (cfg?.smoke ? [96, 128, 256] : c.sizes).filter((s) => [...cells.keys()].some((k) => k.startsWith(c.a + '|') && k.split('|')[2] == s) && [...cells.keys()].some((k) => k.startsWith(c.b + '|') && k.split('|')[2] == s));
    if (!sizes.length) continue;
    w(`## ${c.id}`);
    w();
    w('| size | metric | maps | before median | after median | median ratio [90%] | mean before | mean after | ratio of means [90%] | rep spread before / after | same bytes | verdict |');
    w('|---|---|---:|---:|---:|---|---:|---:|---|---|---:|---|');
    for (const size of sizes) {
      const keys = [...cells.keys()].filter((k) => k.startsWith(c.a + '|') && k.split('|')[2] == size).map((k) => k.slice(c.a.length + 1));
      const maps = keys.filter((k) => cells.has(`${c.b}|${k}`));
      const cellsA = maps.map((k) => cell(`${c.a}|${k}`));
      const cellsB = maps.map((k) => cell(`${c.b}|${k}`));
      const same = maps.filter((_, i) => cellsA[i].hashes.length === 1 && cellsB[i].hashes.length === 1 && cellsA[i].hashes[0] === cellsB[i].hashes[0] && cellsA[i].hashes[0] !== '').length;
      for (const metric of c.metrics) {
        const pairs = maps.map((_, i) => [cellsA[i][metric], cellsB[i][metric]]).filter(([a, b]) => a > 0 && b > 0 && isFinite(a) && isFinite(b));
        if (!pairs.length) continue;
        const s = (ms) => (ms / 1000).toFixed(2);
        const medA = median(pairs.map((p) => p[0]));
        const medB = median(pairs.map((p) => p[1]));
        const mnA = mean(pairs.map((p) => p[0]));
        const mnB = mean(pairs.map((p) => p[1]));
        const rMed = (ps) => median(ps.map(([a, b]) => b / a));
        const rMean = (ps) => mean(ps.map((p) => p[1])) / mean(ps.map((p) => p[0]));
        const ciMed = bootstrap(pairs, rMed);
        const ciMean = bootstrap(pairs, rMean);
        const f = (x) => (isFinite(x) ? x.toFixed(3) : 'n/a');
        const verdict = ciMean[0] > 1 ? 'SLOWER' : ciMean[1] < 1 ? 'faster' : 'no clear difference';
        const spA = median(cellsA.map((x) => x.spread).filter(isFinite));
        const spB = median(cellsB.map((x) => x.spread).filter(isFinite));
        const noisyCells = cellsA.concat(cellsB).filter((x) => x.noisyOnly).length;
        w(`| ${size}² | ${metric} | ${pairs.length}${noisyCells ? ` (${noisyCells} noisy cells)` : ''} | ${s(medA)} | ${s(medB)} | ${f(rMed(pairs))} [${f(ciMed[0])}, ${f(ciMed[1])}] | ${s(mnA)} | ${s(mnB)} | ${f(rMean(pairs))} [${f(ciMean[0])}, ${f(ciMean[1])}] | ${isFinite(spA) ? (100 * spA).toFixed(1) + '%' : 'n/a'} / ${isFinite(spB) ? (100 * spB).toFixed(1) + '%' : 'n/a'} | ${same}/${maps.length} | ${verdict} |`);
        verdicts.push({ id: c.id, size, metric, verdict, ratio: rMean(pairs), n: pairs.length });
      }
    }
    w();
    // per theme at 256² for the comparisons that decide something
    if (sizes.includes(256) && (c.a === 'dev' || c.a === 'tip')) {
      w(`By theme at 256² (map wall, median of the maps, seconds):`);
      w();
      w(`| theme | maps | ${c.a} | ${c.b} | ratio of means |`);
      w('|---|---:|---:|---:|---:|');
      for (const theme of ALL_THEMES) {
        const ks = [...cells.keys()].filter((k) => k.startsWith(c.a + `|${theme}|256|`)).map((k) => k.slice(c.a.length + 1)).filter((k) => cells.has(`${c.b}|${k}`));
        if (!ks.length) continue;
        const A = ks.map((k) => cell(`${c.a}|${k}`)['map wall']);
        const B = ks.map((k) => cell(`${c.b}|${k}`)['map wall']);
        w(`| ${theme} | ${ks.length} | ${(median(A) / 1000).toFixed(2)} | ${(median(B) / 1000).toFixed(2)} | ${(mean(B) / mean(A)).toFixed(3)} |`);
      }
      w();
    }
  }
  w('## One line each');
  w();
  const pick = (id, metric, size) => verdicts.find((v) => v.id.startsWith(id) && v.metric === metric && v.size === size);
  const one = (id, label, metrics) => {
    const parts = verdicts.filter((v) => v.id.startsWith(id) && metrics.includes(v.metric)).map((v) => `${v.size}² ${v.metric} x${v.ratio.toFixed(3)} (${v.verdict}, ${v.n} maps)`);
    w(`- ${label}: ${parts.length ? parts.join('; ') : 'not timed'}`);
  };
  void pick;
  one('T1', 'Small starts, first look, after / before', ['first look']);
  one('T2a', 'Round 1, CPU per map', ['map cpu']);
  one('T2a', 'Round 1, wall per map', ['map wall']);
  one('T2b', 'Round 2, CPU per map', ['map cpu']);
  one('T2b', 'Round 2, wall per map', ['map wall']);
  one('T3', 'Lake Basin round 2, wall per map', ['map wall']);
  one('T4', 'Tip against dev at 256², wall per map', ['map wall']);
  one('T4', 'Tip against dev at 256², CPU per map', ['map cpu']);
  w();
  const rs = recs.filter((r) => !r.error && r.v !== undefined);
  w(`Raw: ${path.relative(ROOT, path.join(dir, 'results.jsonl'))} (${rs.length} timed runs, each with its load); load.jsonl (one line per second); gates.log; warmups.jsonl.`);
  return out.join('\n') + '\n';
}

if (!has('child')) await main();
