import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';
import {createHash} from 'node:crypto';
const HERE=dirname(fileURLToPath(import.meta.url)),ROOT=resolve(HERE,'../..'),LOCAL=resolve(HERE,'local');mkdirSync(LOCAL,{recursive:true});
const base=readFileSync(resolve(ROOT,'src/core/land/hydro.ts'),'utf8').replaceAll('\r\n','\n');
let after=base;
const edit=(from,to)=>{if(after.split(from).length!==2)throw Error('Source hook changed: '+from);after=after.replace(from,to);};
edit('import { distanceFrom }','import { distanceFrom, MinHeap }');
edit('export function planHydro(',readFileSync(resolve(HERE,'delta-course.ts'),'utf8')+'\nexport function planHydro(');
edit('    const fan = g.theme === "delta";', '    const fan = g.theme === "delta";\n'+readFileSync(resolve(HERE,'delta-main-bed.ts'),'utf8'));
edit('    const armBeds:', '    const deltaGround = fan ? h.slice() : null;\n    const armBeds:');
edit('      const armPath = smoothPath(pts, 1, 1);', '      const armPath = fan && natural ? deltaCourse(p0, [ex, ey], E, W, H, gap, hash32(seed, "delta-course", attempt, a), protect) : smoothPath(pts, 1, 1);');
edit('const awv = natural ? { ...wanderOf(g, aw), amp: fan ? 2.5 : 1.5, minAmp: 1 } : null;', 'const awv = natural ? (fan ? { ...wanderOf(g, aw), amp: clamp(gap * 0.18, 3.5, 7), minAmp: 2.8, cell: clamp(gap * 1.5, 16, 28), widthVar: 0.5 } : { ...wanderOf(g, aw), amp: 1.5, minAmp: 1 }) : null;');
edit('      carve(pa.st, pa.prof, pa.L, pa.n, ahalf, 0);\n      markArm(pa.st, pa.L, ahalf);\n      armBeds.push', '      carve(pa.st, pa.prof, pa.L, pa.n, ahalf, fan ? 1.8 : 0);\n      markArm(pa.st, pa.L, ahalf);\n'+readFileSync(resolve(HERE,'braid.ts'),'utf8')+'      armBeds.push');
edit('const armBeds: { prof: Float64Array; L: number; n: number }[] = [];', 'const armBeds: { prof: Float64Array; L: number; n: number; course: Point[]; st: Stamp; half: (s:number,L:number)=>number }[] = [];\n    const braidBeds: typeof armBeds = [];');
edit('const ahalf = (s: number, L: number) => halfWidthAt(aw, awv, aws, s, L);\n      const j0', 'const ahalf = (s: number, L: number) => fan ? Math.max(MIN_WIDTH / 2, halfWidthAt(aw, awv, aws, s, L)) : halfWidthAt(aw, awv, aws, s, L);\n      const j0');
edit('meanderPath(armPath, h, W, H, awv, hash32(seed, \"arm\", attempt, 1 + a))', 'meanderPath(armPath, fan ? deltaGround! : h, W, H, awv, hash32(seed, \"arm\", attempt, 1 + a))');
edit('(fan ? 0.4 : 0.6) * m.width', '(fan ? 0.55 : 0.6) * m.width');
edit('armBeds.push({ prof: pa.prof, L: pa.L, n: pa.n });','armBeds.push({ prof: pa.prof, L: pa.L, n: pa.n, course:armCourse, st:pa.st, half:ahalf });');
edit('arms.push({kind:"split", river:main.id, path:branch});','braidBeds.push({prof:bp.prof,L:bp.L,n:bp.n,course:branch,st:bp.st,half});\n            arms.push({kind:"split", river:main.id, path:branch});');
edit('if (!(\"river\" in r.params.exit)) continue;\n      const m = exits.get(r.id);', 'if (!(\"river\" in r.params.exit) && !(g.theme === \"delta\" && r.role === \"river/main\")) continue;\n      const m = exits.get(r.id);');
edit('ahalf, m.prof[j0]);\n      carve(pa.st', 'ahalf, fan ? Math.max(BED_FLOOR, Math.min(m.prof[j0], deltaGround![Math.round(clamp(p0[1], 0, H - 1)) * W + Math.round(clamp(p0[0], 0, W - 1))]) - 1) : m.prof[j0]);\n      carve(pa.st');
const bedStart=after.indexOf('      const bed = pb.prof.slice();'),bedEnd=after.indexOf('      markArm(pb.st, pb.L, bhalf);',bedStart);
if(bedStart<0||bedEnd<0)throw Error('Delta bed hook changed');
after=after.slice(0,bedStart)+readFileSync(resolve(HERE,'fan-beds.ts'),'utf8')+after.slice(bedEnd);
writeFileSync(resolve(LOCAL,'hydro.after.ts'),after);writeFileSync(resolve(LOCAL,'hydro.before.ts'),base);
// Project only M9b's promise/water outcomes. Do not collect its timing/CPU/other measures.
const measures=readFileSync(resolve(ROOT,'investigation/m9b/measures.ts'),'utf8');
const expression=measures.match(/^    outcomes: (.+),\r?$/m)?.[1];if(!expression)throw Error('M9b outcome projection changed');
writeFileSync(resolve(LOCAL,'measure-outcomes.ts'),'export const project=(r:any)=>('+expression+');\n');
for(const mode of ['before','after'])await build({entryPoints:[resolve(HERE,'run-one.ts')],outfile:resolve(LOCAL,mode+'.cjs'),bundle:true,platform:'node',format:'cjs',target:'node22',logLevel:'error',plugins:[{name:'delta-only',setup(b){b.onLoad({filter:/[/\\]core[/\\]land[/\\]hydro\.ts$/},()=>({contents:mode==='after'?after:base,loader:'ts',resolveDir:resolve(ROOT,'src/core/land')}));}}]});
const sha=s=>createHash('sha256').update(s).digest('hex');writeFileSync(resolve(LOCAL,'build.json'),JSON.stringify({base:JSON.parse(readFileSync(resolve(HERE,'BASE.json'))).sha,before:sha(base),after:sha(after),measures:sha(measures),timings:false},null,2)+'\n');console.log('Built before/after with only Delta-gated shaping changed.');
