// Refuse to publish pins from partial, mismatched or failed evidence.
import {readFileSync,readdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {HERE,LOCAL,hash} from './common.mjs';
const read=name=>JSON.parse(readFileSync(resolve(LOCAL,name+'.json')));
const requireTrue=(ok,message)=>{if(!ok)throw Error(message);};
const root=rows=>hash(JSON.stringify(rows));
const byId=(a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0;
function proof(name,total){const s=read(name+'-summary');requireTrue(s.total===total&&s.complete===total&&!s.partial&&!s.sizeShard,name+' is incomplete');requireTrue(!s.errors?.length&&!s.mismatches?.length,name+' failed');return s;}
const generation=proof('generation',840),water={};
for(const [name,total]of [['forced',24],['official',19],['map-water',840],['weather',27]]){const s=proof(name,total);requireTrue(JSON.stringify(s.counts)==='[1,2,3,4,7,8,16]',name+' lacks thread counts');requireTrue(s.comparisons===total*21,name+' lacks comparisons');const rows=readdirSync(resolve(LOCAL,name)).filter(f=>f.endsWith('.json')).map(f=>JSON.parse(readFileSync(resolve(LOCAL,name,f))));requireTrue(rows.length===total,name+' lacks per-case evidence');for(const r of rows)requireTrue(r.results.length===21&&r.results.every(x=>JSON.stringify([x.hash,x.ticks,x.volume,x.result,x.rows])===JSON.stringify([r.results[0].hash,r.results[0].ticks,r.results[0].volume,r.results[0].result,r.results[0].rows])),name+' row differs');water[name]={cases:total,comparisons:s.comparisons,checks:s.checks,directChecks:s.directChecks,helperDispatches:s.dispatched,pin:root(rows.map(r=>[r.id,r.results[0].hash,r.results[0].ticks,r.results[0].volume,r.results[0].result,r.results[0].rows]).sort(byId))};}
const gen=read('generation-manifest');requireTrue(gen.length===840,'Generation manifest missing');
const changed={},refusals=[];
for(const r of gen){requireTrue(r.fingerprint===generation.fingerprint,'Stale generation row');const ref=r.results.chromium.adopted;requireTrue(Object.keys(r.results).length===3&&Object.values(r.results).every(x=>x.adopted.hash===ref.hash),'Generation row differs');if(!ref.passed)refusals.push(r.id);for(const [engine,x]of Object.entries(r.results))for(const key of Object.keys(ref.components))if(x.baseline.components[key]!==x.adopted.components[key]){changed[engine]??={};(changed[engine][key]??=[]).push(r.id);}}
const genPins={all:root(gen.map(r=>[r.id,r.results.chromium.adopted.hash]).sort(byId)),sizes:Object.fromEntries([96,128,256].map(size=>[size,root(gen.filter(r=>r.id.includes('-'+size+'-')).map(r=>[r.id,r.results.chromium.adopted.hash]).sort(byId))]))};
const fixtures=proof('fixtures',43),fixtureRows=read('fixtures-manifest');requireTrue(fixtureRows.length===43,'Fixture manifest incomplete');
const fixturePins=Object.fromEntries(['official','golden'].map(kind=>[kind,root(fixtureRows.filter(r=>r.id.startsWith(kind+'-')).map(r=>[r.id,r.results.chromium.adopted.hash]).sort(byId))]));
const forces=read('forces-adoption/summary');requireTrue(forces.cases===316&&!forces.mismatches.length&&Object.values(forces.engines).every(e=>e.checkpoints===1716&&!e.errors.length),'Forces proof incomplete');
const forceChanges=read('forces-full-changes');requireTrue(forceChanges.cases===316&&Object.values(forceChanges.engines).every(r=>r.checkpoints===1716&&r.changed===0),'Current force/session results changed');
const forceRows=read('forces-adoption/chromium'),forcePin=root(forceRows.map(r=>[r.label,r.hash]).sort(byId));
for(const e of ['firefox','webkit'])requireTrue(root(read('forces-adoption/'+e).map(r=>[r.label,r.hash]).sort(byId))===forcePin,'Force checkpoint differs');
const carve=proof('carve',54),carvePin=root(read('carve-manifest').map(r=>[r.id,r.results.chromium.adopted.hash]).sort(byId));
const gestures=read('gestures-summary'),gestureRows=read('gestures-manifest');requireTrue(gestures.cases===396&&!gestures.mismatches.length&&gestureRows.length===1188,'Gesture proof incomplete');
const gesturePins=Object.fromEntries(['legacy','dev'].map(revision=>[revision,root(gestureRows.filter(r=>r.engine==='chromium'&&r.revision===revision).map(r=>[r.id,r.after]).sort(byId))]));
const camera={};for(const name of ['three','three-dev']){const s=read(name+'-summary'),rows=read(name+'-manifest').filter(r=>r.mode==='after');requireTrue(s.cases===1512&&!s.mismatches.length&&s.dependency.remaining===0&&rows.length===3,'Camera proof incomplete');requireTrue(rows.every(r=>root(r.hashes)===root(rows[0].hashes)),'Camera differs');camera[name]={cases:s.cases,pin:root(rows[0].hashes),changes:s.changes,dependency:s.dependency};}
const curves=read('curves-summary'),curveRows=read('curves-full');requireTrue(!curves.adoptedMismatches.length,'Weather forcing differs');const curvePin=root([curveRows.chromium.adopted.native,curveRows.chromium.adopted.fractionalNative]);
for(const e of ['firefox','webkit'])requireTrue(root([curveRows[e].adopted.native,curveRows[e].adopted.fractionalNative])===curvePin,'Weather probe differs');
const math=read('math-summary'),rustMath=read('rust-math-summary'),rust=read('rust-build-summary'),plants=read('guard-plants'),compression=read('compression-summary'),audit=read('audit'),reconciliation=read('build-reconciliation');
requireTrue(math.nodeChecks===108198&&math.browserChecks.length===6&&math.browserChecks.every(r=>r.checks===12548),'Exact sqrt evidence incomplete');requireTrue(rustMath.nativeChecks===47074&&Object.values(rustMath.engines).every(r=>r.checks===47074),'Rust vector evidence incomplete');requireTrue(rust.rows.length===8&&rust.rows.every(r=>r.status==='pass'),'Rust build evidence incomplete');requireTrue(plants.rows.length===40&&plants.rows.every(r=>r.status==='expected rejection'),'Guard planted failures incomplete');requireTrue(compression.memoryDecisions===500001&&compression.byteFixtures===65&&!compression.changed&&compression.nativeLogTrapped,'Compression evidence incomplete');requireTrue(Object.values(audit).every(r=>!r.remaining.length),'Native calls remain');requireTrue(reconciliation.length===8&&reconciliation.every(r=>r.identical),'Final bundle changed');
const embedded=read('embedded-summary'),quick=read('quick-proof');requireTrue(embedded.cases===58&&!embedded.mismatches.length&&new Set(Object.values(embedded.pins)).size===1&&embedded.bindings===hash(readFileSync(resolve(HERE,'portable-page.ts'))),'Embedded script proof incomplete');requireTrue(quick.newFailures===0&&quick.baselineFailures===15&&quick.passed===836,'Optional product checks changed');
const profile=read('profile-summary');requireTrue(profile.records.length===27&&profile.records.every(r=>r.load.samples>0&&r.provisional===(r.load.mean===null||r.load.mean>20)),'Timing CPU cohorts incomplete');
requireTrue(read('output-guard').remaining.length===0,'Production output native maths remains');
const sources=read('rust-sources');requireTrue(rustMath.source===sources.portable,'Rust vector source changed');const latest=read('latest-dev'),weatherRevisions=read('weather-revisions-summary');requireTrue(latest.weather.sourceIdentical&&latest.weather.mathSourceIdentical,'Latest dev Weather changed');
const movingM9b=read('moving-m9b');requireTrue(movingM9b.weather.sourceIdenticalToDev&&movingM9b.weather.mathSourceIdenticalToDev&&!movingM9b.remaining.length,'Latest M9b maths audit failed');
const nativeWeather=read('native-weather-summary');requireTrue(nativeWeather.total===27&&nativeWeather.complete===27&&!nativeWeather.errors.length,'Original full Weather states incomplete');
const nativeRows=readdirSync(resolve(LOCAL,'native-weather')).filter(f=>f.endsWith('.json')).map(f=>JSON.parse(readFileSync(resolve(LOCAL,'native-weather',f))));requireTrue(nativeRows.length===27,'Original Weather rows incomplete');
const nativeWeatherPins=Object.fromEntries(['chromium','firefox','webkit'].map(engine=>[engine,root(nativeRows.map(r=>{const s=r.results.find(s=>s.engine===engine);return [r.id,s.hash,s.ticks,s.volume,s.result,s.rows];}).sort(byId))]));
const weatherStates=Object.fromEntries(['chromium','firefox','webkit'].map(engine=>[engine,[]]));
for(const before of nativeRows){const after=read('weather/'+before.id);requireTrue(before.inputHash===after.inputHash&&before.results.length===3,'Weather before/after input differs');for(const b of before.results){const a=after.results.find(r=>r.engine===b.engine&&r.threads===1);requireTrue(a&&b.directChecks===b.checks,'Native Weather scalar oracle missing');const identity=r=>JSON.stringify([r.hash,r.ticks,r.volume,r.result,r.rows]);if(identity(a)!==identity(b)){const changedSnapshots=b.rows.filter((r,i)=>JSON.stringify(r)!==JSON.stringify(a.rows[i]));weatherStates[b.engine].push({id:before.id,canonicalChanged:b.hash!==a.hash,changedSnapshots:changedSnapshots.length,stages:[...new Set(changedSnapshots.map(r=>r.stage))]});}}}
const changes={generation:changed,fixtures:fixtures.changes,carve:carve.changes,gestures:gestureRows.filter(r=>r.before!==r.after).map(({engine,revision,id})=>({engine,revision,id})),camera,weatherProbe:curves.changes,weatherStates,devForces:read('forces-full-changes'),officialBatch:read('tools-summary')};
const results={schema:1,experimentalSource:generation.source,devOracle:weatherRevisions.dev,latestDevChecked:latest.latest,m9bPublishedDuringRun:movingM9b,engines:generation.engines,platform:generation.platform,scope:{m9bReferences:audit.m9b.inventory.length,devReferences:audit.dev.inventory.length,threeReferences:audit.three.inventory.length,rustReferences:audit.rust.inventory.length,remaining:0},generation:{cases:840,refusals:refusals.sort(),pins:genPins,changes:generation.changes},water,fixtures:{cases:43,pins:fixturePins,changes:fixtures.changes,originalArchives:fixtureRows.filter(r=>r.id.startsWith('official-')).map(r=>({id:r.id,sha256:r.inputHash}))},forces:{cases:316,checkpointsPerEngine:1716,pin:forcePin},carve:{cases:54,pin:carvePin,changes:carve.changes},gestures:{cases:396,pins:gesturePins,changes:gestures.changes},camera,weather:{nativeStateOracle:{cases:27,fingerprint:nativeWeather.fingerprint,pins:nativeWeatherPins,changes:weatherStates},revisions:weatherRevisions,terms:read('weather-exp-terms'),probePin:curvePin,changes:curves.changes},math:{nodeChecks:math.nodeChecks,browserChecks:75288,rustChecksPerTarget:47074,rustSource:rustMath.source,rustArtifacts:Object.fromEntries(Object.entries(rustMath.artifacts).map(([target,{path,...pins}])=>[target,pins]))},rust:{compiler:rust.compiler,portableSha256:sources.portable,sources:Object.fromEntries(Object.entries(sources.studies).map(([name,s])=>[name,{inputs:s.inputs,nativeReferences:s.native.length,remaining:s.remaining.length,rustPin:s.rustPin}])),builds:rust.rows.map(r=>({study:r.study,target:r.target,artifacts:r.artifacts.map(a=>({kind:a.kind,sha256:a.sha256})),linked:r.linked.map(a=>({sha256:a.sha256}))}))},guards:{plantedFailures:plants.rows},embedded,productQuickChecks:quick,compression,timing:{records:27,provisional:profile.records.filter(r=>r.provisional).length,cpuMeanRange:[Math.min(...profile.records.map(r=>r.load.mean)),Math.max(...profile.records.map(r=>r.load.mean))],runtime:profile.runtime},bundles:{generationFingerprint:generation.fingerprint,finalSourceBuild:read('final-build/build'),reconciliation},productionOutput:read('output-guard'),adoptionIntegration:read('adoption-integration'),patches:Object.fromEntries(['adoption','dev-adoption','rust-adoption'].map(n=>[n,{sha256:hash(readFileSync(resolve(HERE,n+'.patch')))}]))};
// Keep the compact identity pins and changed case IDs; large raw records stay ignored.
delete results.bundles.finalSourceBuild.inputs;delete results.timing.runtime.executablePath;
writeFileSync(resolve(HERE,'RESULTS.json'),JSON.stringify(results,null,2)+'\n');writeFileSync(resolve(HERE,'CHANGES.json'),JSON.stringify(changes,null,2)+'\n');
const counts=Object.fromEntries(Object.entries(changed).map(([e,cs])=>[e,Object.fromEntries(Object.entries(cs).map(([k,ids])=>[k,ids.length]))]));
writeFileSync(resolve(HERE,'REPORT.md'),`# Portable maths everywhere

Adoption patches only; product files were never edited. Experiment: M9b ${generation.source.slice(0,8)}. Dev oracle: ${weatherRevisions.dev.slice(0,8)}; latest dev checked: ${latest.latest.slice(0,8)}.

The initial M9b fractional Weather probe reproduces WebKit's difference; dev/D366 does not. Latest M9b ${movingM9b.latest.slice(0,8)} now contains the same fix. The 840-map proof stays pinned to the initial head. The cause is badtideContamination's shape, src/core/sim/weather.ts: at day .35, tick 22, x=-2.5500000000000003, native exp(-x) differs by one low bit (40299d3cb4fe0800 versus WebKit …0801). That changes forcing by one ULP and propagates to 13 contamination frames. Exact term bits are in RESULTS.json.

All adopted ordered bytes/raw binary64 bits match in Chromium 145, Firefox 146 and WebKit 26 on Windows x64:

- 840 M9b generation cases (including ${refusals.length} existing quality refusals), water on every regenerated model, 19 original official archives, and 12 golden terrains under both water rules.
- Thread counts 1,2,3,4,7,8,16; every-tick forced golden dispatch; analysis/validation/export contracts; 27 complete Weather scenarios plus the fractional probe.
- 316 dev force/editor/session cases, 54 M9b Carve cases, 396 gestures, 1,512 actual camera/ray/picking cases per revision and 58 evaluated-script checks.
- 47,074 shared Rust vectors per native/browser target, eight strict native/Wasm builds, exact sqrt fallback, dependency traps and all 40 planted guard rejections.

CHANGES.json identifies changed cases; RESULTS.json re-pins their outputs. Generation components: ${JSON.stringify(counts)}; exports stay identical. Official/golden and batch aggregates stay identical. Carve changes 54 heads and 13 metrics, preserving maps/records. Firefox/WebKit change 3 legacy and 27 dev fractional Editor lengths. All 756 orbit-camera cases change per revision. Current dev forces/sessions stay identical. Weather changes 3 standard probe frames per engine and 4 fractional frames in Chromium/Firefox or 15 in WebKit. Full-state scenarios changed: ${JSON.stringify(Object.fromEntries(Object.entries(weatherStates).map(([e,r])=>[e,r.length])))}.

Whole-source adoption leaves zero native maths references: ${audit.m9b.inventory.length}/${audit.dev.inventory.length} product/batch and ${audit.three.inventory.length} Three references audited, plus Rust sqrt/remainder sites. INTEGRATION.md records source pins, input/presentation boundaries and actual-source CI. The optional product quick suite has 836 passes, 15 identical baseline failures and 13 skips.

All 27 Firefox timings use the corrected optimizing tier and individual CPU sampling. Every timing is provisional (${results.timing.cpuMeanRange[0].toFixed(1)}–${results.timing.cpuMeanRange[1].toFixed(1)}% mean CPU); no speed claim. Large raw results remain in ignored local/.
`);
