import {readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {deps,HERE,LOCAL,files,json,hash} from './common.mjs';
import {threeRoot} from './three-common.mjs';
import {transformThree} from './three-plugin.mjs';
import {adoptionPlugin,native} from './transform.mjs';
import {violations} from './guard.mjs';
import {host} from './host.mjs';
const actual=process.argv.includes('--actual'),dev=process.argv.includes('--dev'),prefix=dev?'three-dev':'three',root=threeRoot(),audit=[],remaining=[];
for(const file of [...files(resolve(root,'src')),...files(resolve(root,'build'))]){const source=readFileSync(file,'utf8'),name=file.slice(root.length+1).replaceAll('\\','/'),before=violations(source,'dependency/three/'+name).filter(v=>!v.text.startsWith('Math.random')),after=transformThree(source,file,resolve(HERE,'portable.ts').replaceAll('\\','/'));
 audit.push(...before.map(v=>({file:name,line:v.line,text:v.text})));remaining.push(...violations(after,'dependency/three/'+name).filter(v=>!v.text.startsWith('Math.random')));
}
if(remaining.length)throw Error('Unported Three maths '+JSON.stringify(remaining.slice(0,5)));
const plugin={name:'portable-three-probe',setup(b){b.onLoad({filter:/node_modules[\\/]three[\\/].*\.js$/},({path})=>({contents:transformThree(readFileSync(path,'utf8'),path,resolve(HERE,'portable.ts').replaceAll('\\','/')),loader:'js',resolveDir:resolve(path,'..')}));}};
const entry=resolve(LOCAL,prefix+'-probe.ts');writeFileSync(entry,readFileSync(resolve(HERE,'three-probe.ts'),'utf8').replace("'../../src/render3d/renderer'",JSON.stringify(resolve(dev?resolve(LOCAL,'dev'):resolve(HERE,'../..'),'src/render3d/renderer.ts').replaceAll('\\','/'))));
for(const mode of ['before','after'])await deps('esbuild').build({entryPoints:[entry],outfile:resolve(LOCAL,prefix+'-'+mode+'.js'),bundle:true,format:'esm',platform:'browser',alias:{three:resolve(root,'build/three.module.js')},plugins:mode==='after'?[plugin,...(actual?[]:[adoptionPlugin()])]:[]});
const cases=[];for(const size of [96,128,256])for(const mode of ['orbit','top'])for(const yaw of [-2.5,-1,-.5235987755982988,0,.35,1,2.5])for(const pitch of [.18,.6,1.2217304763960306,1.5])for(const [x,y]of [[0,0],[.25,.25],[.5,.5],[.75,.75],[1,1],[.5-1e-14,.5],[.5+1e-14,.5],[.375,.625],[.123456789,.876543211]])cases.push({size,mode,yaw,pitch,x,y});
const h=await host(),summary={cases:cases.length,dependency:{version:JSON.parse(readFileSync(resolve(root,'package.json'))).version,native:audit.length,remaining:remaining.length},engines:{},mismatches:[],changes:{}},rows=[];
try{for(const name of ['chromium','firefox','webkit']){const b=await deps('playwright')[name].launch({headless:true});try{summary.engines[name]=b.version();for(const mode of ['before','after']){const p=await b.newPage();await p.goto(h.url,{waitUntil:'domcontentloaded',timeout:120000});await p.addScriptTag({url:h.url+prefix+'-'+mode+'.js',type:'module'});await p.waitForFunction(()=>window.cameraProbe);const values=await p.evaluate(async({cases,poison})=>{if(poison)for(const n of ['sin','cos','tan','asin','acos','atan','atan2','exp','log','log2','pow','hypot','sqrt'])(Math)[n]=()=>{throw Error('Native Three '+n);};const rows=[];for(const c of cases){const bytes=new TextEncoder().encode(window.cameraProbe(c)),digest=await crypto.subtle.digest('SHA-256',bytes);rows.push(Array.from(new Uint8Array(digest),n=>n.toString(16).padStart(2,'0')).join(''));}return rows;},{cases,poison:mode==='after'});rows.push({engine:name,mode,hashes:values});await p.close();console.log('Camera cohort',name,mode,values.length);}}finally{await b.close();}}}finally{h.close();}
const adopted=rows.filter(r=>r.mode==='after'),ref=adopted[0].hashes;for(let i=0;i<cases.length;i++)for(const row of adopted){if(row.hashes[i]!==ref[i])summary.mismatches.push({engine:row.engine,case:i});if(row.hashes[i]!==rows.find(r=>r.engine===row.engine&&r.mode==='before').hashes[i])summary.changes[row.engine]=(summary.changes[row.engine]??0)+1;}
summary.bundles=Object.fromEntries(['before','after'].map(m=>[m,hash(readFileSync(resolve(LOCAL,prefix+'-'+m+'.js')))]));json(prefix+'-summary.json',summary);json(prefix+'-manifest.json',rows);json('three-audit.json',audit);console.log('Three camera/ray',summary.cases,'cases',summary.mismatches.length,'mismatches',summary.changes);if(summary.mismatches.length)process.exitCode=1;
