// Writes src/tables.rs: the data and constants the checks read from modules outside src/core/validate (the
// footprints, the starting-logs floor, the calibrated targets, the difficulty rules), taken from the TypeScript
// itself so the two cannot drift. `--check` fails when the committed file differs.
//
//   npx tsx host/gen-tables.ts [--check]        (run from this folder; DGM_ORACLE names the TypeScript checkout)

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { oracle } from "./oracle";

const { FOOTPRINTS } = await import(oracle("src/core/format/footprints.ts"));
const logFloor = await import(oracle("src/core/data/logFloor.ts"));
const cal = await import(oracle("src/core/gen/calibrated.ts"));
const spec = await import(oracle("src/core/spec/mapspec.ts"));
const water = await import(oracle("src/core/sim/water.ts"));
const world = await import(oracle("src/core/format/world.ts"));
const objects = await import(oracle("src/core/features/objects.ts"));
const model = await import(oracle("src/core/sim/model.ts"));

const f = (v: number) => {
  if (!Number.isFinite(v)) throw new Error(`non-finite constant ${v}`);
  const s = String(v);
  return /[.e]/.test(s) ? s.replace(/^(-?\d+)e/, "$1.0e") : `${s}.0`;
};
const str = (s: string) => JSON.stringify(s);
const BELOW = ["ground", "groundOrStackable", "any", "air", "stackable"];

const out: string[] = [];
out.push("// Generated by host/gen-tables.ts from the TypeScript (footprints.json, log-floor.json, calibrated.ts,");
out.push("// mapspec.ts, water.ts, world.ts, objects.ts, model.ts). Do not edit: rerun it.");
out.push("#![allow(dead_code)]");
out.push("");
out.push("pub struct Block { pub x: i32, pub y: i32, pub z: i32, pub below: u8, pub flags: u32, pub stackable: bool, pub occupy_all_below: bool }");
out.push("pub struct Footprint { pub size: [i32; 3], pub flippable: bool, pub blocks: &'static [Block] }");
out.push(`/// Matter below, in the order of \`MatterBelow\`: ${BELOW.join(", ")}.`);
BELOW.forEach((b, k) => out.push(`pub const BELOW_${b.replace(/[A-Z]/g, (c) => `_${c}`).toUpperCase()}: u8 = ${k};`));
out.push("pub fn footprint(template: &str) -> Option<&'static Footprint> {");
out.push("    match template {");
for (const name of Object.keys(FOOTPRINTS).sort()) {
  const fp = FOOTPRINTS[name];
  const blocks = fp.blocks
    .map(([x, y, z, below, flags, stack, oab]: [number, number, number, string, number, number, number]) => {
      const b = BELOW.indexOf(below);
      if (b < 0) throw new Error(`unknown matter below ${below}`);
      return `Block { x: ${x}, y: ${y}, z: ${z}, below: ${b}, flags: ${flags}, stackable: ${!!stack}, occupy_all_below: ${!!oab} }`;
    })
    .join(", ");
  out.push(`        ${str(name)} => Some(&Footprint { size: [${fp.size.join(", ")}], flippable: ${fp.flippable}, blocks: &[${blocks}] }),`);
}
out.push("        _ => None,");
out.push("    }");
out.push("}");
out.push("");
out.push(`pub const LOG_FLOOR: f64 = ${f(logFloor.LOG_FLOOR)};`);
out.push(`pub const LOG_FLOOR_WALK: f64 = ${f(logFloor.LOG_FLOOR_WALK)};`);
out.push("pub fn logs_per_tree(template: &str) -> Option<f64> {");
out.push("    match template {");
for (const [k, v] of Object.entries(logFloor.LOGS_PER_TREE_SPECIES as Record<string, number>)) out.push(`        ${str(k)} => Some(${f(v)}),`);
out.push("        _ => None,");
out.push("    }");
out.push("}");
out.push("/// `DEAD_TREES_KEEP_LOGS[template] === false`.");
out.push("pub fn dead_tree_loses_logs(template: &str) -> bool {");
const loses = Object.entries(logFloor.DEAD_TREES_KEEP_LOGS as Record<string, boolean>).filter(([, v]) => v === false).map(([k]) => str(k));
out.push(loses.length ? `    matches!(template, ${loses.join(" | ")})` : "    let _ = template;\n    false");
out.push("}");
out.push("");
out.push("/// Difficulties in the order easy, normal, hard.");
out.push(`pub const DIFFICULTIES: [&str; 3] = ["easy", "normal", "hard"];`);
const D = ["easy", "normal", "hard"];
out.push("/// DIFFICULTY_RULES: waterWithin, woodWithin20, bushesWithin20, badwaterWithin, ruinsWithin.");
out.push(`pub const DIFFICULTY_RULES: [[f64; 5]; 3] = [${D.map((d) => { const r = spec.DIFFICULTY_RULES[d]; return `[${[r.waterWithin, r.woodWithin20, r.bushesWithin20, r.badwaterWithin, r.ruinsWithin].map(f).join(", ")}]`; }).join(", ")}];`);
out.push(`/// DROUGHT: days, colony.`);
out.push(`pub const DROUGHT: [[f64; 2]; 3] = [${D.map((d) => `[${f(cal.DROUGHT[d].days)}, ${f(cal.DROUGHT[d].colony)}]`).join(", ")}];`);
out.push(`pub const RESERVOIR_NEEDED: [f64; 3] = [${D.map((d) => f(cal.reservoirNeeded(d))).join(", ")}];`);
const kv = (name: string, o: Record<string, number>) => {
  out.push(`pub fn ${name}(key: &str) -> Option<f64> {`);
  out.push("    match key {");
  for (const [k, v] of Object.entries(o)) out.push(`        ${str(k)} => Some(${f(v)}),`);
  out.push("        _ => None,");
  out.push("    }");
  out.push("}");
};
kv("reach_min", cal.REACH_MIN);
kv("reserve", cal.RESERVE);
out.push(`pub const LIVING_SHARE: [f64; 2] = [${cal.OFFICIAL_LAYOUT.livingShare.map(f).join(", ")}];`);
out.push(`pub const SIZE_ANCHORS: [f64; 4] = [${cal.SIZE_ANCHORS.map(f).join(", ")}];`);
for (const k of ["scrap_per_1k_tiles", "trees_per_10k", "bushes_per_10k"]) out.push(`pub const DENSITY_${k.toUpperCase()}: [f64; 4] = [${cal.DENSITY[k].map(f).join(", ")}];`);
for (const k of ["trees", "bushes", "scrap"]) out.push(`pub const SPREAD_${k.toUpperCase()}: [f64; 2] = [${cal.SPREAD[k].map(f).join(", ")}];`);
out.push(`pub const SMALL_MAP: f64 = ${f(spec.SMALL_MAP)};`);
out.push(`pub const SETTLE_DAYS: f64 = ${f(water.SETTLE_DAYS)};`);
out.push(`pub const TICKS_PER_DAY: f64 = ${f(water.TICKS_PER_DAY)};`);
out.push(`pub const DT: f64 = ${f(water.DT)};`);
out.push("/// sim/model.ts EMITTERS: local tiles, contamination, runs at map start, seep.");
out.push("pub struct EmitterRule { pub tiles: &'static [(i64, i64)], pub contamination: f64, pub runs: bool, pub seep: bool }");
out.push("pub fn emitter_rule(template: &str) -> Option<&'static EmitterRule> {");
out.push("    match template {");
for (const [k, r] of Object.entries(model.EMITTERS as Record<string, { tiles: [number, number][]; contamination: number; runs: boolean; seep?: boolean }>))
  out.push(`        ${str(k)} => Some(&EmitterRule { tiles: &[${r.tiles.map(([x, y]) => `(${x}, ${y})`).join(", ")}], contamination: ${f(r.contamination)}, runs: ${r.runs}, seep: ${!!r.seep} }),`);
out.push("        _ => None,");
out.push("    }");
out.push("}");
out.push(`pub const MAX_STRENGTH_PER_TILE: f64 = ${f(model.MAX_STRENGTH_PER_TILE)};`);
out.push(`pub const GAME_VERSION: &str = ${str(world.GAME_VERSION)};`);
out.push(`pub const GAME_MAX_HEIGHT: f64 = ${f(world.GAME_MAX_HEIGHT)};`);
out.push(`pub const EDITOR_MAX_HEIGHT: f64 = ${f(world.EDITOR_MAX_HEIGHT)};`);
out.push(`pub const MAX_OBJECT_Z: i64 = ${world.MAX_OBJECT_Z};`);
out.push("pub fn object_name(kind: &str) -> Option<&'static str> {");
out.push("    match kind {");
for (const [k, v] of Object.entries(objects.OBJECT_NAMES as Record<string, string>)) out.push(`        ${str(k)} => Some(${str(v)}),`);
out.push("        _ => None,");
out.push("    }");
out.push("}");
out.push("");

const text = out.join("\n");
const path = join(import.meta.dirname, "..", "src", "tables.rs");
if (process.argv.includes("--check")) {
  if (readFileSync(path, "utf8").replace(/\r\n/g, "\n") !== text) {
    console.error("src/tables.rs is stale: rerun host/gen-tables.ts");
    process.exit(1);
  }
  console.log("tables PASS");
} else {
  writeFileSync(path, text);
  console.log(`wrote ${path}`);
}
