import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync,readdirSync} from 'node:fs';
import {resolve,join,relative} from 'node:path';
import {assertClean} from '../../tools/rust/guard.mjs';
const tree=resolve(import.meta.dirname,'local/adopted'),rust=join(tree,'rust');
const rs=(dir:string):string[]=>readdirSync(dir,{withFileTypes:true}).flatMap(d=>d.name==='target'?[]:d.isDirectory()?rs(join(dir,d.name)):d.name.endsWith('.rs')?[join(dir,d.name)]:[]);
const remaps=rs(rust).map(f=>{const rel=relative(rust,f);return '--remap-path-prefix='+rel+'='+rel.replaceAll('\\','/');});
const env={...process.env,PATH:'C:/Users/Kyler/.cargo/bin;'+process.env.PATH,CARGO_ENCODED_RUSTFLAGS:remaps.join('\x1f')};
execFileSync('C:/Users/Kyler/.cargo/bin/cargo.exe',['build','--release','-j','2','-p','forces','--lib','--target','wasm32-unknown-unknown','--target-dir','target/embed'],{cwd:rust,env,stdio:'inherit',windowsHide:true});
const wasm=readFileSync(join(rust,'target/embed/wasm32-unknown-unknown/release/forces.wasm'));assertClean('wasm',wasm);
if(WebAssembly.Module.imports(new WebAssembly.Module(wasm)).length)throw Error('Wasm imports');
const text='// Generated by tools/rust/build.ts from rust/forces (Rust 1.90.0, wasm32-unknown-unknown): do not edit.\n'+
"// CI's `rust` job rebuilds it and fails when it differs (PLAN §20 D381, D442).\n"+'// '+wasm.length+' bytes.\n'+
'export const FORCES_WASM = /* @__PURE__ */ [\n'+wasm.toString('base64').match(/.{1,120}/g)!.map(l=>'  "'+l+'",').join('\n')+'\n].join("");\n';
writeFileSync(join(tree,'src/core/forces/rust/forcesWasm.ts'),text);
const { CARGO_ENCODED_RUSTFLAGS: _remaps, ...nativeEnv } = env;
execFileSync('C:/Users/Kyler/.cargo/bin/cargo.exe',['build','--release','-j','2','-p','forces','--bin','forces-batch'],{cwd:rust,env:nativeEnv,stdio:'inherit',windowsHide:true});
console.log('forces-only rebuild: '+wasm.length+' bytes; guard clean');