import {readFileSync,writeFileSync} from 'node:fs';
import {sediment} from './metrics';
const b='investigation/deposit-pillars';
const before=JSON.parse(readFileSync(`${b}/local/before/summary.json`,'utf8'));
const after=JSON.parse(readFileSync(`${b}/local/lobes/summary.json`,'utf8'));
if(before.length!==14||after.length!==14||after.some((r:any)=>r.spiky||r.scattered||r.wires||r.weak||r.refused||r.volumeChanges))throw Error('Sweep incomplete or defective');
const rows=after.map((r:any,i:number)=>{const old=before[i];if(r.theme!==old.theme||r.side!==old.side||JSON.stringify(r.skipped)!==JSON.stringify(old.skipped))throw Error('Mismatched sweep inputs');return {...r,before:{kept:old.kept,refused:old.refused,spiky:old.spiky,disconnected:old.scattered,weak:old.weak}};});
writeFileSync(`${b}/sweep-summary.json`,JSON.stringify(rows,null,2)+'\n');
let table='| Theme | Size | Kept | Uses with separate lobes | Pillars | Stray fragments | One-tile lines | Weak keeps | Refused | Volume losses | Tiny fans expanded |\n| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n';
for(const r of rows)table+=`| ${r.theme} | ${r.side}² | ${r.kept} | ${r.lobed} | ${r.spiky} | ${r.scattered} | ${r.wires} | ${r.weak} | ${r.refused} | ${r.volumeChanges} | ${r.expandedSmallFans} |\n`;
const sums=(side:number)=>rows.filter((r:any)=>r.side===side).reduce((s:any,r:any)=>({uses:s.uses+r.uses,kept:s.kept+r.kept,lobed:s.lobed+r.lobed,expanded:s.expanded+r.expandedSmallFans}),{uses:0,kept:0,lobed:0,expanded:0});
const small=sums(64),large=sums(128);
const oldSamples=JSON.parse(readFileSync(`${b}/local/before/samples.json`,'utf8'));
const newSamples=JSON.parse(readFileSync(`${b}/local/lobes/samples.json`,'utf8'));
const lookup=new Map(newSamples.map((s:any)=>[`${s.theme}/${s.seed}/${s.k}`,s]));
const cases=oldSamples.filter((s:any)=>s.k<3&&lookup.has(`${s.theme}/${s.seed}/${s.k}`)).slice(0,20);
if(cases.length!==20)throw Error('Missing sheet cases');
const sheet=cases.map((old:any,i:number)=>{const next:any=lookup.get(`${old.theme}/${old.seed}/${old.k}`);if(next.reason||JSON.stringify(old.input)!==JSON.stringify(next.input)||JSON.stringify(old.path)!==JSON.stringify(next.path)||old.power!==next.power)throw Error('Sheet gestures changed');return {case:i+1,theme:old.theme,power:old.power,before:sediment(old.input,old.heights,128),after:sediment(next.input,next.heights,128)};});
if(sheet.some(r=>r.after.pillars||r.after.strays||r.after.wires||r.before.volume!==r.after.volume||r.after.bodyXSpan<r.before.bodyXSpan||r.after.bodyYSpan<r.before.bodyYSpan))throw Error('Sheet body, volume or body extent failed');
writeFileSync(`${b}/sheet-summary.json`,JSON.stringify(sheet,null,2)+'\n');
let sheetTable='| Case | Theme | Power | Before blocks | After blocks | Before full span | Before body span | After body span | Lobe sizes after |\n| --- | --- | ---: | ---: | ---: | --- | --- | --- | --- |\n';
for(const r of sheet)sheetTable+=`| ${String(r.case).padStart(2,'0')} | ${r.theme} | ${r.power} | ${r.before.volume} | ${r.after.volume} | ${r.before.xSpan} × ${r.before.ySpan} | ${r.before.bodyXSpan} × ${r.before.bodyYSpan} | ${r.after.bodyXSpan} × ${r.after.bodyYSpan} | ${r.after.components.join(', ')} |\n`;
const summary=[
 'All inter-lobe connector paths are removed; separate lobes remain bodies of sediment, with no wires.',
 'Every deposited tile belongs to filled 2 × 2 ground: no stray tile, skinny fragment or lone pillar.',
 'Round 2’s original cone, reach, normal volume, curving distributaries and short-gesture/Power 0 behavior stay intact.',
 `64²: all seven themes, all ${small.uses} uses kept; zero pillars, stray fragments, one-tile lines or volume losses.`,
 `128²: all seven themes, all ${large.uses} uses kept; zero pillars, stray fragments, one-tile lines or volume losses.`,
 `${small.uses+large.uses-small.expanded-large.expanded} original budgets match exactly; the ${small.expanded+large.expanded} tiny effects still use nine conserved blocks for visible small fans (D356).`,
 '44 other-force pins unchanged; all 50 fixtures match native/Wasm; five Deposit pins re-pinned; 13 contracts and typechecks pass.',
 'Same 20 gestures refreshed and inspected: case 09’s rectangle and the other wires are gone; volumes and body extents retained.'
];
writeFileSync(`${b}/REPORT.md`,summary.join('\n')+'\n\n'+`[20-pair contact sheet](docs/sheets/deposit-pillars.png) · [adoption patch](adoption.patch) · [integration](INTEGRATION.md) · [evidence](EVIDENCE.md) · [shaping and reproduction](DETAILS.md)\n`);
writeFileSync(`${b}/EVIDENCE.md`,table+`\nSeparate lobes are now accepted per Kyler’s round 3 direction. A stray fragment means a disconnected receiving component with fewer than four tiles. A thin receiving tile lies outside every filled 2 × 2 patch; none is allowed, whether it is an isolated fragment, an attached tail or a connector. All deposited tiles pass this body check and neighbour support. The ${small.lobed+large.lobed} uses with valid separate lobes are recorded above, not classified as scattered failures.\n\nThe original worker evaluates every identical request alongside the revised worker. All ${small.uses+large.uses} revised uses keep; ${small.uses+large.uses-small.expanded-large.expanded} preserve exact original deposited volume. The three round 2 tiny effects retain their nine-block visibility correction, paid by permitted upstream/shoulder cuts. No length refusal returns. [sweep-summary.json](sweep-summary.json) records every cell and skipped generator seed. Its historical baseline disconnected counts used the former all-components definition; they are explicitly named separately from current stray-fragment failures. Raw heights and per-use results stay gitignored in local/ (D195).\n\n`+sheetTable+`\nAll 20 sheet cases preserve original volume and retain or extend their original **body** spans, including seven Power 0 gestures. The full original spans included stray tiles and thin extremities; those are removed, not joined by wires. Body span measures tiles that already belonged to a filled 2 × 2 patch. [sheet-summary.json](sheet-summary.json) records area, both spans, pillars, thin tiles and every lobe size. Cases 02, 03, 08, 09, 12 and 20 retain substantial separate bodies with no artificial connector.\n\n[verification.json](verification.json): 44 unchanged other-force pins, five Deposit re-pins, all 50 native/Wasm matches, 96 short-line fans and all six Deposit fixture geometry/budget matches. Both typechecks and all 13 contracts pass. The adoption patch applies cleanly at the pinned base and reproduces the tested overlays.\n\nAll assets are procedural project output. No product file or other checkout changed; no speed measurements or Timberborn probes ran. The sheet stays under investigation/deposit-pillars/; adoption copies it to docs/sheets/deposit-pillars.png. See [DETAILS.md](DETAILS.md) for shaping, acceptance definitions and reproduction.\n`);
console.log({small,large,sheetCases:sheet.length});
