// Regenerate reviewable copies; never writes production files.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
const read = p => readFileSync(p, 'utf8').replaceAll('\r\n', '\n');
const base = read('../../src/core/sim/water.ts');
function replace(s, old, next) {
  if (!s.includes(old)) throw new Error('Source drift: ' + old.slice(0, 100));
  return s.replace(old, next);
}
function saturation(s) {
  const start = s.indexOf('      let c = 1;');
  const end = s.indexOf('      wn[i] = c;', start);
  return s.slice(0, start) + `      let c = 1;
      // Integer counts only; retain the boundary path for narrow/edge grids.
      if (x > 0 && x < W - 1 && y > 0 && y < H - 1) {
        c += +(D[i - W - 1] > 0) + +(D[i - W] > 0) + +(D[i - W + 1] > 0)
          + +(D[i - 1] > 0) + +(D[i + 1] > 0)
          + +(D[i + W - 1] > 0) + +(D[i + W] > 0) + +(D[i + W + 1] > 0);
      } else {
` + s.slice(start + '      let c = 1;\n'.length, end) + '      }\n' + s.slice(end);
}
function topology(s) {
  s = replace(s, '  private readonly wall: Uint8Array;', `  private readonly wall: Uint8Array;
  /** Immutable geometry only, in the original direction order. */
  private readonly neighbours: Int32Array;`);
  s = replace(s, '    this.N = N;', `    this.N = N;
    this.neighbours = new Int32Array(4 * N);
    for (let i = 0; i < N; i++) {
      const x = i % W, y = (i - x) / W, b = 4 * i;
      this.neighbours[b] = y > 0 ? i - W : -1;
      this.neighbours[b + 1] = x > 0 ? i - 1 : -1;
      this.neighbours[b + 2] = y < H - 1 ? i + W : -1;
      this.neighbours[b + 3] = x < W - 1 ? i + 1 : -1;
    }`);
  s = replace(s, 'const { W, H, F, D, C, out, f, wall, mod, dam } = this;', 'const { W, H, F, D, C, out, f, wall, mod, dam, neighbours } = this;');
  s = replace(s, `        let n = -1;
        if (k === 0) n = y > 0 ? c - W : -1;
        else if (k === 1) n = x > 0 ? c - 1 : -1;
        else if (k === 2) n = y < H - 1 ? c + W : -1;
        else n = x < W - 1 ? c + 1 : -1;`, '        const n = neighbours[b + k];');
  s = replace(s, `      const n0 = y > 0 ? c - W : -1;
      const n1 = x > 0 ? c - 1 : -1;
      const n2 = y < H - 1 ? c + W : -1;
      const n3 = x < W - 1 ? c + 1 : -1;`, `      const n0 = neighbours[b];
      const n1 = neighbours[b + 1];
      const n2 = neighbours[b + 2];
      const n3 = neighbours[b + 3];`);
  // Only remove now-unused coordinate calculations inside substep.
  const a = s.indexOf('  private substep('), z = s.indexOf('  private updateSeeps(');
  s = s.slice(0, a) + s.slice(a, z).replaceAll('      const x = c % W;\n      const y = (c - x) / W;\n', '') + s.slice(z);
  return s;
}
function clear(s) {
  return replace(s, '      const b = 4 * this.prevWet[k];', `      // Wet tiles overwrite all four flows before any flow is read.
      if (D[this.prevWet[k]] > 0) continue;
      const b = 4 * this.prevWet[k];`);
}
function unroll(s) {
  const anchor=s.indexOf('    // 1. outflows');
  const start=s.indexOf('      for (let k = 0; k < 4; k++) {',anchor);
  const end=s.indexOf('      // a tile never gives more than it has',start);
  if(start<0||end<0)throw Error('Source drift in flow loop');
  const body=s.slice(start+'      for (let k = 0; k < 4; k++) {\n'.length,end-'      }\n'.length);
  // do/while(false) preserves the original continue as a local break.
  // Four independent blocks keep precisely the original k=0,1,2,3 order.
  return s.slice(0,start)+[0,1,2,3].map(k=>'      do {\n        const k = '+k+' as number;\n'+body.replace('          continue;','          break;')+'      } while (false);\n').join('')+s.slice(end);
}
const transforms = { saturation, topology, clear, unroll };
for (const [name, fn] of Object.entries({...transforms, combined: s => unroll(clear(topology(saturation(s))))})) {
  mkdirSync(`prototypes/${name}`, {recursive: true});
  writeFileSync(`prototypes/${name}/water.ts`, '// Investigation copy of dev src/core/sim/water.ts; generated by prototype.mjs.\n' + fn(base));
}
let drought = read('../../src/core/sim/drought.ts');
drought = drought.replaceAll('"./moisture"', '"../../../src/core/sim/moisture"')
  .replaceAll('"./prefill"', '"../../../src/core/sim/prefill"')
  .replaceAll('"./water"', '"../../../src/core/sim/water"');
const needle = `  for (let i = 0; i < N; i++) {
    if (label[i] < 0) continue;
    const drop = (evap[label[i]] / area[label[i]]) * days;`;
drought = replace(drought, needle, `  // Identical division then multiplication once per pool, after the ordered sum.
  const drops = new Float64Array(area.length);
  for (let p = 0; p < area.length; p++) drops[p] = (evap[p] / area[p]) * days;
  for (let i = 0; i < N; i++) {
    if (label[i] < 0) continue;
    const drop = drops[label[i]];`);
mkdirSync('prototypes', {recursive: true});
writeFileSync('prototypes/drought.ts', '// Investigation copy; generated by prototype.mjs.\n' + drought);
