const state={active:false,frames:[],calls:[],tasks:[],renders:[],events:[],errors:[]};
for(const name of ['pointerdown','pointerup','keydown'])window.addEventListener(name,e=>{if(state.active)state.events.push({name,at:performance.now(),key:e.key,target:e.target.tagName});},true);
new PerformanceObserver(list=>{if(state.active)state.tasks.push(...list.getEntries().map(x=>({at:x.startTime,ms:x.duration})));}).observe({type:'longtask'});
window.addEventListener('error',e=>state.errors.push(e.message));
window.addEventListener('unhandledrejection',e=>state.errors.push(String(e.reason)));
let last=null;
function frame(t){if(state.active&&last!==null)state.frames.push(t-last);last=state.active?t:null;requestAnimationFrame(frame);}requestAnimationFrame(frame);
function wrap(r,name){const original=r[name];if(typeof original!=='function')return;r[name]=function(...args){const start=performance.now();let value;try{return value=original.apply(this,args);}finally{if(state.active)state.calls.push({name,at:start,ms:performance.now()-start,keptGeometry:name==="meshGeometry"?args[0]?.geometry===value:undefined});if(name==='renderNow'&&state.active){state.renders.push({at:performance.now(),calls:r.gl.info.render.calls,triangles:r.gl.info.render.triangles,geometries:r.gl.info.memory.geometries,textures:r.gl.info.memory.textures,heap:performance.memory?.usedJSHeapSize});}}};}
const hooked=new WeakSet();
window.scaling={start(){const r=window.dgm3d?.renderer;if(r&&!hooked.has(r)){hooked.add(r);for(const n of ['setMap','updateTerrain','updateTerrainRect','updateEntities','updateWater','updateWaterSoon','meshTerrain','meshWater','bakeTiles','bakeShadows','setHeat','meshGeometry','dropMesh','renderNow'])wrap(r,n);}for(const k of ['frames','calls','tasks','renders','events'])state[k]=[];last=null;state.active=true;return performance.now();},stop(){state.active=false;return JSON.parse(JSON.stringify(state));},geometry(){const r=window.dgm3d.renderer;let bytes=0;const seen=new Set();r.scene.traverse(x=>{if(x.geometry&&!seen.has(x.geometry)){seen.add(x.geometry);for(const a of Object.values(x.geometry.attributes))bytes+=a.array?.byteLength??a.data?.array?.byteLength??0;bytes+=x.geometry.index?.array.byteLength??0;}});const gl=r.gl.getContext(),debug=gl.getExtension('WEBGL_debug_renderer_info');return {bytes,geometries:r.gl.info.memory.geometries,textures:r.gl.info.memory.textures,gpu:debug?gl.getParameter(debug.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),maxTexture:gl.getParameter(gl.MAX_TEXTURE_SIZE),maxRenderbuffer:gl.getParameter(gl.MAX_RENDERBUFFER_SIZE),build:r.lastBuild};}};
