[package]
name = "forces"
description = "The forces of nature: portable typed Rust computation and playback records"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "forces-batch"
path = "src/main.rs"

[dependencies]
portable = { path = "../portable" }
water = { path = "../water", default-features = false }
