import assert from 'node:assert/strict';
import {signaturePlan,drama,auditSignatureOrigins,prefillReach} from './signature-water';
import {prefill}from'../../src/core/sim/prefill';
import {waterModel}from'../../src/core/sim/model';
import {tileName} from './reference-water';
import {convert} from './convert';
import {measure,projectWet} from './measure-water.mjs';
const W=96,N=W*W,h=new Uint8Array(N).fill(4),raw=new Float32Array(N).fill(10);
for(let seed=1;seed<=30;seed++){
 let state=seed;const rand=()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state;};
 const heights=Uint8Array.from({length:24*24},()=>rand()%8),model=waterModel(24,24,heights,[]);
 model.emitters=Array.from({length:6},(_,k)=>({cells:[rand()%heights.length],strength:k===0?0:(rand()%100+1)/30,contamination:0}));
 const reachable=prefillReach(model),water=prefill(model);for(let i=0;i<heights.length;i++)assert.equal(reachable[i]>0,water.depth[i]>0,'prefill reachability must equal the exact prefill wet set, including off-source footprints');
}
const ref=(fraction:Float32Array)=>({fraction,valid:new Uint8Array(N).fill(1),coverage:1,waterCells:fraction.reduce((a,b)=>a+b,0),errors:[]});
const lake=new Float32Array(N);for(let y=30;y<66;y++)for(let x=30;x<66;x++)lake[y*W+x]=1;
const plan=signaturePlan(raw,h,W,ref(lake));
assert.equal(plan.features[0].kind,'lake');assert.equal(plan.sources.length,1);assert.equal(plan.sources[0].kind,'basin spring');
assert.equal(plan.landEdits,0);assert.equal(plan.bedCells,36*36);
for(let i=0;i<N;i++)if(!lake[i])assert.equal(plan.heights[i],h[i]);
const result=convert(plan.heights,W,16,plan,'signature-lake-regression');
assert.ok(result.start&&result.start.waterDistance<=20,'start must reach the connected signature lake');
assert.ok(drama(plan,result.water.depth,ref(lake),W).signaturePresent);
assert.ok(auditSignatureOrigins(plan.heights,W,plan.sources).passed,'one spring may fill its own new lake');
const booster={...plan.sources[0],i:40*W+40,headId:'downstream-booster'};
const audit=auditSignatureOrigins(plan.heights,W,[...plan.sources,booster]);
assert.equal(audit.passed,false,'a second head inside an already supplied lake must be rejected');
assert.ok(audit.checks.some(c=>c.depthFromOthers>.05));
assert.ok(result.heights.every((v,i)=>v===plan.heights[i]),'conversion must not alter land or add a rim');
const river=new Float32Array(N),slopeRaw=Float32Array.from({length:N},(_,i)=>Math.floor(i/W));
for(let y=0;y<W;y++)for(let x=45;x<=50;x++)river[y*W+x]=1;
const riverPlan=signaturePlan(slopeRaw,h,W,ref(river));
assert.equal(riverPlan.features[0].kind,'river');assert.ok(riverPlan.sources.length);
assert.ok(riverPlan.sources.every(s=>Math.floor(s.i/W)===W-1),'all river sources at the upstream edge, never downstream');
const sea=new Float32Array(N),seaRaw=new Float32Array(N).fill(25);for(let i=0;i<N;i++)if(i%W<48){sea[i]=1;seaRaw[i]=0;}
const coast=signaturePlan(seaRaw,h,W,ref(sea));assert.equal(coast.features[0].kind,'sea opening');
assert.ok(coast.sources.every(s=>s.i<W||s.i>=N-W||s.i%W===0||s.i%W===W-1));assert.equal(coast.landEdits,0);
const bathymetry=seaRaw.slice();for(let i=0;i<N;i++)if(sea[i])bathymetry[i]=-100+i%W;
assert.equal(signaturePlan(bathymetry,h,W,ref(sea)).features[0].kind,'sea opening','negative bathymetry is an open sea, not a river');
assert.equal(tileName(42.94,-122.11),'ESA_WorldCover_10m_2021_v200_N42W123_Map.tif');
assert.equal(tileName(-16.82,179.99),'ESA_WorldCover_10m_2021_v200_S18E177_Map.tif');
const wet=Uint8Array.from(lake),good=measure(lake,wet,W),dry=measure(lake,new Uint8Array(N),W);
assert.equal(good.retained,1);assert.equal(good.signaturePresent,true);assert.equal(dry.retained,0);assert.equal(dry.signaturePresent,false);
assert.equal(measure(lake,wet,W,0).retained,null,'missing reference must not masquerade as no water');
const frame={lat:42,lon:-122,size:W,mpt:60};
assert.deepEqual(projectWet(lake,frame,frame),wet);
const clipped=projectWet(new Float32Array(N).fill(1),{...frame,mpt:30},frame);
assert.ok(clipped.reduce((s,x)=>s+x,0)<N*.3,'smaller framing cannot claim full fixed-extent preservation');
console.log('Signature source, land preservation, connected-shore start, missing-reference and fixed-extent metric regressions passed.');
