"""Apply exact dev-based integration edits inside local/workspace, then emit the adoption patch."""
import pathlib
from emit_patch import emit
STUDY=pathlib.Path(__file__).resolve().parent
ROOT=STUDY.parents[1]
WORK=STUDY/"local/workspace"
BASE="ac5a8b224483f87ab7917565d036d6c9c695d986"
changed=set()
def edit(name,old,new):
 p=WORK/name;s=p.read_text(encoding="utf-8"); assert s.count(old)==1,(name,old[:100],s.count(old));p.write_text(s.replace(old,new),encoding="utf-8");changed.add(name)
edit("rust/forces/src/lib.rs", "mod json;", "mod json;\nmod rift;")
edit("rust/forces/src/lib.rs", "enum Records {", "enum Records {\n    Rift(Box<rift::RiftRecords>),")
edit("rust/forces/src/lib.rs", "let mut out = match &self.records {", "let mut out = match &self.records {\n            Records::Rift(r) => r.value(),")
edit("rust/forces/src/lib.rs", '"glaciate" => 5.0,', '"glaciate" => 5.0,\n        "rift" => 6.0,')
edit("rust/forces/src/lib.rs", "command[33] = map.w as f64;", 'command[33] = map.w as f64;\n    if opcode == 6.0 { command[5] = ["auto", "sheer", "stepped"].iter().position(|&x| x == settings.walls).map_or(-1.0, |i| i as f64); }')
edit("rust/forces/src/lib.rs", "if opcode >= 4.0 {", "if opcode == 4.0 || opcode == 5.0 {")
edit("rust/forces/src/lib.rs", "const FORCE_ERRORS: [&str; 27]", "const FORCE_ERRORS: [&str; 30]")
edit("rust/forces/src/lib.rs", '    "No room to rise here",\n];', '    "No room to rise here",\n    "Invalid Rift settings",\n    "Draw the Rift on the map",\n    "the Floor leaves no ground to drop here",\n];')
edit("rust/forces/src/lib.rs", "        _ => 11,\n    }\n}\npub fn plan", """        6 => {
            if !power || !seed || !(c[2].is_nan() || bounded(c[2],4.0,64.0)) || !(c[4].is_nan() || whole(c[4],1.0,m.ceiling)) || !whole(c[5],0.0,2.0) {return 27;}
            if !whole(c[19],1.0,512.0) || points*2>path.len() || !path[..points*2].chunks_exact(2).all(|p|bounded(p[0],0.0,m.w as f64-1.0)&&bounded(p[1],0.0,m.h as f64-1.0)) {return 28;}
            0
        }
        _ => 11,
    }
}
pub fn plan""")
edit("rust/forces/src/lib.rs", "    let mut p = match c[0] as u32 {", "    let mut p = match c[0] as u32 {\n        6 => rift::plan(&before, m, &settings, &intent, &task.keep, c[5] as u32),")
edit("rust/forces/src/lib.rs", "    match &p.records {\n        Records::Glaciate(r) => {", "    match &p.records {\n        Records::Rift(r) => r.geometry(g),\n        Records::Glaciate(r) => {")
edit("rust/forces/src/lib.rs", "        match &p.records {\n            Records::Glaciate(r) => {", "        match &p.records {\n            Records::Rift(r) => {pair(d,10,&r.arrival);pair(d,12,&r.stats);},\n            Records::Glaciate(r) => {")
edit("src/core/forces/rust/bridge.ts", '  "No room to rise here",\n];', '  "No room to rise here",\n  "Invalid Rift settings",\n  "Draw the Rift on the map",\n  "the Floor leaves no ground to drop here",\n];')
edit("src/core/forces/rust/bridge.ts", 'export type RustVerb = "craterize" | "erupt" | "quake" | "carve" | "glaciate";', 'export type RustVerb = "craterize" | "erupt" | "quake" | "carve" | "glaciate" | "rift";')
edit("src/core/forces/rust/bridge.ts", 'export type RustPlan =\n', 'export interface RiftRecords { raw: RustMap; fault: FaultShape; arrival: Float32Array; stats: { changed: number; drop: number; held: number; stepped: number; sheer: number; width: number }; }\n\nexport type RustPlan =\n  | ({ verb: "rift" } & RiftRecords)\n')
edit("src/core/forces/rust/bridge.ts", '    case "quake": {\n      const fault', '    case "rift":\n    case "quake": {\n      const fault')
edit("src/core/forces/rust/bridge.ts", '      plan = {\n        verb: "quake",', '      if (job.verb === "rift") {\n        plan = { verb: "rift", raw, fault, arrival: view(10, Float32Array).slice(), stats: named(view(12, Float64Array), ["changed", "drop", "held", "stepped", "sheer", "width"]) as RiftRecords["stats"] };\n        break;\n      }\n      plan = {\n        verb: "quake",')
edit("src/core/forces/op.ts", 'export type Verb = "carve" | "craterize" | "erupt" | "quake" | "glaciate";', 'export type Verb = "carve" | "craterize" | "erupt" | "quake" | "glaciate" | "rift";')
edit("src/core/forces/op.ts", 'export const VERBS: readonly Verb[] = ["carve", "craterize", "erupt", "quake", "glaciate"];', 'export const VERBS: readonly Verb[] = ["carve", "craterize", "erupt", "quake", "glaciate", "rift"];')
edit("src/core/forces/op.ts", 'export type ForceSettingsRecord =\n', 'export type ForceSettingsRecord =\n  | { mode: "drop"; power: number; size: number | null; walls: "auto" | "sheer" | "stepped"; seed: number; floor: number }\n')
# The existing union's history label may inspect mode; narrow structurally rather than require a fake mode on Rift.
edit("src/core/forces/op.ts", 'p.settings.mode === "fissure"', '(p.settings as { mode?: string }).mode === "fissure"')
edit("src/core/forces/op.ts", 'p.settings.mode === "slide"', '(p.settings as { mode?: string }).mode === "slide"')
edit("src/core/forces/op.ts", '      return "Glaciate";', '      return "Glaciate";\n    case "rift":\n      return "Rift";')
edit("src/core/forces/op.ts", '  if (p.verb === "quake") {', '  if (p.verb === "rift" && !w.path?.length) return ["a rift needs its fault"];\n  if (p.verb === "quake") {')
edit("src/core/doc/ops.schema.json", '"verb": { "enum": ["carve", "craterize", "erupt", "quake", "glaciate"] }', '"verb": { "enum": ["carve", "craterize", "erupt", "quake", "glaciate", "rift"] }')
edit("src/core/forces/settings.ts", '  glaciate: {', '  rift: { name: "a rift", choices: { mode: ["drop"], walls: ["auto", "sheer", "stepped"] }, flags: [], ranges: [{ key: "size", min: 4, max: 64, empty: "null", why: "a rift\'s size is 4 to 64 tiles, or null (it follows Power)" }] },\n  glaciate: {')
edit("src/core/forces/runs.ts", 'readonly verb: "craterize" | "erupt" | "quake" | "glaciate";', 'readonly verb: "craterize" | "erupt" | "quake" | "glaciate" | "rift";')
edit("src/core/forces/start.ts", 'import type { CraterSettings }', 'import { RiftRun, type RiftSettings } from "./rift";\nimport type { CraterSettings }')
edit("src/core/forces/start.ts", 'export type ForceRequest = (\n', 'export type ForceRequest = (\n  | { verb: "rift"; settings: RiftSettings; path: Point[]; cut: number | null }\n')
edit("src/core/forces/start.ts", 'export type AnyForceSettings = CarveSettings', 'export type AnyForceSettings = RiftSettings | CarveSettings')
edit("src/core/forces/start.ts", 'const points = req.verb === "quake" ? []', 'const points = req.verb === "quake" || req.verb === "rift" ? []')
edit("src/core/forces/start.ts", '      case "quake": {', '      case "rift": {\n        map = stagedForceMap(base);\n        const run = new RiftRun(map, req.settings, { path: req.path }, keep);\n        run.finalize = buildTouches(state, base.heights);\n        staged = run;\n        break;\n      }\n      case "quake": {')
edit("src/core/forces/keep.ts", 'import type { CarveRun }', 'import type { RiftRun } from "./rift";\nimport type { CarveRun }')
edit("src/core/forces/keep.ts", '    case "quake": {', '    case "rift": {\n      const r = run as RiftRun;\n      return { settings: { ...r.settings }, where: { path: pathRecord(r.intent.path) } };\n    }\n    case "quake": {')
edit("src/core/forces/nature.ts", '    case "carve":\n      return AUTO_CARVE_DETAILS;', '    case "rift":\n      return { walls: null };\n    case "carve":\n      return AUTO_CARVE_DETAILS;')
edit("src/core/forces/nature.ts", '    case "carve":\n      return { ...req, settings: carveNature', '    case "rift":\n      return { ...req, settings: { ...req.settings, walls: req.settings.walls ?? "auto" } };\n    case "carve":\n      return { ...req, settings: carveNature')
edit("src/core/forces/runs.ts", "  quake?: { path: Point[]; slide: boolean; side: 1 | -1 };", "  quake?: { path: Point[]; slide: boolean; side: 1 | -1 };\n  rift?: { path: Point[]; width: number };")
edit("src/core/forces/op.ts", "w.path.length >= 2", "w.path.length >= (p.verb === \"rift\" ? 1 : 2)")
edit("src/core/forces/op.ts", '  } else if (!w.origin) return ["a force needs the point it started from"];', '  } else if (p.verb !== "rift" && !w.origin) return ["a force needs the point it started from"];')
edit("src/core/doc/ops.schema.json", '"unleash", "aim", "strike", "vent", "fissure", "lift", "slide", "flow"', '"unleash", "aim", "strike", "vent", "fissure", "lift", "slide", "flow", "drop"')
edit("src/core/doc/ops.schema.json", '"walls": { "enum": ["steep", "wide", "terraced"] }', '"walls": { "enum": ["steep", "wide", "terraced", "auto", "sheer", "stepped"] }')
# Type-only cue plumbing: no renderer effect, control or interface implementation.
edit("src/render3d/forces.ts", 'verb: "carve" | "craterize" | "erupt" | "quake" | "glaciate";', 'verb: "carve" | "craterize" | "erupt" | "quake" | "glaciate" | "rift";')
edit("tests/contract/forceSettings.test.ts", 'import { QUAKE_DEFAULTS', 'import { RIFT_DEFAULTS, validateRift } from "../../src/core/forces/rift";\nimport { QUAKE_DEFAULTS')
edit("tests/contract/forceSettings.test.ts", '  glaciate: { ...GLACIATE_DEFAULTS },', '  glaciate: { ...GLACIATE_DEFAULTS },\n  rift: { ...RIFT_DEFAULTS },')
edit("tests/contract/forceSettings.test.ts", '    case "carve":', '    case "rift":\n      return thrown(() => validateRift(s as never));\n    case "carve":')
edit("tests/unit/forcePlayback.test.ts", 'type Verb = ForceMoment["verb"];', 'type Verb = Exclude<ForceMoment["verb"], "rift">; // New Rift effects belong to the page session.')
edit("src/core/doc/ops.schema.json", '"path": { "type": "array", "minItems": 2, "maxItems": 512', '"path": { "type": "array", "minItems": 1, "maxItems": 512')
edit("tools/determinism/cases.ts", 'import { keptForceParams }', 'import { RiftRun, RIFT_DEFAULTS } from "../../src/core/forces/rift";\nimport { keptForceParams }')
edit("tools/determinism/cases.ts", 'const verbs = ["carve", "craterize", "erupt", "quake", "glaciate"];', 'const verbs = ["carve", "craterize", "erupt", "quake", "glaciate", "rift"];')
edit("tools/determinism/cases.ts", '  } else if (verb === "quake") {', '  } else if (verb === "rift") {\n    settings = { ...RIFT_DEFAULTS, power, size, seed };\n    intent = { path: mode ? path : [{ x, y }] };\n    run = new RiftRun(m, settings, intent);\n  } else if (verb === "quake") {')
edit("tools/determinism/cases.ts", 'verb === "quake"\n      ? { verb, settings, path, side: intent.side, cut: null }', '(verb === "quake" || verb === "rift")\n      ? { verb, settings, path: intent.path, ...(verb === "quake" ? {side: intent.side} : {}), cut: null }')
edit("tools/determinism/cases.ts", '    for (const verb of verbs)\n', '    for (const verb of verbs.filter(v => v !== "rift"))\n')
edit("tools/determinism/cases.ts", '  return out;\n}\n\n/** One case', '  for (const power of [0, 100]) for (const mode of [0, 1]) out.push({ id: `force/64/rift/${power}/${mode}`, kind: "force", n: 64, verb: "rift", power, size: 22, mode });\n  return out;\n}\n\n/** One case')
# Strengthen the existing fixture checker: exact bytes, rather than the 53-bit convenience hash.
edit("tools/rust/check.ts", '  return hash53(out);\n});\nconst forcesBin', '  return Buffer.from(out);\n});\nconst forcesBin')
edit("tools/rust/check.ts", 'const got = hash53(new Uint8Array(out.buffer, out.byteOffset + at + 4, len));', 'const got = out.subarray(at + 4, at + 4 + len);')
edit("tools/rust/check.ts", 'if (got !== nodeForces[k])', 'if (!got.equals(nodeForces[k]))')
# Only the force page's hash is replaced. Water retains its existing check.
p=WORK/"tools/rust/check.ts"; text=p.read_text(encoding="utf-8"); a=text.index('const FORCES_IN_PAGE ='); b=text.index('const forcesPayload',a); section=text[a:b]; start=section.index('    let h1 ='); end=section.index('    x.water_dealloc(res',start); section=section[:start]+"    let str = ''; for (const v of b) str += String.fromCharCode(v); out.push(btoa(str));\n"+section[end:]; text=text[:a]+section+text[b:]; text=text.replace('as number[];\n      forceHashes.forEach','as string[];\n      forceHashes.forEach').replace('if (h !== nodeForces[k])','if (!Buffer.from(h, "base64").equals(nodeForces[k]))'); p.write_text(text,encoding="utf-8");changed.add("tools/rust/check.ts")
edit("rust/forces/src/lib.rs", "    keep: Vec<u8>,\n    output: Option<Plan>,", "    keep: Vec<u8>,\n    area_depth: Vec<u8>,\n    output: Option<Plan>,")
edit("rust/forces/src/lib.rs", "    let settings = Settings::from(&job[\"settings\"]);", "    let area_depth = if job[\"areaDepth\"].is_array() { arr(&job[\"areaDepth\"]).iter().map(|v| num(v) as u8).collect() } else { vec![255; map.w * map.h] };\n    let settings = Settings::from(&job[\"settings\"]);")
edit("rust/forces/src/lib.rs", "        keep,\n        output: None,", "        keep,\n        area_depth,\n        output: None,")
edit("rust/forces/src/lib.rs", "    pair(d, 5, &task.keep);", "    pair(d, 5, &task.keep);\n    pair(d, 67, &task.area_depth);")
edit("rust/forces/src/lib.rs", "rift::plan(&before, m, &settings, &intent, &task.keep, c[5] as u32)", "rift::plan(&before, m, &settings, &intent, &task.keep, &task.area_depth, c[5] as u32)")
edit("src/core/forces/rust/bridge.ts", "  keep: Uint8Array | null;", "  keep: Uint8Array | null;\n  areaDepth?: Uint8Array | null;")
edit("src/core/forces/rust/bridge.ts", "    if (job.keep) view(5, Uint8Array).set(job.keep);", "    if (job.keep) view(5, Uint8Array).set(job.keep);\n    if (job.areaDepth) view(67, Uint8Array).set(job.areaDepth);")
edit("src/core/forces/start.ts", "new RiftRun(map, req.settings, { path: req.path }, keep)", "new RiftRun(map, req.settings, { path: req.path }, keep, inside)")
edit("src/core/forces/keep.ts", "  if (request.area) {", "  if (request.area && request.verb !== \"rift\") { // Rift feathers its terrain before playback in Rust.")
edit("src/core/forces/rust/bridge.ts", "keep: job.keep ?? new Uint8Array(N) }, false);", "keep: job.keep ?? new Uint8Array(N), ...(job.areaDepth ? { areaDepth: job.areaDepth } : {}) }, false);")
# Extend CI's existing Rust fixture list, without changing any old fixture/pin.
edit("tools/rust/forces-jobs.ts", 'const VERBS: RustVerb[] = ["craterize", "erupt", "quake", "carve", "glaciate"];', 'const VERBS: RustVerb[] = ["craterize", "erupt", "quake", "carve", "glaciate", "rift"];')
edit("tools/rust/forces-jobs.ts", '    case "carve":\n', '    case "rift":\n      return { verb, map, keep, settings: { mode: "drop", power, size: k % 2 ? 64 : null, walls: ["auto", "sheer", "stepped"][k % 3], floor: 1, seed: k }, intent: { path: k % 2 ? path : [path[0]] } };\n    case "carve":\n')
# Rift odd variants retain sub-tile paths; the underlying map/object/water variation is shared.
edit("tools/rust/forces-jobs.ts", '  if (verb === "quake") {', '  if (verb === "rift") {\n    j.settings = { mode: "drop", power, seed, size: pick([null, 4, 64]), walls: pick(["auto", "sheer", "stepped"]), floor: 1 };\n    j.intent = { path: Array.from({ length: 2 + Math.floor(u() * 6) }, () => ({ x: u() * (n - 1), y: u() * (n - 1) })) };\n  }\n  if (verb === "quake") {')
# Deposit: opcode 7, same one-call typed arena, no changes to the five adopted operations.
edit("rust/forces/src/lib.rs", "mod rift;", "mod rift;\nmod deposit;")
edit("rust/forces/src/lib.rs", "    Rift(Box<rift::RiftRecords>),", "    Rift(Box<rift::RiftRecords>),\n    Deposit(Box<deposit::DepositRecords>),")
edit("rust/forces/src/lib.rs", "            Records::Rift(r) => r.value(),", "            Records::Rift(r) => r.value(),\n            Records::Deposit(r) => r.value(),")
edit("rust/forces/src/lib.rs", '\"rift\" => 6.0,', '\"rift\" => 6.0,\n        \"deposit\" => 7.0,')
edit("rust/forces/src/lib.rs", "command[33] = map.w as f64;", 'command[33] = map.w as f64;\n    if opcode == 7.0 { command[5] = ["auto", "few", "many"].iter().position(|&x| x == job["settings"]["channels"].as_str().unwrap_or("")).map_or(-1.0, |i| i as f64); }')
edit("rust/forces/src/lib.rs", "const FORCE_ERRORS: [&str; 30]", "const FORCE_ERRORS: [&str; 35]")
edit("rust/forces/src/lib.rs", '    "the Floor leaves no ground to drop here",\n];', '    "the Floor leaves no ground to drop here",\n    "Invalid Deposit settings",\n    "Draw Deposit on the map",\n    "the working area leaves nothing to take sediment from",\n    "the Floor leaves nothing to take sediment from",\n    "the map leaves no room for sediment here",\n];')
edit("rust/forces/src/lib.rs", "        6 => {\n            if !power", "        6 | 7 => {\n            let settings_error=if opcode==6{27}else{30}; let path_error=if opcode==6{28}else{31};\n            if !power")
edit("rust/forces/src/lib.rs", "{return 27;}\n            if !whole(c[19]", "{return settings_error;}\n            if !whole(c[19]")
edit("rust/forces/src/lib.rs", "{return 28;}\n            0", "{return path_error;}\n            0")
edit("rust/forces/src/lib.rs", "    let mut p = match c[0] as u32 {", "    let mut p = match c[0] as u32 {\n        7 => deposit::plan(&before,m,&settings,&intent,&task.keep,&task.area_depth,c[5] as u32),")
edit("rust/forces/src/lib.rs", "        Records::Rift(r) => r.geometry(g),", "        Records::Rift(r) => r.geometry(g),\n        Records::Deposit(r) => r.geometry(g),")
edit("rust/forces/src/lib.rs", "            Records::Rift(r) => {pair(d,10,&r.arrival);pair(d,12,&r.stats);},", "            Records::Rift(r) => {pair(d,10,&r.arrival);pair(d,12,&r.stats);},\n            Records::Deposit(r) => {pair(d,10,&r.arrival);pair(d,11,&r.channel);pair(d,12,&r.stats);pair(d,25,&r.stages);},")
edit("src/core/forces/rust/bridge.ts", '  "the Floor leaves no ground to drop here",\n];', '  "the Floor leaves no ground to drop here",\n  "Invalid Deposit settings",\n  "Draw Deposit on the map",\n  "the working area leaves nothing to take sediment from",\n  "the Floor leaves nothing to take sediment from",\n  "the map leaves no room for sediment here",\n];')
edit("src/core/forces/rust/bridge.ts", 'export type RustVerb = "craterize" | "erupt" | "quake" | "carve" | "glaciate" | "rift";', 'export type RustVerb = "craterize" | "erupt" | "quake" | "carve" | "glaciate" | "rift" | "deposit";')
edit("src/core/forces/rust/bridge.ts", 'export type RustPlan =\n', 'export interface DepositRecords { raw: RustMap; arrival: Float32Array; channel: Uint8Array; channelStages: Uint8Array[]; mouth: Point; direction: Point; reach: number; width: number; placement: "fan" | "slope" | "sheet" | "delta" | "hollow"; branches: Point[][]; stats: { changed: number; eroded: number; deposited: number; balance: number; maximumCut: number; maximumDeposit: number; channels: number; wet: number; buried: number; carried: number; donorRadius: number }; }\n\nexport type RustPlan =\n  | ({ verb: "deposit" } & DepositRecords)\n')
edit("src/core/forces/rust/bridge.ts", '  switch (job.verb) {\n    case "craterize":', '  switch (job.verb) {\n    case "deposit": {\n      const mouth=point(), direction=point(), reach=n(), width=n(), placement=(["fan","slope","sheet","delta","hollow"] as const)[n()], count=n();\n      const branches=counted(count,()=>counted(n(),point));\n      const stages=view(25,Uint8Array).slice(); const N=raw.W*raw.H;\n      plan={verb:"deposit",raw,mouth,direction,reach,width,placement,branches,arrival:view(10,Float32Array).slice(),channel:view(11,Uint8Array).slice(),channelStages:[0,1,2].map(k=>stages.slice(k*N,(k+1)*N)),stats:named(view(12,Float64Array),["changed","eroded","deposited","balance","maximumCut","maximumDeposit","channels","wet","buried","carried","donorRadius"]) as DepositRecords["stats"]};\n      break;\n    }\n    case "craterize":')
edit("src/core/forces/op.ts", 'export type Verb = "carve" | "craterize" | "erupt" | "quake" | "glaciate" | "rift";', 'export type Verb = "carve" | "craterize" | "erupt" | "quake" | "glaciate" | "rift" | "deposit";')
edit("src/core/forces/op.ts", 'export const VERBS: readonly Verb[] = ["carve", "craterize", "erupt", "quake", "glaciate", "rift"];', 'export const VERBS: readonly Verb[] = ["carve", "craterize", "erupt", "quake", "glaciate", "rift", "deposit"];')
edit("src/core/forces/op.ts", 'export type ForceSettingsRecord =\n', 'export type ForceSettingsRecord =\n  | { mode: "fan"; power: number; size: number | null; channels: "auto" | "few" | "many"; seed: number; floor: number }\n')
edit("src/core/forces/op.ts", 'p.verb === "rift" ? 1 : 2', '(p.verb === "rift" || p.verb === "deposit") ? 1 : 2')
edit("src/core/forces/op.ts", 'p.verb !== "rift" && !w.origin', 'p.verb !== "rift" && p.verb !== "deposit" && !w.origin')
edit("src/core/forces/op.ts", '  if (p.verb === "rift" && !w.path?.length)', '  if (p.verb === "deposit" && !w.path?.length) return ["a deposit needs its origin"];\n  if (p.verb === "rift" && !w.path?.length)')
edit("src/core/forces/op.ts", '      return "Rift";', '      return "Rift";\n    case "deposit":\n      return "Deposit";')
edit("src/core/doc/ops.schema.json", '"verb": { "enum": ["carve", "craterize", "erupt", "quake", "glaciate", "rift"] }', '"verb": { "enum": ["carve", "craterize", "erupt", "quake", "glaciate", "rift", "deposit"] }')
edit("src/core/doc/ops.schema.json", '"flow", "drop"]', '"flow", "drop", "fan"]')
edit("src/core/doc/ops.schema.json", '"meltwater": { "type": "boolean" },', '"meltwater": { "type": "boolean" },\n            "channels": { "enum": ["auto", "few", "many"] },')
edit("src/core/forces/settings.ts", '  glaciate: {', '  deposit: { name: "a deposit", choices: { mode: ["fan"], channels: ["auto", "few", "many"] }, flags: [], ranges: [{ key: "size", min: 4, max: 64, empty: "null", why: "a deposit\'s size is 4 to 64 tiles, or null (it follows Power)" }] },\n  glaciate: {')
edit("src/core/forces/runs.ts", 'readonly verb: "craterize" | "erupt" | "quake" | "glaciate" | "rift";', 'readonly verb: "craterize" | "erupt" | "quake" | "glaciate" | "rift" | "deposit";')
edit("src/core/forces/runs.ts", '  rift?: { path: Point[]; width: number };', '  rift?: { path: Point[]; width: number };\n  deposit?: { mouth: Point; direction: Point; reach: number; branches: Point[][] };')
edit("src/core/forces/start.ts", 'import { RiftRun, type RiftSettings }', 'import { DepositRun, type DepositSettings } from "./deposit";\nimport { RiftRun, type RiftSettings }')
edit("src/core/forces/start.ts", 'export type ForceRequest = (\n', 'export type ForceRequest = (\n  | { verb: "deposit"; settings: DepositSettings; path: Point[]; cut: number | null }\n')
edit("src/core/forces/start.ts", 'export type AnyForceSettings = RiftSettings', 'export type AnyForceSettings = DepositSettings | RiftSettings')
edit("src/core/forces/start.ts", 'req.verb === "quake" || req.verb === "rift" ? []', 'req.verb === "quake" || req.verb === "rift" || req.verb === "deposit" ? []')
edit("src/core/forces/start.ts", '      case "rift": {', '      case "deposit": {\n        map = stagedForceMap(base);\n        // Rust budgets material after Keep/Floor/area feathering; never weather or feather its result independently.\n        staged = new DepositRun(map, req.settings, { path: req.path }, keep, inside);\n        break;\n      }\n      case "rift": {')
edit("src/core/forces/keep.ts", 'import type { RiftRun }', 'import type { DepositRun } from "./deposit";\nimport type { RiftRun }')
edit("src/core/forces/keep.ts", '    case "rift": {', '    case "deposit": {\n      const r = run as DepositRun;\n      return { settings: { ...r.settings }, where: { path: pathRecord(r.intent.path) } };\n    }\n    case "rift": {')
edit("src/core/forces/keep.ts", 'request.area && request.verb !== "rift"', 'request.area && request.verb !== "rift" && request.verb !== "deposit"')
edit("src/core/forces/nature.ts", '    case "rift":\n      return { walls: null };', '    case "rift":\n      return { walls: null };\n    case "deposit":\n      return { channels: null };')
edit("src/core/forces/nature.ts", '    case "rift":\n      return { ...req, settings: { ...req.settings, walls: req.settings.walls ?? "auto" } };', '    case "rift":\n      return { ...req, settings: { ...req.settings, walls: req.settings.walls ?? "auto" } };\n    case "deposit":\n      return { ...req, settings: { ...req.settings, channels: req.settings.channels ?? "auto" } };')
edit("src/render3d/forces.ts", 'verb: "carve" | "craterize" | "erupt" | "quake" | "glaciate" | "rift";', 'verb: "carve" | "craterize" | "erupt" | "quake" | "glaciate" | "rift" | "deposit";')
edit("tests/unit/forcePlayback.test.ts", 'Exclude<ForceMoment["verb"], "rift">', 'Exclude<ForceMoment["verb"], "rift" | "deposit">')
edit("tests/contract/forceSettings.test.ts", 'import { RIFT_DEFAULTS', 'import { DEPOSIT_DEFAULTS, validateDeposit } from "../../src/core/forces/deposit";\nimport { RIFT_DEFAULTS')
edit("tests/contract/forceSettings.test.ts", '  rift: { ...RIFT_DEFAULTS },', '  rift: { ...RIFT_DEFAULTS },\n  deposit: { ...DEPOSIT_DEFAULTS },')
edit("tests/contract/forceSettings.test.ts", '    case "rift":', '    case "deposit":\n      return thrown(() => validateDeposit(s as never));\n    case "rift":')
edit("tools/rust/forces-jobs.ts", 'const VERBS: RustVerb[] = ["craterize", "erupt", "quake", "carve", "glaciate", "rift"];', 'const VERBS: RustVerb[] = ["craterize", "erupt", "quake", "carve", "glaciate", "rift", "deposit"];')
edit("tools/rust/forces-jobs.ts", '    case "rift":', '    case "deposit":\n      return { verb, map, keep, settings: { mode: "fan", power, size: k % 2 ? 64 : null, channels: ["auto", "few", "many"][k % 3], floor: 1, seed: k }, intent: { path: k % 2 ? path : [path[0]] } };\n    case "rift":')
edit("tools/rust/forces-jobs.ts", '  if (verb === "rift") {', '  if (verb === "deposit") {\n    j.settings = { mode: "fan", power, seed, size: pick([null, 4, 64]), channels: pick(["auto", "few", "many"]), floor: 1 };\n    j.intent = { path: Array.from({ length: 2 + Math.floor(u() * 6) }, () => ({ x: u() * (n - 1), y: u() * (n - 1) })) };\n  }\n  if (verb === "rift") {')
edit("tools/determinism/cases.ts", 'import { RiftRun, RIFT_DEFAULTS }', 'import { DepositRun, DEPOSIT_DEFAULTS } from "../../src/core/forces/deposit";\nimport { RiftRun, RIFT_DEFAULTS }')
edit("tools/determinism/cases.ts", 'const verbs = ["carve", "craterize", "erupt", "quake", "glaciate", "rift"];', 'const verbs = ["carve", "craterize", "erupt", "quake", "glaciate", "rift", "deposit"];')
edit("tools/determinism/cases.ts", '  } else if (verb === "rift") {', '  } else if (verb === "deposit") {\n    settings = { ...DEPOSIT_DEFAULTS, power, size, seed };\n    intent = { path: mode ? path : [{ x, y }] };\n    run = new DepositRun(m, settings, intent);\n  } else if (verb === "rift") {')
edit("tools/determinism/cases.ts", '(verb === "quake" || verb === "rift")', '(verb === "quake" || verb === "rift" || verb === "deposit")')
edit("tools/determinism/cases.ts", 'verbs.filter(v => v !== "rift")', 'verbs.filter(v => v !== "rift" && v !== "deposit")')
edit("tools/determinism/cases.ts", '  for (const power of [0, 100]) for (const mode of [0, 1]) out.push({ id: `force/64/rift/${power}/${mode}`, kind: "force", n: 64, verb: "rift", power, size: 22, mode });', '  for (const verb of ["rift", "deposit"]) for (const power of [0, 100]) for (const mode of [0, 1]) out.push({ id: `force/64/${verb}/${power}/${mode}`, kind: "force", n: 64, verb, power, size: 22, mode });')
# Identity-only runs collect no performance samples.
for verb in ["rift","deposit"]:
 # Keep the existing five fixtures byte-for-byte; exercise the new forces' small Size and Floor caps.
 s=(WORK/"tools/rust/forces-jobs.ts").read_text(encoding="utf-8")
 start=s.index(f'    case "{verb}":');end=s.index('    case "',start+1)
 piece=s[start:end];replacement=piece.replace('size: k % 2 ? 64 : null','size: k === 2 ? 4 : k % 2 ? 64 : null').replace('floor: 1, seed: k','floor: k === 3 ? 8 : k === 2 ? 3 : 1, seed: k')
 edit("tools/rust/forces-jobs.ts",piece,replacement)
edit("tools/rust/forces-jobs.ts", '  return j;\n}', '  if ((verb === "rift" || verb === "deposit") && k === 1) j.areaDepth = new Uint8Array(n*n).fill(2);\n  return j;\n}')
edit("tools/determinism/cases.ts", '  let intent: any;\n', '  let intent: any;\n  const areaDepth = (verb === "rift" || verb === "deposit") && mode ? new Uint8Array(n*n).fill(2) : null;\n')
edit("tools/determinism/cases.ts", 'run = new RiftRun(m, settings, intent);', 'run = new RiftRun(m, settings, intent, null, areaDepth);')
edit("tools/determinism/cases.ts", 'run = new DepositRun(m, settings, intent);', 'run = new DepositRun(m, settings, intent, null, areaDepth);')
edit("tools/determinism/cases.ts", '  run.planAll();\n  // (its record as the editor', '  run.planAll();\n  const frames: { stage: number; map: FullForceMap }[] = [];\n  if (verb === "rift" || verb === "deposit") {\n    while (!run.done) { run.step(); if ([1, Math.floor(run.total/2), run.total].includes(run.shown)) frames.push({ stage: run.shown, map: snapshotMap(run.map) }); }\n  }\n  // (its record as the editor')
edit("tools/determinism/cases.ts", '  return { map: run.final(), record: kept.ok ? kept.params : null };', '  return { map: run.final(), record: kept.ok ? kept.params : null, frames };')
edit("tools/determinism/cases.ts", '          m = f.map;\n          record = f.record;', '          m = f.map;\n          record = f.record;\n          if ("frames" in f && f.frames) for (const frame of f.frames) await add(`${c.id}/${k}/playback/${frame.stage}`, frame.map, record);')
edit("rust/forces/Cargo.toml", 'description = "The forces of nature (Carve, Craterize, Erupt, Quake, Glaciate), the same bytes as the TypeScript they replaced"', 'description = "The forces of nature: portable typed Rust computation and playback records"')
edit("rust/forces/src/lib.rs", '        via: if c[0] >= 4.0 {', '        via: if c[0] == 4.0 || c[0] == 5.0 {')
edit("rust/forces/src/lib.rs", '    command[33] = map.w as f64;', '    command[33] = map.w as f64;\n    if opcode == 6.0 || opcode == 7.0 { command[9] = if settings.mode == if opcode == 6.0 { "drop" } else { "fan" } {0.0} else {-1.0}; }')
edit("rust/forces/src/lib.rs", 'if !power || !seed || !(c[2].is_nan()', 'if c[9] != 0.0 || !power || !seed || !(c[2].is_nan()')
edit("tools/rust/forces-jobs.ts", 'import { createHash } from "node:crypto";', 'import { createHash } from "node:crypto";\nimport { decode } from "../../src/core/forces/rust/protocol";')
edit("tools/rust/forces-jobs.ts", '  for (const f of forceFixtures()) pins[f.name] = sha256(executeInRust(f.job));', '  for (const f of forceFixtures()) {\n    const output = executeInRust(f.job);\n    if (/^(rift|deposit) /.test(f.name) && (decode(output) as { error?: string }).error) throw Error(`Unexpected refusal: ${f.name}`);\n    pins[f.name] = sha256(output);\n  }')
edit("tools/determinism/run.ts", 'const serial = process.argv.includes("--serial");', 'const serial = process.argv.includes("--serial");\nconst noTimings = process.argv.includes("--no-timings");')
edit("tools/determinism/run.ts", 'const t0 = performance.now();', 'const t0 = noTimings ? 0 : performance.now();')
edit("tools/determinism/run.ts", 'const tc = performance.now();', 'const tc = noTimings ? 0 : performance.now();')
edit("tools/determinism/run.ts", '    slowest.push({ case: c.id, seconds:', '    if (!noTimings) slowest.push({ case: c.id, seconds:')
edit("tools/determinism/run.ts", 'const seconds = Math.round((performance.now() - t0) / 1000);', 'const seconds = noTimings ? null : Math.round((performance.now() - t0) / 1000);')
edit("tools/determinism/run.ts", '${errors.length} errors, ${seconds} s`', '${errors.length} errors${noTimings ? "" : `, ${seconds} s`}`')
# New files from the study overlay are part of the patch; the build regenerates embedded Wasm at adoption.
changed.update(str(p.relative_to(WORK)).replace("\\","/") for p in (STUDY/"overlay").rglob("*") if p.is_file() for p in [WORK/p.relative_to(STUDY/"overlay")])
(STUDY/"local/changed.json").write_text(__import__("json").dumps(sorted(changed)),encoding="utf-8")
emit(STUDY,BASE,changed)
print("Patched",len(changed),"local build files; product working tree untouched")
