// Independent small scenes cover the native sealed-basin path and fractional/edge cases.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
import {LOCAL,api,deps,json,hash} from './common.mjs';
const a=api(),p=deps(resolve(LOCAL,'protocol.cjs')),rows=[];
function save(id,m,initial,opts,commands){const sim=new a.WaterSim(structuredClone(m),initial,opts),parts=[];for(const cmd of commands){const r=cmd.settle?a.settle(sim,cmd.settle):(sim.run(cmd.ticks,cmd.scale??1),null);parts.push(p.snapshot(sim,r));}
 const input=p.encodeJob(m,initial,opts,commands),expected=p.packSnapshots(parts);writeFileSync(resolve(LOCAL,'checks',id+'.in'),input);writeFileSync(resolve(LOCAL,'checks',id+'.expected'),expected);const row={id,W:m.W,H:m.H,commands:commands.length,captures:parts.length,input:hash(input),expected:hash(expected),ticks:sim.ticks};writeFileSync(resolve(LOCAL,'checks',id+'.json'),JSON.stringify(row));rows.push(row);}
let seed=0xabc123;const rand=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32);
for(let k=0;k<100;k++){const W=1+Math.floor(rand()*24),H=1+Math.floor(rand()*24),N=W*H,m={W,H,floor:Float64Array.from({length:N},()=>Math.floor(rand()*6)/2),dam:k%2?null:Float64Array.from({length:N},()=>rand()<.2?.65:-1),emitters:[{cells:[Math.floor(rand()*N)],strength:k%7===0?1e-14:rand()*8,contamination:rand()},{cells:[0,N-1],strength:.7,contamination:.3,depthLimit:{anchor:0,off:1.2,on:.8}}]},initial={depth:Float64Array.from({length:N},()=>rand()<.4?-0:rand()*2),contamination:Float64Array.from({length:N},()=>rand()<.5?-0:rand())};save('extra-random-'+k,m,initial,{rules:k%2?'port':'game',edgeSpill:k%3===0},Array.from({length:100},(_,t)=>({ticks:1,scale:t<40?1:t<80?0:.35})));}
for(const rules of ['game','port'])for(const[W,H]of[[1,1],[1,9],[9,1],[2,2],[3,7],[13,11],[24,20]]){const N=W*H,m={W,H,floor:Float64Array.from({length:N},(_,i)=>(i*13+7)%5),dam:Float64Array.from({length:N},(_,i)=>i%7===0?.65:-1),emitters:[{cells:[0],strength:2,contamination:0,depthLimit:{anchor:0,off:.8,on:.72}},{cells:[N-1],strength:1,contamination:1},{cells:[W-1,N-W],strength:.5,contamination:.5}]},initial={depth:Float64Array.from({length:N},(_,i)=>i%3===0?0:.01+(i%9)/3),contamination:Float64Array.from({length:N},(_,i)=>(i%4)/3)};save(`extra-grid-${rules}-${W}x${H}`,m,initial,{rules},Array.from({length:256},(_,t)=>({ticks:1,scale:t<64?1:t<128?0:t<192?.35:1})));}
for(const mode of ['canonical','preview','feed','edge']){const W=20,H=20,N=W*H,floor=new Float64Array(N).fill(5),depth=new Float64Array(N),c=new Float64Array(N),tiles=[];for(let y=5;y<15;y++)for(let x=5;x<15;x++){const i=y*W+x;floor[i]=0;depth[i]=1;c[i]=.35;tiles.push(i);}if(mode==='edge')for(let x=0;x<5;x++){floor[10*W+x]=0;depth[10*W+x]=1;}
 const m={W,H,floor,dam:null,emitters:mode==='feed'?[{cells:[tiles[0]],strength:2,contamination:0}]:[]};save('extra-sealed-'+mode,m,{depth,contamination:c},{},[{settle:{sealed:tiles,untilSteady:mode==='preview'}}]);
 const snap=readFileSync(resolve(LOCAL,'checks','extra-sealed-'+mode+'.expected')),dv=new DataView(snap.buffer,snap.byteOffset);if(mode==='preview')assert.equal(dv.getUint32(8+8,true),128,'first sealed steady check');if(mode==='canonical')assert.equal(dv.getUint32(8+8,true),128,'canonical records same first steady tick');}
writeFileSync(resolve(LOCAL,'extra-manifest.tsv'),rows.map(r=>`${resolve(LOCAL,'checks',r.id+'.in')}\t${resolve(LOCAL,'checks',r.id+'.native')}`).join('\n'));
execFileSync(process.env.DGM_NATIVE??resolve(LOCAL,'target/release/water-batch'+(process.platform==='win32'?'.exe':'')),['--batch',resolve(LOCAL,'extra-manifest.tsv'),'4']);for(const r of rows)assert.equal(hash(readFileSync(resolve(LOCAL,'checks',r.id+'.native'))),r.expected,r.id);
json('extra.json',{status:'pass',cases:rows.length,captures:rows.reduce((s,r)=>s+r.captures,0)});
const cases=readdirSync(resolve(LOCAL,'checks')).filter(n=>n.endsWith('.json')).sort().map(n=>JSON.parse(readFileSync(resolve(LOCAL,'checks',n))));json('checks.json',{cases});console.log('Extra native scenarios PASS',rows.length);
