// Refresh the leading report only after the complete acceptance gate passes.
import {readFileSync,writeFileSync,readdirSync} from 'node:fs';
import assert from 'node:assert/strict';
const read=p=>JSON.parse(readFileSync(p,'utf8'));
const s=read('results/weather/summary.json'),p=read('results/weather/product-summary.json');
assert.equal(s.status,'complete');assert.equal(p.buildId,s.buildId);
const seconds=n=>(n/1000).toFixed(2),ratio=n=>n.toFixed(2)+'×';
const b128=s.bySize[128],b256=s.bySize[256],c128=p.byRuntime.chromium[128],c256=p.byRuntime.chromium[256];
let md='# Exact weather-cycle speed investigation\n\n';
md+='**Complete: 204 maps in Node and Chromium, six implementations, all 18 full-duration profiles, and 12 additional continuous-timeline cases per runtime. No mismatches.** The follow-up optimizes current dev\'s own `GameWater` and `GameSoil`; it does not substitute the earlier approximate cycle model. Production and reference modules remain unchanged.\n\n';
md+='The full four-change combination gives median paired exact-weather speedups of **'+ratio(b128.ratios.combined.nodeCpu)+' / '+ratio(b256.ratios.combined.nodeCpu)+' in Node CPU** and **'+ratio(b128.ratios.combined.chromiumWall)+' / '+ratio(b256.ratios.combined.chromiumWall)+' in Chromium elapsed time** at 128² / 256². Separate Chromium medians for the full native probe set fall from **'+seconds(b128.chromiumBaselineWallMs)+' → '+seconds(b128.chromiumCombinedWallMs)+' s** and **'+seconds(b256.chromiumBaselineWallMs)+' → '+seconds(b256.chromiumCombinedWallMs)+' s**. The reference normally totals 73 days across six independently loaded probes; longer source ramps keep their extra days.\n\n';
md+='| Prototype | 128² Node CPU / Chromium elapsed speedup | 256² Node CPU / Chromium elapsed speedup |\n|---|---:|---:|\n';
for(const v of s.variants.slice(1)){const a=b128.ratios[v],b=b256.ratios[v];md+='| '+v+' | '+ratio(a.nodeCpu)+' / '+ratio(a.chromiumWall)+' | '+ratio(b.nodeCpu)+' / '+ratio(b.chromiumWall)+' |\n';}
md+='\nStart integration with soil descriptor reuse, then evaluate the strict scalar WASM water kernel and conservative contamination support. Treat saturation caching as optional: its standalone result varies with changing wet boundaries, and it adds memory. Only the complete four-change combination has been measured together; do not assign its speedup to a smaller subset or multiply individual ratios. [INTEGRATION.md](INTEGRATION.md) specifies the changes in order and includes an unapplied combined patch. [WEATHER-PROOF.md](WEATHER-PROOF.md) gives the dependency and arithmetic arguments.\n\n';
md+='The first-drought wait depends on which Weather view is built. The additional continuous experiment starts at the reference new game\'s 04:00 and reaches 73 calendar-day boundaries (55,936 ticks); the reset probes retain their own full-day starts.\n\n| Chromium observed compute wait | 128² combined | 256² combined |\n|---|---:|---:|\n';
for(const [label,get] of [
  ['Independent Normal probe prioritized: drought end',c=>c.probes.combined.endMs],
  ['Independent Normal probe: all three recovery days ready',c=>c.probes.combined.keysMs],
  ['Complete independent probe set',c=>c.probes.combined.totalMs],
  ['Continuous new game: first drought end (boundary 19)',c=>c.continuous.combined.endMs],
  ['Continuous new game: recovery complete (boundary 22)',c=>c.continuous.combined.keysMs],
  ['Continuous new game: full 73-day timeline',c=>c.continuous.combined.totalMs]
])md+='| '+label+' | '+seconds(get(c128))+' s | '+seconds(get(c256))+' s |\n';
const continuousCases=readdirSync('results/weather/product/chromium').filter(f=>f.endsWith('.json')).map(f=>read('results/weather/product/chromium/'+f));
md+='\nTheme variation is substantial. Across the six seed-1 continuous cases at each size, the combined Chromium wait ranges are ';
for(const size of [128,256]){
  const rows=continuousCases.filter(r=>r.size===size&&r.buildId===s.buildId);assert.equal(rows.length,6);
  const end=rows.map(r=>r.timings.combined.progress.find(t=>t.row.phase==='drought'&&t.row.cycle===1&&t.row.phaseDay===2).wallMs);
  const full=rows.map(r=>r.timings.combined.wallMs),range=a=>seconds(Math.min(...a))+'–'+seconds(Math.max(...a))+' s';
  md+=(size===128?'128²: ':'; 256²: ')+range(end)+' to first drought end and '+range(full)+' to completion';
}
md+='. The per-theme table in WEATHER-PRODUCT.md retains these slower cases.\n';
md+='\nThese are observed worker compute times on a shared Ryzen 7 9800X3D host, not target-device UI guarantees. Four proof workers per runtime overlap; the one-worker continuous runs also overlap the proof. Constructors and required Measures calls are included; generation, proof copies/hashing, module startup, transfer and rendering are excluded. Absolute values are separate medians; speedups are medians of paired ratios. [WEATHER-RESULTS.md](WEATHER-RESULTS.md) retains every theme/size, all standalone results and diagnostic profiles.\n\n';
md+='The product proposals **do not change simulated results**: stream completed key days, prioritize independent probes, keep a lossless timeline cache under a complete content/configuration/version hash, and start a cancellable worker after the selected map is generated. A continuous journey still executes every earlier tick and daily measurement. A useful B-second background head start reduces remaining wait to approximately max(0, T − B); a resident cache hit replaces compute with measured copy/parse plus transfer/paint. Eight-millisecond tick batches keep cancellation responsive, with separately estimated scheduling overhead. [WEATHER-PRODUCT.md](WEATHER-PRODUCT.md) supplies baseline/combined waits, cache memory/copy costs, measured message scheduling and the limits of those estimates.\n\n';
md+='Proof uses all six themes, seeds 1–30 at 128², seeds 1–3 at 256² and seed 1 at 96². Each runtime independently generates **1,224 exports**, compares every byte against baseline, and matches the historical SHA oracle. Per implementation, **'+s.checkpointsPerVariant.toLocaleString('en-US')+' daily/phase checkpoints across '+s.simulatedDaysPerVariant.toLocaleString('en-US')+' simulated days** compare water depth/contamination, soil moisture/contamination, every plant/timer/death, sources, clock, summaries and hidden state feeding later ticks. Node and Chromium reference digests agree. Tick-order/RNG code is unchanged. Additional every-tick smoke, narrow-grid/dependency and continuous-journey checks pass. No tolerance or expected-hash update accepts a mismatch.\n\n';
md+='The source audit pins dev `'+s.reference+'`, verifies all 82 input hashes and seven bundle hashes, and checks that the retained WAT assembles to the tested binary. The compiler disables fast math explicitly; scalar float64 water expressions and all float32 soil roundings retain their order. The tested build is `'+s.buildId+'`. [WEATHER-REPRODUCTION.md](WEATHER-REPRODUCTION.md) gives commands and workload definitions. This is evidence for the supported immutable heightfield model, not arbitrary private-state mutation or unimplemented roofed water.\n\n';
md+='For stacked layers, descriptor reuse and strict WASM arithmetic remain useful techniques; contamination support must expand along the actual compartment graph. The literal four-edge water kernel and eight/four-neighbour saturation stencil cannot be reused unchanged. Cache/background/streaming work largely carries over with complete layered-geometry keys and larger memory budgets. [STACKED-LAYERS.md](STACKED-LAYERS.md) assesses the now-available terrain3d prototype and the conditions for each proposal.\n\n';
md+='## Scope and source revisions\n\nPR #17 was merged externally during this follow-up, at 2026-09-25 19:38:03 UTC. Following the requested fallback, this work moved to branch `investigation/simspeed-cycles`, created from dev `652774175c08b46b40c01536ee3d08a83cbe98d6`, and this folder alone. No merge was performed by this investigation. The exact-weather and core dependency source trees are unchanged between the initially pinned dev and that new base; the rebuilt bundles retain the identical fingerprint, so completed proof records remain valid. The branch/source record is in `results/weather/branch-provenance.json`.\n\n';
const upstream=read('results/weather/upstream-check.json');assert(upstream.passed&&upstream.changedDependencyPaths.length===0);
md+='The final remote check at '+upstream.checkedAt+' found dev `'+upstream.observedDev+'`; its exact-weather tree and every tested core dependency still match the pinned reference. Two newly added core places modules are outside that dependency graph. Unrelated upstream changes do not alter this experiment. The terrain3d assessment remains pinned to `'+upstream.terrain3d+'`.\n\n';
md+='The [earlier core/M9 study](../simspeed/REPORT.md) remains separate and unchanged. The present weather prototypes do not optimize generation or the core editor simulator. They target the independent exact-weather implementations and propose integration without applying it. No source, test, root dependency, CI or configuration file is changed. The new PR is to remain open and unmerged.\n';
writeFileSync('REPORT.md',md);
console.log('Updated REPORT.md from complete weather evidence');
