// The first-visit maps (docs/UI-BRIEF.md §7, PLAN §20 D330): a handful of ready-made 128² maps,
// generated by the current generator and checked like any release, one picked at random and loaded
// instantly, with no generation. `tools/first-visit-maps.ts` makes them at each generator release
// into public/first-visit/: an index and each map's project file (the map as the editor opens it:
// its settings, seed, land, water and objects; gzip JSON).

import type { ThemeId } from "../../core/spec/mapspec";

export const FIRST_VISIT_FORMAT = 1;
/** Their folder under the site's base, and in the repository under public/. */
export const FIRST_VISIT_DIR = "first-visit";
export const FIRST_VISIT_SIZE = 128;

export interface FirstVisitMap {
  id: string;
  /** The project file, relative to the index. */
  file: string;
  name: string;
  theme: ThemeId;
  seed: number;
  /** The map's share fragment (its spec). */
  fragment: string;
  /** The project file's size, and the sha256 of the .timber the map exports as generated. */
  bytes: number;
  sha256: string;
}

export interface FirstVisitIndex {
  format: 1;
  /** The generator that made them: a page on another version generates live instead. */
  generatorVersion: string;
  size: number;
  maps: FirstVisitMap[];
}

/** One map at random, or null when there is none for this generator (the page generates live). */
export function pickFirstVisit(index: FirstVisitIndex | null, generatorVersion: string, random: () => number = Math.random): FirstVisitMap | null {
  if (!index || index.format !== FIRST_VISIT_FORMAT || index.generatorVersion !== generatorVersion || !index.maps.length) return null;
  return index.maps[Math.min(index.maps.length - 1, Math.floor(random() * index.maps.length))];
}
