import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const dir=fileURLToPath(new URL('.',import.meta.url)),local=resolve(dir,'../local/round3');
const preview=process.argv.includes('--preview');
const read=p=>JSON.parse(readFileSync(p,'utf8')),median=a=>{const s=[...a].sort((x,y)=>x-y),n=s.length;return n?s[Math.floor(n/2)]/2+s[Math.floor((n-1)/2)]/2:null;};
const round=n=>n===null?null:Math.round(n*1000)/1000;
const loads=['load.jsonl','browser/load.jsonl'].filter(f=>existsSync(resolve(local,f))).flatMap(f=>readFileSync(resolve(local,f),'utf8').trim().split('\n').filter(Boolean).map(x=>{const r=JSON.parse(x);return {at:Date.parse(r.at),cpu:r.cpuPercent,available:r.availableBytes};})).sort((a,b)=>a.at-b.at);
assert(loads.length,'machine load samples required');
function loadFor(row){let lo=0,hi=loads.length;while(lo<hi){const m=(lo+hi)>>1;if(loads[m].at<row.at)lo=m+1;else hi=m;}const sample=[];for(let i=lo;i<loads.length&&loads[i].at<=row.at+(row.loadMs??row.ms);i++)sample.push(loads[i]);
 let nearest=false;if(!sample.length){const candidates=[loads[lo],loads[lo-1]].filter(Boolean).sort((a,b)=>Math.abs(a.at-row.at)-Math.abs(b.at-row.at));assert(Math.abs(candidates[0].at-row.at)<15000,'missing contemporaneous load '+row.at);sample.push(candidates[0]);nearest=true;}
 return {samples:sample.length,nearest,cpuMedian:round(median(sample.map(x=>x.cpu))),cpuWorst:Math.max(...sample.map(x=>x.cpu)),minimumAvailableMiB:round(Math.min(...sample.map(x=>x.available))/1024**2)};
}
const csv=['scope,size,engine,action,repeat,target,ms,cpu_median,cpu_worst,minimum_available_MiB,load_samples,nearest_sample'];
function metrics(rows,scope,size,engine='node'){
 const grouped={};for(const row of rows.filter(r=>Number.isFinite(r.ms))){const load=loadFor(row),key=row.name+(row.target!==undefined&&row.name!=='worst-varied-depth'?'@'+row.target:'');(grouped[key]??=[]).push({...row,load});csv.push([scope,size,engine,row.name,row.repeat??'',row.target??'',round(row.ms),load.cpuMedian,load.cpuWorst,load.minimumAvailableMiB,load.samples,load.nearest].join(','));}
 return Object.fromEntries(Object.entries(grouped).map(([name,r])=>[name,{repeats:r.length,medianMs:round(median(r.map(x=>x.ms))),worstMs:round(Math.max(...r.map(x=>x.ms))),cpuMedian:round(median(r.map(x=>x.load.cpuMedian))),cpuWorst:Math.max(...r.map(x=>x.load.cpuWorst)),minimumAvailableMiB:Math.min(...r.map(x=>x.load.minimumAvailableMiB))}]));
}
function ready(rows){const repeats=[...new Set(rows.filter(r=>r.name==='open').map(r=>r.repeat))];return repeats.map(repeat=>{const a=rows.find(r=>r.name==='open'&&r.repeat===repeat),b=rows.find(r=>r.name==='first-edit'&&r.repeat===repeat);return {name:'open-plus-first-edit',repeat,at:a.at,ms:a.ms+b.ms,loadMs:b.at+b.ms-a.at};});}
function deepWorst(rows){return [1,2,3].map(repeat=>{const candidates=rows.filter(r=>r.name==='seek'&&r.repeat===repeat);const worst=candidates.reduce((a,b)=>a.ms>b.ms?a:b);return {...worst,name:'worst-varied-depth'};});}
const old=read(resolve(dir,'../round2/measurements.json'));
const summary={base:old.base,determinism:old.determinism,round2:'40e5d6ca85e9ca973ed603707e4a21d0ab458980',scope:'2048 accepted mixed edits at both sizes. End actions repeated three times; timings include whole-machine CPU and available RAM. Construction is a single capacity trace. Node GC memory includes fixture/oracle and journal bookkeeping, not page/GPU RAM. Historical replay checks use every cold-seek prefix, amortized once per checkpoint interval.',revision:'Full-session construction/proofs use the original numeric layout. Final reader/actions and six three-engine modern contracts additionally verify UTF16 code units, distinct equal component instances, full finalizer hash v2, saved-past sequence restart, recent redo bookkeeping and canonical-water boundary markers. These changes preserve successful numeric results.',policy:{checkpointEvery:32,checkpointCount:128,checkpointBytes:128*1024**2,recentBytes:128*1024**2,recentSteps:16,resultBytes:32*1024**2,fieldBytes:32*1024**2,overflow:'Double spacing; keep zero/current/aligned. Journal and current force-program dependencies are outside the historical checkpoint cap. Cold disposable disk/indexes need owned cleanup/compaction; infinite total-file or heap bound is not claimed.'},cases:[],policyPilot:[],browsers:[],finalContracts:[]};
for(const size of [256,512]){
 const full=read(resolve(local,`runs/${size}-32.json`)),actions=read(resolve(local,`runs/${size}-final-actions.json`));assert(full.passed&&actions.passed&&actions.savedFileRoundTrips);assert.equal(full.steps,2048);assert.equal(full.trace.length,2049);
 const previous=old.cases.filter(c=>c.size===size),oracle=read(resolve(dir,`../local/round2/accepted/after-${size}-1-128.json`));assert.deepEqual(full.baseTrace.slice(1),oracle.trace);assert.equal(full.exportHash,oracle.final.exportHash);
 const memory=full.rows.filter(r=>r.name==='memory'&&typeof r.step==='number').map(r=>({step:r.step,heapMiB:round(r.memory.heapUsed/1024**2),arrayBufferMiB:round(r.memory.arrayBuffers/1024**2),rssMiB:round(r.memory.rss/1024**2),checkpoints:r.checkpoints,coldDiskBytes:r.disk}));
 for(const row of memory){assert(row.checkpoints.count<=128&&row.checkpoints.bytes<=128*1024**2);assert(row.checkpoints.recentCount<=16&&row.checkpoints.recentBytes<=128*1024**2);}
 summary.cases.push({size,steps:full.steps,forces:full.forces,finalState:full.finalState,exportHash:full.exportHash,traceDigest:createHash('sha256').update(full.trace.join('\n')).digest('hex'),previous:previous.map(c=>({phase:c.phase,projectBytes:c.projectBytes,timing:c.timing})),projectBytes:actions.rows.find(r=>r.name==='save').bytes,constructionProjectBytes:full.bytes,checkpoints:full.checkpoints,memory,finalControllerMemory:actions.rows.filter(r=>r.name.startsWith('memory-')).map(r=>({stage:r.name,repeat:r.repeat,heapMiB:round(r.memory.heapUsed/1024**2),arrayBufferMiB:round(r.memory.arrayBuffers/1024**2)})),timing:metrics([...actions.rows,...ready(actions.rows)],'final-actions',size),variedDepth:metrics([...full.rows.filter(r=>r.name==='seek'),...deepWorst(full.rows)],'full-varied-depth',size)});
}
for(const spacing of [8,32,128]){const full=read(resolve(local,`policy/256-${spacing}.json`));assert(full.passed);summary.policyPilot.push({size:256,steps:64,spacing,bytes:full.bytes,checkpoints:full.checkpoints,timing:metrics(full.rows.filter(r=>r.name==='seek'&&r.target===63),'policy-64-edits',256)});}
for(const engine of ['chromium','firefox','webkit'])for(const size of [256,512])for(const suffix of ['32','modern']){
 const name=`${size}-${suffix}`,file=resolve(local,`browser/${engine}-${name}.json`);if(preview&&!existsSync(file))continue;const runs=read(file);if(preview&&runs.length!==3)continue;assert.equal(runs.length,3,name+' '+engine);assert.deepEqual(runs.map(x=>x.repeat),[1,2,3]);assert.equal(runs[0].allDepths.positions,suffix==='32'?2049:7);const oracle=read(resolve(local,`runs/${name}.json`));assert(runs.every(x=>x.exportHash===oracle.exportHash));
 const rows=runs.flatMap(run=>run.rows.map(r=>({...r,repeat:run.repeat})));summary.browsers.push({engine,version:runs[0].version,size,session:suffix==='32'?'2048 edits':'five newly hashed forces',storage:runs[0].storage,saveScope:'Encoding with counting sink; actual saved disk readback is reported separately in saveRoundTrips.',positions:runs[0].allDepths.positions,proofMs:runs[0].allDepths.ms,exportHash:oracle.exportHash,timing:metrics([...rows,...ready(rows),...(suffix==='32'?deepWorst(rows):[])],'browser-'+suffix,size,engine),maxWrite:Math.max(...runs.flatMap(x=>x.rows.filter(r=>r.name==='save').map(r=>r.maxWrite))),pageTimerMaxGap:Math.max(...runs.map(x=>x.pageTimerMaxGap))});
}
for(const engine of ['chromium','firefox','webkit'])for(const size of [256,512]){const [run]=read(resolve(local,`final-contracts/${engine}-${size}-modern.json`));assert(run.bookkeeping&&Object.values(run.bookkeeping).every(Boolean)&&run.bookkeeping.canonicalWaterBoundaries);assert.equal(run.allDepths.positions,7);summary.finalContracts.push({engine,size,...run.bookkeeping});}
summary.contracts=read(resolve(local,'contracts.json'));assert(summary.contracts.passed);
summary.saveRoundTrips=[];
for(const engine of ['chromium','firefox','webkit'])for(const size of [256,512]){const file=resolve(local,`save-roundtrips/${engine}-${size}-32.json`);if(preview&&!existsSync(file))continue;const runs=read(file);if(preview&&runs.length!==3)continue;assert.equal(runs.length,3);const oracle=read(resolve(local,`runs/${size}-32.json`));assert(runs.every(r=>r.savedFileRoundTrip&&r.exportHash===oracle.exportHash));summary.saveRoundTrips.push({engine,size,storage:runs[0].storage,scope:'Final writer streams into owned worker disk cache; reopening reads those saved chunks into a separate fresh cache. All current-state/export hashes match, three repetitions.',bytes:runs[0].bytes,timing:metrics(runs.flatMap(run=>run.rows.map(r=>({...r,repeat:run.repeat}))),'saved-disk-roundtrip',size,engine)});}
for(const c of summary.cases){const files=summary.saveRoundTrips.filter(r=>r.size===c.size);if(files.length){assert(files.every(r=>r.bytes===files[0].bytes));c.nodeLatencyArchiveBytes=c.projectBytes;c.projectBytes=files[0].bytes;c.projectScope='2048 accepted edits/current cursor; final browser writer. Node latency archive additionally retains the verification brush as redo.';}}
summary.timerDiagnostics=[];
for(const size of [256,512]){const file=resolve(local,`timer-diagnostic/chromium-${size}-32.json`);if(!existsSync(file))continue;const runs=read(file);if(preview&&runs.length!==3)continue;assert.equal(runs.length,3);summary.timerDiagnostics.push({engine:'chromium',size,scope:'Separate passive timer/long-task trace; no all-depth proof, not the primary timing comparison.',runs:runs.map(r=>({repeat:r.repeat,observer:r.longTaskObserver,gaps:r.pageTimerGaps,longTasks:r.pageLongTasks})),timing:metrics(runs.flatMap(r=>r.rows.map(row=>({...row,repeat:r.repeat}))),'timer-diagnostic',size,'chromium')});}
if(preview)writeFileSync(resolve(local,'preview.json'),JSON.stringify(summary,null,2)+'\n');
else{writeFileSync(resolve(dir,'measurements.json'),JSON.stringify(summary,null,2)+'\n');writeFileSync(resolve(dir,'timings.csv'),csv.join('\n')+'\n');}
console.log(preview?'Partial local preview':'Verified compact evidence',summary.cases.length,summary.browsers.length,summary.finalContracts.length);
