import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {dir} from './overlay.mjs';
const local=resolve(dir,'../local/round2');
const read=p=>JSON.parse(readFileSync(resolve(local,p),'utf8'));
const median=a=>{const b=[...a].sort((x,y)=>x-y);return b.length%2?b[b.length>>1]:(b[b.length/2-1]+b[b.length/2])/2;};
const loads=['accepted/load.jsonl','accepted/recent-load.jsonl','accepted/baseline-load.jsonl','policy-accepted/load.jsonl','policy-fixed/load.jsonl','browser/load.jsonl','browser-large/load.jsonl'].filter(p=>existsSync(resolve(local,p))).flatMap(p=>readFileSync(resolve(local,p),'utf8').trim().split(/\r?\n/).filter(Boolean).map(s=>{const r=JSON.parse(s);return {cpuPercent:r.cpuPercent,availableBytes:r.availableBytes,time:Date.parse(r.at)};})).sort((a,b)=>a.time-b.time);
function samples(row){const inRun=loads.filter(s=>s.time>=row.at&&s.time<=row.at+row.ms);if(inRun.length)return inRun;const near=loads.reduce((a,b)=>Math.abs(b.time-row.at)<Math.abs(a.time-row.at)?b:a);assert(Math.abs(near.time-row.at)<15000,'missing contemporary load');return [near];}
function timing(rows,name,depth){const r=rows.filter(r=>r.name===name&&(depth===undefined||r.depth===depth));assert(r.length>=3,`${name}/${depth} needs three repetitions`);const l=r.flatMap(samples);return {n:r.length,medianMs:median(r.map(r=>r.ms)),worstMs:Math.max(...r.map(r=>r.ms)),cpuMedianPercent:median(l.map(r=>r.cpuPercent)),cpuWorstPercent:Math.max(...l.map(r=>r.cpuPercent)),minimumAvailableBytes:Math.min(...l.map(r=>r.availableBytes))};}
function compact(path,policy=false){const d=read(path);assert(d.final?.parity&&!d.failure,`incomplete/failed ${path}`);assert.equal(d.refusals.length,0);const mem=d.rows.filter(r=>r.name==='memory');const rows=[...d.rows];if(!policy&&!rows.some(r=>r.name==='undo-recent')){const recent=read(path.replace('.json','.recent-128.json'));assert(recent.parity);rows.push(...recent.rows);}
 if(!policy&&d.phase==='after'){const recent=read(path.replace('.json','.recent-128.json'));assert(recent.parity);d.recentCache=recent.cache;assert(recent.cache.bytes<=recent.cache.budget);for(let i=rows.length-1;i>=0;i--)if(['undo-recent','redo-recent'].includes(rows[i].name))rows.splice(i,1);rows.push(...recent.rows);}
 return {source:path,phase:d.phase,size:d.size,steps:d.steps,forces:d.forces,final:d.final,memory:mem.map(r=>({step:r.step,...r.memory,maxRSS_KiB:r.maxRSS_KiB,cache:r.cache,cacheDiskBytes:r.cacheDiskBytes})),recentCache:d.recentCache,timing:Object.fromEntries((policy?['save-project','reopen-project']:['undo-recent','redo-recent','save-project','reopen-project']).map(n=>[n,timing(rows,n)]).concat(['undo','redo'].map(n=>[n+'-depth32',timing(rows,n,32)]))),projectBytes:d.rows.find(r=>r.name==='save-project').bytes,maxWrite:Math.max(...d.rows.filter(r=>r.name==='save-project').map(r=>r.maxWrite)),baselineRedoMismatches:d.redoMismatches};}
const cases=['accepted/before-256-1-128.json','accepted/after-256-1-128.json','accepted/before-512-1-128.json','accepted/after-512-1-128.json'].map(p=>compact(p));
for(const size of [256,512]){const a=read(`accepted/before-${size}-1-128.json`),b=read(`accepted/after-${size}-1-128.json`);assert.equal(a.trace.length,2048);assert.deepEqual(a.trace,b.trace,'every forward state must be exact');assert.equal(a.final.exportHash,b.final.exportHash);assert.equal(a.final.state,b.final.state);assert.deepEqual(a.forces,b.forces);assert.equal(Object.keys(b.forces).length,5);}
const policies=['policy-accepted/after-256-1-64.json','policy-accepted/after-256-1-256.json','cold-fix/after-512-1-64.json','policy-fixed/after-512-1-256.json'].map(p=>compact(p,true));
const evidence={base:'75cb5d4c4a168eb17113bd0dd19576bb43b3ffc9',determinism:'f306fd495c713e19278c507686102b2c603cdef8',scope:'Actual core under Node, same canonical-water/portable-math policy both variants. Memory: GC checkpoints, not browser-page RAM; sampled OS loads, RSS includes transient allocation. Snapshot byte accounting excludes JS bookkeeping. Journal metadata/disk grow with edit count.',timingScope:'End actions repeated three times. Construction diagnostic only. Report depth32 separately from recent pair. CPU is whole-machine load, not a causal speedup control.',cases,policies,dense:[read('dense-256.json'),read('dense-512.json')],stringLimit:read('string-limit.json'),rectangles:read('rectangles.json'),browser:read('browser/results.json'),browserLargeFixture:read('browser-source/long-512.json'),browserLarge:read('browser-large/results.json')};
evidence.verification={legacyContracts:90,controller:read('contracts.json'),codec:read('codec-checks.json')};assert(evidence.verification.controller.passed&&evidence.verification.codec.passed);
evidence.browserMemory=read('browser-large/memory-diagnostic.json');
evidence.revisionNotes='Primary profile processes started before final rejection guards, preparation-failure rollback, metadata snapshot and post-settle budget enforcement. Successful replay arithmetic/codec unchanged; fixes verified separately with frozen raw/export golden and cold contracts. Recent action pairs use the post-settle-trim controller after fresh replay of both full 2048-edit files; settings rejection was subsequently tightened without changing successful replay. Browser storage profile predates post-settle trim and shows a 0.33 MiB overshoot; final budget enforcement is checked separately.';
assert(evidence.dense.every(d=>d.readback));assert(evidence.stringLimit.streamedSaveAndRead&&evidence.stringLimit.giantStringFailed);assert.equal(evidence.browser.length,9);assert.equal(evidence.browserLarge.length,6);
assert(evidence.rectangles.every(r=>r.parity));assert(evidence.browserLarge.every(r=>r.count===2048&&r.hash===evidence.browserLargeFixture.final.exportHash&&r.storage==='worker OPFS'));
evidence.browserTiming=[];for(const [group,rows]of [['fiveForceOracle',evidence.browser],['long512Storage',evidence.browserLarge]])for(const engine of new Set(rows.map(r=>r.engine))){const r=rows.filter(r=>r.engine===engine);assert.equal(r.length,3);const timed=r.flatMap(x=>[{name:'open-total',at:x.at,ms:x.openMs},{name:'save-project',at:x.at+x.openMs,ms:x.saveMs},{name:'reopen-total',at:x.at+x.openMs+x.saveMs,ms:x.reopenMs}]);evidence.browserTiming.push({group,engine,timing:Object.fromEntries(['open-total','save-project','reopen-total'].map(n=>[n,timing(timed,n)])),scope:'Browser total opening includes canonical settling/export oracle, unlike Node replay-only timing. Sample intervals use worker phase offsets from parent start.'});}
writeFileSync(resolve(dir,'measurements.json'),JSON.stringify(evidence,null,2)+'\n');
const columns=['size','phase','action','n','medianMs','worstMs','cpuMedianPercent','cpuWorstPercent','minimumAvailableBytes'];const csv=[columns.join(',')];for(const c of cases)for(const [action,t]of Object.entries(c.timing))csv.push([c.size,c.phase,action,...columns.slice(3).map(k=>t[k])].join(','));writeFileSync(resolve(dir,'timings.csv'),csv.join('\n')+'\n');
console.log('All forward states, cold round trips, complete exports and repeated action/load evidence validated.');for(const c of cases)console.log(c.size,c.phase,c.projectBytes,c.timing);
