import {createRequire} from 'node:module';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {mkdirSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
export const HERE=dirname(fileURLToPath(import.meta.url)),ROOT=resolve(HERE,'../..'),LOCAL=resolve(HERE,'local');
mkdirSync(LOCAL,{recursive:true});
export const WORKSPACE=resolve(ROOT,'../../..');
export const WATER=process.env.DGM_WATER??resolve(WORKSPACE,'rust-water/local/checkout/investigation/rust-water');
export const deps=createRequire(resolve(process.env.DGM_DEPS??resolve(WORKSPACE,'startup/local/checkout'),'package.json'));
export const hash=b=>createHash('sha256').update(b).digest('hex');
export const json=(name,data)=>writeFileSync(resolve(LOCAL,name),JSON.stringify(data,null,2)+'\n');
export const arg=(name,fallback)=>{const i=process.argv.indexOf('--'+name);return i<0?fallback:process.argv[i+1];};
