import fs from 'node:fs';
import path from 'node:path';
const dir='investigation/map-switch-speed/local';
const files=['src/ui/App.tsx','src/worker/session.ts','src/ui/View3D.tsx','src/core/sim/parallelPolicy.ts','src/platform/index.ts'];
for(const f of files){const p=path.join(dir,'baseline',f);fs.mkdirSync(path.dirname(p),{recursive:true});if(!fs.existsSync(p))fs.copyFileSync(f,p);const backup=path.join(dir,'instrument-backup',f);fs.mkdirSync(path.dirname(backup),{recursive:true});fs.copyFileSync(f,backup);}
const edit=(f,fn)=>fs.writeFileSync(f,fn(fs.readFileSync(f,'utf8')));
edit('src/ui/App.tsx',s=>s.replace('    const e = list.find((m) => m.id === id);','    (window as any).__switch = {start: performance.now(), stages: {}};\n    const e = list.find((m) => m.id === id);').replace('      await saver.flush();\n      return await load();','      const t = performance.now(); await saver.flush();\n      if ((window as any).__switch) (window as any).__switch.stages.save = performance.now()-t;\n      return await load();').replaceAll('        const bytes = await yourMaps.project(id);','        let t=performance.now(); const bytes = await yourMaps.project(id);\n        if ((window as any).__switch) (window as any).__switch.stages.read = performance.now()-t;').replace('        return openEntry(bytes, e);','        t=performance.now(); const result=await openEntry(bytes, e);\n        Object.assign((window as any).__switch, {worker: (result as any).__profile});\n        (window as any).__switch.stages.worker=performance.now()-t;\n        return result;').replace('      await saver.flush();\n      switching.current = true;', '      const t = performance.now(); await saver.flush();\n      if ((window as any).__switch) (window as any).__switch.stages.save = performance.now()-t;\n      switching.current = true;').replace('    const now = new Date().toISOString();\n    const isNew', '    if ((window as any).__switch) (window as any).__switch.enter = performance.now();\n    const now = new Date().toISOString();\n    const isNew'));
edit('src/worker/session.ts',s=>s.replace('  const s = MapSession.open(decodeProject(bytes));','  let t=performance.now(); const doc=decodeProject(bytes); const profile: any={decode:performance.now()-t};\n  t=performance.now(); const s = MapSession.open(doc); profile.open=performance.now()-t;').replace('  const doc = decodeProject(bytes);', '  let t=performance.now(); const doc=decodeProject(bytes); const profile: any={decode:performance.now()-t};').replace('  const s = MapSession.open(doc, { deferWater: !drawn });', '  t=performance.now(); const s = MapSession.open(doc, { deferWater: !drawn }); profile.open=performance.now()-t;').replace('  bakeLandforms(s);\n  return opened(s);','  t=performance.now(); bakeLandforms(s); profile.bake=performance.now()-t;\n  t=performance.now(); const result=opened(s); profile.view=performance.now()-t;\n  return Object.assign(result, {__profile:profile});'));
edit('src/ui/View3D.tsx',s=>s.replace('    const stats = r.setMap(props.view, keep);','    const t=performance.now(); const stats = r.setMap(props.view, keep);\n    if ((window as any).__switch) (window as any).__switch.setMap={ms:performance.now()-t, stats};').replace('    props.onReady?.(r, stats);','    props.onReady?.(r, stats);\n    if ((window as any).__switch) (window as any).__switch.ready=performance.now();'));
// Measurement cap: two water threads per pool; a foreground and checks worker plus main/GPU remain within six active CPU cores.
edit('src/core/sim/parallelPolicy.ts',s=>s.replace('const MAX_THREADS = 16;','const MAX_THREADS = 2;').replace('let t = 8;','let t = 2;'));
edit('src/platform/index.ts',s=>s.replace('const count = Math.min(threadsFor(256 * 256), (navigator.hardwareConcurrency || 4) - 1) - 1;','const count = 0;'));
