import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {gunzipSync} from 'node:zlib';
import {strict as assert} from 'node:assert';
import {dir,root} from './build.mjs';
const median=a=>{a=a.filter(Number.isFinite).sort((x,y)=>x-y);return a.length?(a[(a.length-1)>>1]+a[a.length>>1])/2:null;};
const worst=a=>a.length?Math.max(...a):null;
const file=resolve(dir,'local/full.jsonl');
const raw=readFileSync(file,'utf8');
const key=r=>`${r.theme}/${r.size}/${r.seed}/${r.rep}/${r.variant}`;
const observations=raw.trim().split('\n').filter(Boolean).map(JSON.parse);
const records=[...new Map(observations.map(r=>[key(r),r])).values()];
const themes=['any','riverValley','canyon','highlands','lakeBasin','delta','islands'],sizes=[96,128,256];
const failureFile=resolve(dir,'local/browser-failures.jsonl');
const browserFailures=existsSync(failureFile)?readFileSync(failureFile,'utf8').trim().split('\n').filter(Boolean).map(JSON.parse):[];
writeFileSync(resolve(dir,'BROWSER-FAILURES.json'),JSON.stringify(browserFailures,null,2)+'\n');
const timedSeeds=size=>size===256?20:5;
const expected=2520;
if(process.argv.includes('--partial')){console.log({rows:records.length,expected,pairsDone:records.filter(r=>r.rawCompared).length});process.exit(0);}
assert.equal(records.length,expected,'full three-repeat timing and 40-seed identity matrix required');
for(const size of sizes)for(const theme of themes)for(let seed=1;seed<=40;seed++)for(let rep=0;rep<(seed<=timedSeeds(size)?3:1);rep++){
 const pair=['before','after'].map(variant=>records.find(r=>r.theme===theme&&r.size===size&&r.seed===seed&&r.rep===rep&&r.variant===variant));assert(pair.every(Boolean),'missing pair');assert.deepEqual(pair[0].identity,pair[1].identity);assert(pair.some(r=>r.rawCompared),'pair lacks direct raw comparison');
 if(rep>0)assert.deepEqual(pair[0].identity,records.find(r=>r.theme===theme&&r.size===size&&r.seed===seed&&r.rep===0&&r.variant==='before').identity,'repeat changed deterministic result');
}
const names={any:'Any',riverValley:'River Valley',canyon:'Canyon',highlands:'Highlands',lakeBasin:'Lake Basin',delta:'Delta',islands:'Islands'};
const fmt=n=>n===null?'–':(n/1000).toFixed(2);
const timeRows=[],profileRows=[],rejections=[];
for(const size of sizes)for(const theme of themes){
 const n=timedSeeds(size),rows=records.filter(r=>r.theme===theme&&r.size===size&&r.seed<=n);
 const item={theme,size};
 for(const v of ['before','after'])for(const stage of ['firstLook','firstWater','final']){
  const selected=rows.filter(r=>r.variant===v&&r.timings[stage]>=0),values=observations.filter(r=>r.theme===theme&&r.size===size&&r.seed<=n&&r.variant===v&&r.timings[stage]>=0).map(r=>r.timings[stage]);
  const perSeed=Array.from({length:n},(_,i)=>median(selected.filter(r=>r.seed===i+1).map(r=>r.timings[stage]))).filter(x=>x!==null);
  item[v+'_'+stage+'_median']=median(perSeed);item[v+'_'+stage+'_worst']=worst(values);
 }
 for(const v of ['before','after']){const sr=rows.filter(r=>r.variant===v);item[v+'_cpu_median']=median(Array.from({length:n},(_,i)=>median(sr.filter(r=>r.seed===i+1).map(r=>r.cpu))));item[v+'_load_median']=median(sr.map(r=>r.load.mean).filter(x=>x!==null));item[v+'_load_worst']=worst(sr.map(r=>r.load.max).filter(x=>x!==null));}
 timeRows.push(item);
 if(size===256){for(const v of ['before','after']){const sr=rows.filter(r=>r.variant===v),sums={};for(const r of sr)for(const [k,val]of Object.entries(r.prof.categories))sums[k]=(sums[k]??0)+val;profileRows.push({theme,variant:v,...sums});}}
 const why=new Map();
 for(const r of rows.filter(r=>r.variant==='before')){let prev=0;for(const a of r.attempts){const elapsed=a.at-prev;prev=a.at;if(a.passed||a.firstLand>=0)continue;const w=why.get(a.stage)??{count:0,seeds:new Set(),spent:[]};if(r.rep===0){w.count++;w.seeds.add(r.seed);}w.spent.push(elapsed);why.set(a.stage,w);}}
 for(const [reason,w]of why)rejections.push({theme,size,reason,attempts:w.count,seeds:w.seeds.size,median:median(w.spent),worst:worst(w.spent),total:w.spent.reduce((a,b)=>a+b,0)});
}
function csv(name,rows){const keys=[...new Set(rows.flatMap(Object.keys))];const quote=v=>JSON.stringify(v??'');writeFileSync(resolve(dir,name),keys.map(quote).join(',')+'\n'+rows.map(r=>keys.map(k=>quote(r[k])).join(',')).join('\n')+'\n');}
csv('TIMINGS.csv',timeRows);csv('PROFILE.csv',profileRows);csv('REJECTIONS.csv',rejections);
const cpuSamples=[];
for(const theme of themes){const p=JSON.parse(readFileSync(resolve(dir,`local/${theme}.cpuprofile`)));const nodes=new Map(p.nodes.map(n=>[n.id,n.callFrame]));const counts=new Map();for(const id of p.samples){const f=nodes.get(id);counts.set(f.functionName,(counts.get(f.functionName)??0)+1);}for(const [functionName,samples]of [...counts].sort((a,b)=>b[1]-a[1]).slice(0,10))cpuSamples.push({theme,seed:1,functionName,samples,percent:100*samples/p.samples.length});}
csv('CPU-SAMPLES.csv',cpuSamples);
const prior=gunzipSync(readFileSync(resolve(root,'investigation/m9b/baseline/13d1f1a2-256.jsonl.gz'))).toString().trim().split('\n').map(JSON.parse).filter(r=>r.seed<=20);
csv('SETTLE-TICKS.csv',themes.map(theme=>{const sr=prior.filter(r=>r.theme===theme);return{theme,source:'M9b 13d1f1a2 baseline (identical core at e292cefe)',finalTicksMedian:median(sr.map(r=>r.settleTicks)),finalTicksWorst:worst(sr.map(r=>r.settleTicks)),settlesMedian:median(sr.map(r=>r.settles)),settlesWorst:worst(sr.map(r=>r.settles))};}));
const refusals=records.filter(r=>r.variant==='before'&&r.rep===0&&!r.passed).map(r=>({theme:r.theme,size:r.size,seed:r.seed,stages:r.attempts.slice(-1).map(a=>a.stage)}));
const baseline=JSON.parse(readFileSync(resolve(dir,'BASE.json'))),manifest=JSON.parse(readFileSync(resolve(dir,'local/full-manifest.json')));
const identity={base:baseline.base,uniqueInputs:840,pairs:1260,generations:2520,observedGenerations:observations.length,directRawPairs:records.filter(r=>r.rawCompared).length,hashMismatches:0,rawMismatches:0,identityIncludes:['first land and its planned water','terrain and every built typed array','returned canonical depth/contamination/saturation/outflow/stop ticks','entities and all object data','complete .timber bytes including refused empty exports','features, genome, attempts, diagnostics, decisions and reports'],excluded:['informational elapsed timings','failure elapsed milliseconds'],refusals,rawEvidenceSha256:createHash('sha256').update(raw).digest('hex'),manifest,candidate:baseline.files};
writeFileSync(resolve(dir,'IDENTITY.json'),JSON.stringify(identity,null,2)+'\n');
let report=`# Generation speed at 256²\n\nBase: M9b \`${baseline.base.slice(0,8)}\`. Product code is unchanged. Adopt [adoption.patch](adoption.patch) through the milestone; [INTEGRATION.md](INTEGRATION.md) has the exactness argument and regeneration commands.\n\nThe candidate shares read-only start fields across the four picks made before levelling, uses a histogram for the byte-height median, stops a mine-room scan once one/two sites are proved, and skips a wall's second side when the first cannot qualify. Random draws, scores, rejection order, attempts, first land, water arithmetic and stopping rules are unchanged. M9b already contains water-speed's faster scalar settle; this does not redo it or add parallel-water/startup's pending integration.\n\n`;
report+=`## Before and after\n\nSeconds: **median / worst**, before → after. At 256² seeds 1–20 have three interleaved pairs (60 runs per variant/theme); at 96²/128² seeds 1–5 have three pairs (15 runs). Median is over per-seed medians of complete pairs; worst includes every recorded repeat, including resumed partial-pair reruns. Normal/default settings. Four isolated generation workers; total Windows CPU load median ${median(records.filter(r=>r.seed<=timedSeeds(r.size)).map(r=>r.load.mean).filter(x=>x!==null))?.toFixed(1)}%, worst ${worst(records.map(r=>r.load.max).filter(x=>x!==null))?.toFixed(1)}%. ${manifest.cpus[0].trim()}, ${manifest.cpus.length} logical CPUs, ${(manifest.memory/2**30).toFixed(0)} GiB; Windows, Node ${manifest.node}. The browser checks, contract tests, other investigations and applications ran concurrently during portions of the matrix. These are loaded timings, not an idle-machine certification of D333's 3/8 s targets. [Thread CPU and load by cell](TIMINGS.csv). ${observations.filter(r=>r.load.mean===null).length} observations have no counter sample (recorded as missing, never zero); their durations remain included.\n\n| Theme | Size | First land before → after | Water/start fixed before → after | Finished before → after |\n|---|---:|---:|---:|---:|\n`;
for(const r of timeRows){const cell=s=>`${fmt(r['before_'+s+'_median'])} / ${fmt(r['before_'+s+'_worst'])} → ${fmt(r['after_'+s+'_median'])} / ${fmt(r['after_'+s+'_worst'])}`;report+=`| ${names[r.theme]} | ${r.size}² | ${cell('firstLook')} | ${cell('firstWater')} | ${cell('final')} |\n`;}
report+=`\nThe core's \`firstWater\` includes water repairs and choosing its start. M9b's first-land canvas is a preview without editing handlers; water is shown at the candidate/finished preview, and editing starts after Refine. The browser results below measure those real boundaries, including message transit and painting.\n\n## Where time goes\n\nAll 140 theme/seed inputs at 256² are traced on every repeat. [PROFILE.csv](PROFILE.csv) contains disjoint wall-time totals before/after land; [REJECTIONS.csv](REJECTIONS.csv) counts refused plans and their cost. Initial shaping repeatedly runs noise and erosion's priority floods; planning cuts/checks courses. Prepared starts repeat shore walks, drought/storage fields and terrain statistics. Later fixes and builds spend most of their time advancing water; the existing settle cache already reuses equal models. Seed-1 [V8 samples](CPU-SAMPLES.csv) put substep at 51% in River Valley and 77% in Islands, versus 24% in Canyon, where wall checks and priority-flood drainage are also costly. M9b’s existing [tick evidence](SETTLE-TICKS.csv) shows 1,792–2,816 median final settle ticks by theme, up to 4,352 ticks and five separate settles: large wet areas and repeated fixes explain the water tail. This patch leaves those exact steps intact. The patch removes duplicate start work and impossible check branches. It does not remove necessary rejected draws: changing a threshold, screen budget, start preparation or six-day settle cap can change which map is chosen. [Result-changing proposals](PROPOSALS.md) are separate and unmeasured.\n\n`;
if(existsSync(resolve(dir,'local/browser.jsonl'))){const br=readFileSync(resolve(dir,'local/browser.jsonl'),'utf8').trim().split('\n').filter(Boolean).map(JSON.parse);assert.equal(br.length,42,'complete browser timing matrix required');report+=`Browser: actual production page/worker, headless Chrome ${br[0].browser} with an RTX 4080 SUPER via ANGLE/D3D11 ([renderer metadata](BROWSER-GPU.json)), seed 1 at 256² for every theme, three reversed-order pairs; fresh contexts, a small-map worker/UI warm-up, native page/worker/GPU. Editing was proved by a real Raise click; undo restored every terrain byte on all 42 completed visits. Seconds median / worst:\n\n| Theme | First land paint before → after | Settled preview before → after | Editable GPU frame before → after |\n|---|---:|---:|---:|\n`;const bs=[];for(const t of themes){const cell=stage=>['before','after'].map(v=>{const sr=br.filter(r=>r.theme===t&&r.variant===v);const vals=sr.map(r=>stage==='editable'?r.editable:r.events.find(e=>e.name===stage)?.at).filter(Number.isFinite);const timedOut=browserFailures.some(f=>f.theme===t&&f.variant===v&&f.phase==='editor-ready');return `${fmt(median(vals))} / ${stage==='editable'&&timedOut?'>300 (timeout)':fmt(worst(vals))}`;}).join(' → ');report+=`| ${names[t]} | ${cell('landPaintFrame')} | ${cell('settledPaintFrame')} | ${cell('editable')} |\n`;bs.push({theme:t,...Object.fromEntries(['before','after'].flatMap(v=>{const sr=br.filter(r=>r.theme===t&&r.variant===v);return ['landPaintFrame','settledPaintFrame','editable'].flatMap(s=>{const vals=sr.map(r=>s==='editable'?r.editable:r.events.find(e=>e.name===s)?.at).filter(Number.isFinite);return [[v+'_'+s+'_median',median(vals)],[v+'_'+s+'_worst',worst(vals)]];});}))});}for(const summary of bs)for(const v of ['before','after']){const fs=browserFailures.filter(f=>f.theme===summary.theme&&f.variant===v&&f.phase==='editor-ready');summary[v+'_editorReady_timeouts']=fs.length;summary[v+'_editable_worst_lower_bound']=Math.max(summary[v+'_editable_worst']??0,...fs.map(f=>f.timeoutMs??300000));}csv('BROWSER.csv',bs);report+=`\n${browserFailures.length?`A baseline Delta editor-readiness wait timed out at 300 s; its Generate-to-editable worst is therefore **over 300 s**, not just the completed-run maximum. The retry completed. [Failure evidence](BROWSER-FAILURES.json). The original failed visit did not retain its counter samples; successful visits and concurrent core runs record host load. This is a censored harness readiness observation, not a diagnosed product fault.\n\n`:''}Browser whole-machine CPU load: median ${median(br.map(r=>r.load.mean).filter(Number.isFinite)).toFixed(1)}%, worst ${worst(br.map(r=>r.load.max).filter(Number.isFinite)).toFixed(1)}%. Refine is clicked immediately after the finished preview; network/startup and human hesitation are excluded. These loaded native-desktop results do not prove laptop compliance.\n\n`;}
const focused=JSON.parse(readFileSync(resolve(dir,'local/focused.json'))),tests=JSON.parse(readFileSync(resolve(dir,'local/tests-after.json')));
const types=JSON.parse(readFileSync(resolve(dir,'local/typecheck.json')));
assert(types.results.every(r=>r.diagnostics===0));assert.equal(types.results.length,2);
assert.equal(tests.numFailedTests,0);assert.equal(tests.numPassedTests,21);
writeFileSync(resolve(dir,'VALIDATION.json'),JSON.stringify({base:baseline.base,candidate:baseline.files,typecheck:types.results,focused,tests:{passed:tests.numPassedTests,failed:tests.numFailedTests,files:tests.numPassedTestSuites,reportSha256:createHash('sha256').update(readFileSync(resolve(dir,'local/tests-after.json'))).digest('hex')}},null,2)+'\n');
const shared=JSON.parse(readFileSync(resolve(dir,'SHARED-COST.json')));
assert(shared.byteIdentical);assert.equal(shared.rows[0].droughtCalls,12);assert.equal(shared.rows[1].droughtCalls,2);
for(const r of records.filter(r=>r.theme==='lakeBasin'&&r.size===256&&r.seed===7)){
 assert.equal(r.prof.totals['preland:sim/drought.ts:droughtStorage'].calls,r.variant==='before'?12:2);
 assert.equal(r.prof.totals['preland:gen/settler.ts:pickStart'].calls,4);
}
const sharedText=`Lake Basin round 2 at this base found 12 pre-land drought calls but two complete inputs (282 ms CPU), plus four distinct start picks (937 ms CPU), on 256² seed 7. [Independent input/byte verification](SHARED-COST.json) and all three matrix repeats confirm **12 → 2 drought calculations, 4 → 4 selections**. The four picks share read-only fields; the intentions view consumes the already-computed nine-day storage. Fields are discarded before terrain/water mutations; later picks prepare fresh data. Peer CPU values are single observations, not a claimed 1.2 s saving.\n\n`;
report=report.replace('## Before and after',sharedText+'## Before and after');
const ratios=[];
for(const b of records.filter(r=>r.variant==='before'&&r.size===256&&r.seed<=20)){const a=records.find(r=>r.variant==='after'&&r.theme===b.theme&&r.size===b.size&&r.seed===b.seed&&r.rep===b.rep);ratios.push(100*(1-a.cpu/b.cpu));}
report=report.replace('Seconds: **median / worst**,',`Median paired generation thread-CPU saving at 256²: **${median(ratios).toFixed(1)}%**. Native-page wall time remains noisy and does not improve in every theme; the 3/8 s targets are not established by this loaded run.\n\nSeconds: **median / worst**,`);
const stageCells=[];
for(const theme of themes){
 const p=profileRows.find(r=>r.theme===theme&&r.variant==='before');
 const total=phase=>Object.entries(p).filter(([k,v])=>k.startsWith(phase+':')).reduce((s,[k,v])=>s+v,0);
 const share=(phase,cats)=>cats.reduce((s,c)=>s+(p[phase+':'+c]??0),0)/total(phase)*100;
 const before=records.filter(r=>r.theme===theme&&r.size===256&&r.seed<=20&&r.variant==='before'),spent=[];
 for(const r of before){let prev=0;for(const a of r.attempts){const duration=a.at-prev;prev=a.at;if(!a.passed&&a.firstLand<0)spent.push(duration);}}
 stageCells.push(`| ${names[theme]} | ${share('preland',['shaping']).toFixed(0)}% | ${share('preland',['planning']).toFixed(0)}% | ${share('preland',['start']).toFixed(0)}% | ${share('preland',['checks']).toFixed(0)}% | ${share('preland',['mines','hazards','build-prefill','other']).toFixed(0)}% | ${share('postland',['settle']).toFixed(0)}% | ${(100*spent.reduce((s,x)=>s+x,0)/total('preland')).toFixed(0)}% |`);
}
const stages=`Disjoint baseline wall-time shares across all 20 seeds/repeats at 256²; redraw is an overlapping share of pre-land time, not another stage. “Other pre-land” includes mine/hazard preparation, builds and glue.\n\n| Theme | Shaping | Planning | Starts | Checks | Other pre-land | Settle share after land | Redraw share before land |\n|---|---:|---:|---:|---:|---:|---:|---:|\n${stageCells.join('\n')}\n\n`;
report=report.replace('All 140 theme/seed inputs at 256² are traced on every repeat.',stages+'All 140 theme/seed inputs at 256² are traced on every repeat.');
const rejectCounts=new Map();let redrawMs=0,prelandMs=0;
for(const r of records.filter(r=>r.size===256&&r.seed<=20&&r.variant==='before')){
 for(const [k,v]of Object.entries(r.prof.categories))if(k.startsWith('preland:'))prelandMs+=v;
 let prev=0;for(const a of r.attempts){const duration=a.at-prev;prev=a.at;if(a.passed||a.firstLand>=0)continue;redrawMs+=duration;if(r.rep===0)rejectCounts.set(a.stage,(rejectCounts.get(a.stage)??0)+1);}
}
const refusedPlans=[...rejectCounts.values()].reduce((s,n)=>s+n,0),topRejects=[...rejectCounts].sort((a,b)=>b[1]-a[1]).slice(0,3).map(([reason,n])=>`${reason}: ${n}`).join('; ');
report=report.replace('All 140 theme/seed inputs at 256² are traced on every repeat.',`Before first land, these 140 inputs refuse **${refusedPlans} plans**; redraws consume **${(100*redrawMs/prelandMs).toFixed(1)}%** of pre-land wall time. Most frequent: ${topRejects}. The course and promise screens already run before start preparation; skipping them changes the selected map.\n\nAll 140 theme/seed inputs at 256² are traced on every repeat.`);
const browserIdentity=JSON.parse(readFileSync(resolve(dir,'BROWSER-IDENTITY.json')));
assert.equal(browserIdentity.mismatches,0);assert.equal(browserIdentity.browserVisits,42);
report+=`The 42 browser visits also match uninstrumented Node first-land and download hashes ([BROWSER-IDENTITY.json](BROWSER-IDENTITY.json)).\n\n`;
report+=`## Identity\n\n**Zero differences:** all 840 current M9b batch inputs (seeds 1–40, all seven themes, 96²/128²/256²), ${identity.directRawPairs} direct complete-state byte comparisons, including the first land and all water/object/export bytes. ${refusals.length} identical refusals are retained, not counted as valid exports. [Bound evidence](IDENTITY.json). Focused parity: ${focused.rooms} mine grids, ${focused.walls} wall scenes (${focused.positiveWalls} positive), ${focused.picks} repeated picks plus ${focused.rngTail} subsequent random draws. Full baseline/candidate typechecks pass; ${tests.numPassedTests} existing focused tests pass. Adoption patch applies cleanly. Large raw runs, profiles and builds are ignored under \`local/\`; regenerate them with the integration commands.\n`;
// Keep the report short; adoption details and methodology live in INTEGRATION.
report=report.replace(/The candidate shares[\s\S]*?\n\nLake Basin/, 'Changes: shared start preparation and nine-day storage; histogram median; exact early exits in mine-room and wall checks. RNG, rejection order and water arithmetic stay unchanged. Water-speed is already adopted; parallel-water/startup work is retained.\n\nLake Basin');
report=report.replace(/Lake Basin round 2[\s\S]*?\n\n## Before/, 'Lake Basin 256² seed 7: **12 → 2 drought calculations, 4 → 4 selections**, confirmed on all three repeats ([input/byte audit](SHARED-COST.json)). Shared fields expire before levelling; later picks prepare fresh data. The peer audit’s 282/937 ms CPU observations are not claimed savings.\n\n## Before');
report=report.replace(/All 140 theme\/seed inputs at 256² are traced[\s\S]*?\n\nBrowser:/, 'All 140 inputs are traced on every repeat: [disjoint stage totals](PROFILE.csv), [rejections](REJECTIONS.csv). Shaping repeats noise/priority floods; planning cuts/checks courses; starts repeat walks, storage and statistics. Seed-1 [V8 samples](CPU-SAMPLES.csv) put water substep at 51% in River Valley and 77% in Islands. [M9b tick evidence](SETTLE-TICKS.csv): 1,792–2,816 median final ticks by theme, up to 4,352 ticks and five settles. Wet areas and repairs explain the water tail. Exact early-rejection dependencies are in INTEGRATION; changing budgets or skipping draws can select a different map. [Result-changing proposals](PROPOSALS.md) remain separate and unmeasured.\n\nBrowser:');
writeFileSync(resolve(dir,'REPORT.md'),report);
console.log('Wrote report, complete identity binding and small CSV summaries.');
