import assert from 'node:assert/strict';
import { writeFileSync } from 'node:fs';
import { fixture } from './maps';
import { erupt, DEFAULTS, modelFor, snapshot } from './engine';
import { canonicalSettle } from '../../src/core/sim/prefill';
import { CarveRun, DEFAULTS as CARVE } from './carve/engine';
const river=fixture('river',128),before=canonicalSettle(modelFor(river));river.water=before;
const plan=erupt(river,{...DEFAULTS,mode:'fissure',power:58,seed:76},{origin:59*128+64,path:[{x:64,y:59},{x:83,y:63},{x:104,y:59}]});
const after=canonicalSettle(modelFor(plan.map));
const x=Math.floor(128*.66),upstream=95*128+x;
assert(after.depth[upstream]>before.depth[upstream]+1);
assert.deepEqual(modelFor(plan.map).emitters,modelFor(river).emitters);
const rock=erupt(fixture('plain',128),{...DEFAULTS,power:35,shape:'steep',seed:6},{origin:62*128+68}).map;
const soft=snapshot(rock);soft.lava.fill(0);
const settings={...CARVE,mode:'aim' as const,power:60,seed:18,wander:0,width:4,dry:true,defyGravity:true};
const intent={origin:72*128+28,end:72*128+112},hardRun=new CarveRun(rock,settings,intent),softRun=new CarveRun(soft,settings,intent);
for(let k=0;k<200&&!hardRun.metrics.stable;k++)hardRun.step();
for(let k=0;k<200&&!softRun.metrics.stable;k++)softRun.step();
assert.notDeepEqual(hardRun.path,softRun.path);
const crossed=(r:CarveRun)=>r.path.filter(p=>rock.lava[Math.round(p.y)*128+Math.round(p.x)]>0).length;
assert(crossed(hardRun)<crossed(softRun));
const report={river:{before:before.depth[upstream],after:after.depth[upstream],settled:after.settled,unchangedEmitters:true},carve:{hardLavaStations:crossed(hardRun),softLavaStations:crossed(softRun),hardCut:hardRun.metrics.cut,softCut:softRun.metrics.cut}};
writeFileSync('captures/water-rock-checks.json',JSON.stringify(report,null,2)+'\n');console.log(report);
