import assert from 'node:assert/strict';
import { fixture } from './maps';
import { erupt, DEFAULTS, snapshot, stageMap, liveWater, modelFor, protectedGround, waterRun } from './engine';
import { operation, applyOperation } from './operation';
import { canonicalSettle } from '../../src/core/sim/prefill';
import { performance } from 'node:perf_hooks';
import { writeFileSync, mkdirSync } from 'node:fs';
const checks:Record<string,unknown>={};
const base=fixture('plain',128),intent={origin:64*128+64},settings={...DEFAULTS,seed:891};
const p=erupt(base,settings,intent),again=erupt(base,settings,intent);
assert.deepEqual(p.map,again.map);
assert.notDeepEqual(erupt(base,{...settings,seed:892},intent).map.heights,p.map.heights);
assert.equal(base.heights[intent.origin],3);
assert(p.map.heights.every(v=>Number.isInteger(v)&&v>=0&&v<=22));
assert(p.map.heights.every((v,i)=>v>=base.heights[i]));
assert(p.map.lava.some(v=>v>0));
assert(p.map.fallen.length>0);
checks.determinism=true;
for(const shape of ['steep','broad'] as const)for(const summit of ['auto','peak','crater','caldera'] as const)for(const flows of ['light','heavy'] as const)for(const ridges of [true,false]){
  const r=erupt(base,{...settings,shape,summit,flows,ridges},intent);
  assert(r.map.heights.every(v=>v<=22));assert(r.stats.changed>0);
}
checks.settings=32;
const small=erupt(base,{...settings,power:10},intent),big=erupt(base,{...settings,power:100},intent);assert(big.stats.raised>small.stats.raised);
const caldera=erupt(base,{...settings,power:90,summit:'caldera'},intent).map;
assert(caldera.heights[intent.origin]<Math.max(...caldera.heights)-3);
const overlapping=erupt(p.map,{...settings,power:45},{origin:60*128+82});
assert(overlapping.stats.raised>0);
assert(erupt(base,settings,{origin:0}).stats.changed>0);
assert.throws(()=>erupt(base,settings,{origin:8*128+7}),/Start here/);
const fissure=erupt(base,{...settings,mode:'fissure'},{origin:50*128+35,path:[{x:35,y:50},{x:60,y:65},{x:90,y:55}]});
assert(fissure.anatomy.vents.length>=4);
assert.throws(()=>erupt(base,{...settings,mode:'fissure'},{origin:8*128+2,path:[{x:2,y:8},{x:30,y:8}]}),/Start here/);
const beforeWater=base.water.depth.reduce((a,b)=>a+b,0),live=stageMap(base,p.map,.5);liveWater(base,live);
assert.equal(live.water.depth.reduce((a,b)=>a+b,0),beforeWater);
const dry=waterRun(p.map);let result=dry.advance(2);while(!result)result=dry.advance(2);p.map.water={depth:result.depth,contamination:result.contamination};
assert.deepEqual(p.map.water.depth,canonicalSettle(modelFor(p.map)).depth);
const op=operation(base,p.map,settings,intent,result);
const restored=applyOperation(p.map,op,true);assert.deepEqual(restored,base);
assert.deepEqual(applyOperation(restored,JSON.parse(JSON.stringify(op))),p.map);
const stale=snapshot(base);stale.lava[op.params.lava[0][0]]=1;assert.throws(()=>applyOperation(stale,op),/lava/);
checks.undoReplayAndCanonical=true;
const keep=protectedGround(base);for(let i=0;i<keep.length;i++)if(keep[i])assert.equal(p.map.heights[i],base.heights[i]);
for(const e of p.map.entities)assert.equal(e.z,p.map.heights[e.y*128+e.x]);
assert.equal(p.map.entities.filter(e=>e.template.includes('Source')).length,0);
checks.objectsAndStart=true;
const b256=fixture('plain',256),t=performance.now(),large=erupt(b256,settings,{origin:128*256+128});checks.plan256Ms=Math.round(performance.now()-t);checks.changed256=large.stats.changed;
mkdirSync('captures',{recursive:true});writeFileSync('captures/checks.json',JSON.stringify(checks,null,2)+'\n');console.log(checks);
const smallBase=fixture('plain',32),sampleSettings={...DEFAULTS,power:18,seed:17},sampleIntent={origin:22*32+22},sample=erupt(smallBase,sampleSettings,sampleIntent).map;
const sampleRun=waterRun(sample);let sr=sampleRun.advance(Infinity);while(!sr)sr=sampleRun.advance(Infinity);sample.water={depth:sr.depth,contamination:sr.contamination};
mkdirSync('samples',{recursive:true});writeFileSync('samples/vent-32.json',JSON.stringify({format:1,base:smallBase,eruptionBase:smallBase,operation:operation(smallBase,sample,sampleSettings,sampleIntent,sr)},(_k,v)=>ArrayBuffer.isView(v)?Array.from(v as any):v));
