// Builds the Rust water (PLAN §20 D381, D442): `npx tsx tools/rust/build.ts [--check] [--native]`.
//
// - The WebAssembly every engine and Node run, embedded in src/core/sim/waterWasm.ts (committed, so the app,
//   the tests and every checkout work without Rust). Source paths inside it are written with forward
//   slashes, so Windows and Linux build the same bytes. The Wasm guard (tools/rust/guard.mjs) checks it.
// - With --native, also the native batch binary (rust/target/release/water-batch), which src/core/sim/native.ts
//   runs for batch jobs.
// - With --check, nothing is written: it fails when the committed Wasm differs from a fresh build (CI's
//   `rust` job), so the committed module always matches rust/.
//
// Cargo runs with -j 4 by default (DGM_CARGO_JOBS).

import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { assertClean } from "./guard.mjs";

const ROOT = resolve(import.meta.dirname, "../..");
const RUST = join(ROOT, "rust");
const OUT = join(ROOT, "src/core/sim/waterWasm.ts");
const JOBS = String(process.env.DGM_CARGO_JOBS ?? 4);
const CHECK = process.argv.includes("--check");

function rsFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((d) =>
    d.name === "target" ? [] : d.isDirectory() ? rsFiles(join(dir, d.name)) : d.name.endsWith(".rs") ? [join(dir, d.name)] : [],
  );
}

// every source file's path as cargo passes it (relative to rust/, the OS's separators) → forward slashes
const remaps = rsFiles(RUST).map((f) => {
  const rel = relative(RUST, f);
  return `--remap-path-prefix=${rel}=${rel.replaceAll("\\", "/")}`;
});
execFileSync("cargo", ["build", "--release", "-j", JOBS, "-p", "water", "--lib", "--target", "wasm32-unknown-unknown", "--target-dir", "target/embed"], {
  cwd: RUST,
  stdio: ["ignore", "inherit", "inherit"],
  env: { ...process.env, CARGO_ENCODED_RUSTFLAGS: remaps.join("\x1f") },
  windowsHide: true,
});
const wasm = readFileSync(join(RUST, "target/embed/wasm32-unknown-unknown/release/water.wasm"));
assertClean("wasm", wasm);
const imports = WebAssembly.Module.imports(new WebAssembly.Module(wasm));
if (imports.length) throw new Error(`the water's Wasm must import nothing: ${JSON.stringify(imports)}`);

const b64 = wasm.toString("base64");
const lines = b64.match(/.{1,120}/g) ?? [];
const text =
  "// Generated by tools/rust/build.ts from rust/water (Rust 1.90.0, wasm32-unknown-unknown): do not edit.\n" +
  "// CI's `rust` job rebuilds it and fails when it differs (PLAN §20 D381, D442).\n" +
  `// ${wasm.length} bytes.\n` +
  "export const WATER_WASM =\n" +
  lines.map((l, k) => `  "${l}"${k < lines.length - 1 ? " +" : ";"}`).join("\n") +
  "\n";

if (CHECK) {
  let committed = "";
  try {
    committed = readFileSync(OUT, "utf8").replaceAll("\r\n", "\n");
  } catch {
    // missing: reported below
  }
  if (committed !== text) {
    console.error("src/core/sim/waterWasm.ts differs from a fresh build of rust/water: run `npx tsx tools/rust/build.ts` and commit it");
    process.exit(1);
  }
  console.log(`src/core/sim/waterWasm.ts matches a fresh build (${wasm.length} bytes)`);
} else {
  writeFileSync(OUT, text);
  console.log(`wrote src/core/sim/waterWasm.ts (${wasm.length} bytes of Wasm)`);
}

if (process.argv.includes("--native")) {
  execFileSync("cargo", ["build", "--release", "-j", JOBS, "-p", "water", "--bin", "water-batch"], { cwd: RUST, stdio: ["ignore", "inherit", "inherit"], windowsHide: true });
  console.log("built rust/target/release/water-batch");
}
