// Builds the Rust ports (PLAN §20 D381, D442): `npx tsx tools/rust/build.ts [--check] [--native]`.
//
// - The WebAssembly every engine and Node run, embedded in TypeScript (committed, so the app, the tests and
//   every checkout work without Rust): the water's in src/core/sim/waterWasm.ts, the forces' in
//   src/core/forces/rust/forcesWasm.ts. Source paths inside them are written with forward slashes, so Windows
//   and Linux build the same bytes. The Wasm guard (tools/rust/guard.mjs) checks each.
// - With --native, also the native batch binaries (rust/target/release/water-batch, which
//   tools/rust/native-water.ts runs for batch jobs, and forces-batch, the forces' identity check's).
// - With --check, nothing is written: it fails when a committed Wasm differs from a fresh build (CI's
//   `rust` job), so the committed modules always match rust/.
//
// Cargo runs with -j 4 by default (DGM_CARGO_JOBS).

import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { assertClean } from "./guard.mjs";

const ROOT = resolve(import.meta.dirname, "../..");
const RUST = join(ROOT, "rust");
const JOBS = String(process.env.DGM_CARGO_JOBS ?? 4);
const CHECK = process.argv.includes("--check");

function rsFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((d) =>
    d.name === "target" ? [] : d.isDirectory() ? rsFiles(join(dir, d.name)) : d.name.endsWith(".rs") ? [join(dir, d.name)] : [],
  );
}

// every source file's path as cargo passes it (relative to rust/, the OS's separators) → forward slashes
const remaps = rsFiles(RUST).map((f) => {
  const rel = relative(RUST, f);
  return `--remap-path-prefix=${rel}=${rel.replaceAll("\\", "/")}`;
});
/** Each embedded module: its crate, the library cargo builds, the file and the constant it is written to. */
const EMBEDS = [
  { pkg: "water", lib: "water", out: "src/core/sim/waterWasm.ts", name: "WATER_WASM" },
  { pkg: "forces", lib: "forces", out: "src/core/forces/rust/forcesWasm.ts", name: "FORCES_WASM" },
];
let stale = false;
for (const { pkg, lib, out, name } of EMBEDS) {
  execFileSync("cargo", ["build", "--release", "-j", JOBS, "-p", pkg, "--lib", "--target", "wasm32-unknown-unknown", "--target-dir", "target/embed"], {
    cwd: RUST,
    stdio: ["ignore", "inherit", "inherit"],
    env: { ...process.env, CARGO_ENCODED_RUSTFLAGS: remaps.join("\x1f") },
    windowsHide: true,
  });
  const wasm = readFileSync(join(RUST, `target/embed/wasm32-unknown-unknown/release/${lib}.wasm`));
  assertClean("wasm", wasm);
  const imports = WebAssembly.Module.imports(new WebAssembly.Module(wasm));
  if (imports.length) throw new Error(`rust/${pkg}'s Wasm must import nothing: ${JSON.stringify(imports)}`);

  const b64 = wasm.toString("base64");
  const lines = b64.match(/.{1,120}/g) ?? [];
  const text =
    `// Generated by tools/rust/build.ts from rust/${pkg} (Rust 1.90.0, wasm32-unknown-unknown): do not edit.\n` +
    "// CI's `rust` job rebuilds it and fails when it differs (PLAN §20 D381, D442).\n" +
    `// ${wasm.length} bytes.\n` +
    // (lines in a list, never a chain of +: thousands of them nest too deep for a parser)
    `export const ${name} = [\n` +
    lines.map((l) => `  "${l}",`).join("\n") +
    '\n].join("");\n';
  const file = join(ROOT, out);

  if (CHECK) {
    let committed = "";
    try {
      committed = readFileSync(file, "utf8").replaceAll("\r\n", "\n");
    } catch {
      // missing: reported below
    }
    if (committed !== text) {
      console.error(`${out} differs from a fresh build of rust/${pkg}: run \`npx tsx tools/rust/build.ts\` and commit it`);
      stale = true;
    } else console.log(`${out} matches a fresh build (${wasm.length} bytes)`);
  } else {
    writeFileSync(file, text);
    console.log(`wrote ${out} (${wasm.length} bytes of Wasm)`);
  }
}
if (stale) process.exit(1);

if (process.argv.includes("--native")) {
  for (const [pkg, bin] of [["water", "water-batch"], ["forces", "forces-batch"]])
    execFileSync("cargo", ["build", "--release", "-j", JOBS, "-p", pkg, "--bin", bin], { cwd: RUST, stdio: ["ignore", "inherit", "inherit"], windowsHide: true });
  console.log("built rust/target/release/water-batch and forces-batch");
}
