// Writes rust/checks/src/tables.rs: the data and constants the checks read from modules outside the checks (the
// footprints, the starting-logs floor, the calibrated targets, the difficulty rules, the water's constants, the
// emitters, the objects' names), taken from the TypeScript itself so the two cannot drift. `--check` fails when
// the committed file differs (tools/rust/check.ts runs it).
//
//   npx tsx tools/rust/checks-tables.ts [--check]

import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { FOOTPRINTS } from "../../src/core/format/footprints";
import * as logFloor from "../../src/core/data/logFloor";
import * as cal from "../../src/core/gen/calibrated";
import * as spec from "../../src/core/spec/mapspec";
import * as water from "../../src/core/sim/water";
import * as world from "../../src/core/format/world";
import * as objects from "../../src/core/features/objects";
import * as model from "../../src/core/sim/model";
import { NAMES } from "../../src/core/doc/describeTile";
import { REQUIRED } from "../../src/core/validate/checks";
import { EXTRA_BANDS } from "../../src/core/validate/playability";
import { WALK_BLOCKERS } from "../../src/core/analysis/walk";

const PATH = join(resolve(import.meta.dirname, "../.."), "rust/checks/src/tables.rs");

const f = (v: number): string => {
  if (!Number.isFinite(v)) throw new Error(`non-finite constant ${v}`);
  const s = String(v);
  return /[.e]/.test(s) ? s.replace(/^(-?\d+)e/, "$1.0e") : `${s}.0`;
};
const str = (s: string): string => JSON.stringify(s);
const BELOW = ["ground", "groundOrStackable", "any", "air", "stackable"];

/** The text of tables.rs. */
export function checksTables(): string {
  const out: string[] = [];
  out.push("// Generated by tools/rust/checks-tables.ts from the TypeScript (footprints.json, log-floor.json, calibrated.ts,");
  out.push("// mapspec.ts, water.ts, world.ts, objects.ts, model.ts, describeTile.ts, checks.ts, playability.ts, walk.ts).");
  out.push("// Do not edit: rerun it.");
  out.push("#![allow(dead_code)]");
  out.push("");
  out.push("pub struct Block { pub x: i32, pub y: i32, pub z: i32, pub below: u8, pub flags: u32, pub stackable: bool, pub occupy_all_below: bool }");
  out.push("pub struct Footprint { pub size: [i32; 3], pub flippable: bool, pub blocks: &'static [Block] }");
  out.push(`/// Matter below, in the order of \`MatterBelow\`: ${BELOW.join(", ")}.`);
  BELOW.forEach((b, k) => out.push(`pub const BELOW_${b.replace(/[A-Z]/g, (c) => `_${c}`).toUpperCase()}: u8 = ${k};`));
  out.push("pub fn footprint(template: &str) -> Option<&'static Footprint> {");
  out.push("    match template {");
  for (const name of Object.keys(FOOTPRINTS).sort()) {
    const fp = FOOTPRINTS[name];
    const blocks = (fp.blocks as unknown as [number, number, number, string, number, number, number][])
      .map(([x, y, z, below, flags, stack, oab]) => {
        const b = BELOW.indexOf(below);
        if (b < 0) throw new Error(`unknown matter below ${below}`);
        return `Block { x: ${x}, y: ${y}, z: ${z}, below: ${b}, flags: ${flags}, stackable: ${!!stack}, occupy_all_below: ${!!oab} }`;
      })
      .join(", ");
    out.push(`        ${str(name)} => Some(&Footprint { size: [${fp.size.join(", ")}], flippable: ${fp.flippable}, blocks: &[${blocks}] }),`);
  }
  out.push("        _ => None,");
  out.push("    }");
  out.push("}");
  out.push("");
  out.push(`pub const LOG_FLOOR: f64 = ${f(logFloor.LOG_FLOOR)};`);
  out.push(`pub const LOG_FLOOR_WALK: f64 = ${f(logFloor.LOG_FLOOR_WALK)};`);
  out.push("pub fn logs_per_tree(template: &str) -> Option<f64> {");
  out.push("    match template {");
  for (const [k, v] of Object.entries(logFloor.LOGS_PER_TREE_SPECIES as Record<string, number>)) out.push(`        ${str(k)} => Some(${f(v)}),`);
  out.push("        _ => None,");
  out.push("    }");
  out.push("}");
  out.push("/// `DEAD_TREES_KEEP_LOGS[template] === false`.");
  out.push("pub fn dead_tree_loses_logs(template: &str) -> bool {");
  const loses = Object.entries(logFloor.DEAD_TREES_KEEP_LOGS as Record<string, boolean>)
    .filter(([, v]) => v === false)
    .map(([k]) => str(k));
  out.push(loses.length ? `    matches!(template, ${loses.join(" | ")})` : "    let _ = template;\n    false");
  out.push("}");
  out.push("");
  out.push("/// Difficulties in the order easy, normal, hard.");
  out.push(`pub const DIFFICULTIES: [&str; 3] = ["easy", "normal", "hard"];`);
  const D = ["easy", "normal", "hard"] as const;
  out.push("/// DIFFICULTY_RULES: waterWithin, woodWithin20, bushesWithin20, badwaterWithin, ruinsWithin.");
  out.push(
    `pub const DIFFICULTY_RULES: [[f64; 5]; 3] = [${D.map((d) => {
      const r = spec.DIFFICULTY_RULES[d];
      return `[${[r.waterWithin, r.woodWithin20, r.bushesWithin20, r.badwaterWithin, r.ruinsWithin].map(f).join(", ")}]`;
    }).join(", ")}];`,
  );
  out.push(`/// DROUGHT: days, colony.`);
  out.push(`pub const DROUGHT: [[f64; 2]; 3] = [${D.map((d) => `[${f(cal.DROUGHT[d].days)}, ${f(cal.DROUGHT[d].colony)}]`).join(", ")}];`);
  out.push(`pub const RESERVOIR_NEEDED: [f64; 3] = [${D.map((d) => f(cal.reservoirNeeded(d))).join(", ")}];`);
  const kv = (name: string, o: Record<string, number>) => {
    out.push(`pub fn ${name}(key: &str) -> Option<f64> {`);
    out.push("    match key {");
    for (const [k, v] of Object.entries(o)) out.push(`        ${str(k)} => Some(${f(v)}),`);
    out.push("        _ => None,");
    out.push("    }");
    out.push("}");
  };
  kv("reach_min", cal.REACH_MIN as Record<string, number>);
  kv("reserve", cal.RESERVE as Record<string, number>);
  out.push(`pub const LIVING_SHARE: [f64; 2] = [${cal.OFFICIAL_LAYOUT.livingShare.map(f).join(", ")}];`);
  out.push(`pub const SIZE_ANCHORS: [f64; 4] = [${cal.SIZE_ANCHORS.map(f).join(", ")}];`);
  const density = cal.DENSITY as unknown as Record<string, number[]>;
  const spread = cal.SPREAD as unknown as Record<string, number[]>;
  for (const k of ["scrap_per_1k_tiles", "trees_per_10k", "bushes_per_10k"]) out.push(`pub const DENSITY_${k.toUpperCase()}: [f64; 4] = [${density[k].map(f).join(", ")}];`);
  for (const k of ["trees", "bushes", "scrap"]) out.push(`pub const SPREAD_${k.toUpperCase()}: [f64; 2] = [${spread[k].map(f).join(", ")}];`);
  out.push(`pub const SMALL_MAP: f64 = ${f(spec.SMALL_MAP)};`);
  out.push(`pub const SETTLE_DAYS: f64 = ${f(water.SETTLE_DAYS)};`);
  out.push(`pub const TICKS_PER_DAY: f64 = ${f(water.TICKS_PER_DAY)};`);
  out.push(`pub const DT: f64 = ${f(water.DT)};`);
  out.push("/// sim/model.ts EMITTERS: local tiles, contamination, runs at map start, seep.");
  out.push("pub struct EmitterRule { pub tiles: &'static [(i64, i64)], pub contamination: f64, pub runs: bool, pub seep: bool }");
  out.push("pub fn emitter_rule(template: &str) -> Option<&'static EmitterRule> {");
  out.push("    match template {");
  for (const [k, r] of Object.entries(model.EMITTERS as Record<string, { tiles: [number, number][]; contamination: number; runs: boolean; seep?: boolean }>))
    out.push(`        ${str(k)} => Some(&EmitterRule { tiles: &[${r.tiles.map(([x, y]) => `(${x}, ${y})`).join(", ")}], contamination: ${f(r.contamination)}, runs: ${r.runs}, seep: ${!!r.seep} }),`);
  out.push("        _ => None,");
  out.push("    }");
  out.push("}");
  out.push(`pub const MAX_STRENGTH_PER_TILE: f64 = ${f(model.MAX_STRENGTH_PER_TILE)};`);
  out.push(`pub const GAME_VERSION: &str = ${str(world.GAME_VERSION)};`);
  out.push(`pub const GAME_MAX_HEIGHT: f64 = ${f(world.GAME_MAX_HEIGHT)};`);
  out.push(`pub const EDITOR_MAX_HEIGHT: f64 = ${f(world.EDITOR_MAX_HEIGHT)};`);
  out.push(`pub const MAX_OBJECT_Z: i64 = ${world.MAX_OBJECT_Z};`);
  out.push("/// features/objects.ts OBJECT_NAMES: a map object's name by its kind.");
  out.push("pub fn object_name(kind: &str) -> Option<&'static str> {");
  out.push("    match kind {");
  for (const [k, v] of Object.entries(objects.OBJECT_NAMES as Record<string, string>)) out.push(`        ${str(k)} => Some(${str(v)}),`);
  out.push("        _ => None,");
  out.push("    }");
  out.push("}");
  out.push("/// analysis/walk.ts WALK_BLOCKERS: the objects a beaver never walks through.");
  out.push("pub fn walk_blocker(template: &str) -> bool {");
  out.push(`    matches!(template, ${[...WALK_BLOCKERS].map(str).join(" | ")})`);
  out.push("}");
  out.push("/// validate/playability.ts EXTRA_BANDS: a map object's distance band from the start (lo, hi, scaled with the map).");
  out.push("pub fn extra_band(kind: &str) -> Option<(f64, f64, bool)> {");
  out.push("    match kind {");
  for (const [k, b] of Object.entries(EXTRA_BANDS)) out.push(`        ${str(k)} => Some((${f(b.lo)}, ${b.hi === Infinity ? "f64::INFINITY" : f(b.hi)}, ${b.scaled})),`);
  out.push("        _ => None,");
  out.push("    }");
  out.push("}");
  const comps = [...new Set(Object.values(REQUIRED).flat())];
  out.push("/// validate/checks.ts REQUIRED's components, in order of first use: a component's bit in `Entity::comps`.");
  out.push(`pub const COMP_NAMES: [&str; ${comps.length}] = [${comps.map(str).join(", ")}];`);
  out.push("/// validate/checks.ts REQUIRED: the components whose absence crashes the load, as indices into COMP_NAMES.");
  out.push("pub fn required(template: &str) -> &'static [usize] {");
  out.push("    match template {");
  for (const [k, v] of Object.entries(REQUIRED)) out.push(`        ${str(k)} => &[${v.map((c) => comps.indexOf(c)).join(", ")}],`);
  out.push("        _ => &[],");
  out.push("    }");
  out.push("}");
  out.push("/// doc/describeTile.ts NAMES: the game's name of an object, where it has its own.");
  out.push("pub fn game_name(template: &str) -> Option<&'static str> {");
  out.push("    match template {");
  for (const [k, v] of Object.entries(NAMES)) out.push(`        ${str(k)} => Some(${str(v)}),`);
  out.push("        _ => None,");
  out.push("    }");
  out.push("}");
  out.push("");
  return out.join("\n");
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  const text = checksTables();
  if (process.argv.includes("--check")) {
    if (readFileSync(PATH, "utf8").replace(/\r\n/g, "\n") !== text) {
      console.error("rust/checks/src/tables.rs is stale: run `npx tsx tools/rust/checks-tables.ts`");
      process.exit(1);
    }
    console.log("rust/checks/src/tables.rs matches the TypeScript");
  } else {
    writeFileSync(PATH, text);
    console.log(`wrote ${PATH}`);
  }
}
