import {launchOptions} from './browser-options.mjs';
// Adapted from rust-water/browser.mjs: one worker/retained Wasm arena per engine.
import {createServer} from 'node:http';
import {readFileSync,existsSync,appendFileSync,writeFileSync} from 'node:fs';
import {resolve,sep} from 'node:path';
import {createRequire} from 'node:module';
import {cpus,freemem} from 'node:os';
import {loadSampler} from './load.mjs';
import {HERE,LOCAL,deps,arg,json,hash} from './common.mjs';
const pw=createRequire(resolve(process.env.DGM_BROWSER_DEPS??resolve(LOCAL,'browser-deps'),'package.json'))('playwright');
const server=createServer((req,res)=>{if(req.method==='POST'&&/^\/failure-[a-z0-9-]+\.(?:input|expected|actual)\.bin$/.test(req.url)){const pieces=[];req.on('data',b=>pieces.push(b));req.on('end',()=>{writeFileSync(resolve(LOCAL,req.url.slice(1)),Buffer.concat(pieces));res.end('saved');});return;}const path=resolve(LOCAL,decodeURIComponent(new URL(req.url,'http://localhost').pathname).slice(1));if(!path.startsWith(LOCAL+sep)||!existsSync(path)){res.writeHead(404).end();return;}res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript':path.endsWith('.wasm')?'application/wasm':'application/octet-stream');res.end(readFileSync(path));});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port+'/';
const build=JSON.parse(readFileSync(resolve(LOCAL,'build.json'))),fingerprint=hash(Buffer.concat([process.argv.includes('--bench')?'forces-bench.wasm':'forces.wasm','worker.js'].map(n=>readFileSync(resolve(LOCAL,n))))),sampler=loadSampler(),rows=[];
try{for(const engine of arg('engines','chromium,firefox,webkit').split(',')){const firefox=engine==='firefox'?process.env.DGM_FIREFOX??resolve(LOCAL,'firefox-optimized/firefox.exe'):undefined;if(engine==='firefox'&&!existsSync(firefox))throw Error('Set DGM_FIREFOX to a standard Firefox executable for correctness checks.');const browser=await pw[engine].launch(launchOptions(engine));try{const page=await browser.newPage();page.setDefaultTimeout(1800000);await page.goto(base+'worker.js');await page.evaluate(url=>{window.taskWorker=new Worker(url,{type:'module'});},base+'worker.js?engine='+engine+(process.argv.includes('--bench')?'&bench=1':''));
const send=d=>page.evaluate(d=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Force worker timed out '+JSON.stringify(d))),1800000);window.taskWorker.onmessage=e=>{clearTimeout(timer);e.data.ok?resolve(e.data):reject(Error(JSON.stringify(e.data)));};window.taskWorker.onerror=e=>{clearTimeout(timer);reject(Error(e.message));};window.taskWorker.postMessage(d);}),d);
for(const verb of arg('verbs','footprint,craterize,erupt,quake').split(','))for(const size of arg('sizes','256').split(',').map(Number))for(let k=Number(arg('start','0'));k<Number(arg('start','0'))+Number(arg('count','6'));k++){
 const d={verb,size,k,random:process.argv.includes('--random'),bench:process.argv.includes('--bench'),exports:process.argv.includes('--exports'),reps:Number(arg('reps','3'))};sampler.reset();if(d.bench)await sampler.observe();let result;try{result=await send(d);}catch(error){const api=deps(resolve(LOCAL,'api.cjs')),job=(d.random?api.randomJob:api.job)(verb,size,k),name=`failure-${arg('name','smoke')}-${engine}-${verb}-${size}-${k}`;writeFileSync(resolve(LOCAL,name+'.input.bin'),api.encode(job,false));json(name+'.json',{descriptor:d,engine,version:browser.version(),fingerprint,error:String(error)});throw error;}if(d.bench)await sampler.observe();const row={engine,version:browser.version(),...result,fingerprint,load:{...sampler.summary(),freeMemory:freemem()}};rows.push(row);appendFileSync(resolve(LOCAL,'browser-'+arg('name','smoke')+'.jsonl'),JSON.stringify(row)+'\n');if(k%10===0)console.log(engine,verb,size,k,'PASS');}
}finally{await browser.close();}}json('browser-'+arg('name','smoke')+'.json',{rows,build,machine:cpus()[0].model,logicalCores:cpus().length});}finally{sampler.stop();server.close();}
