import {readFileSync,writeFileSync,appendFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
import {HERE,LOCAL,deps,arg,hash,json} from './common.mjs';
import {nativeFixtures} from './native-fixtures.mjs';
const fingerprint=hash(Buffer.concat(['forces.wasm','api.cjs','target/release/forces-batch.exe'].map(n=>readFileSync(resolve(LOCAL,n)))));
const api=deps(resolve(LOCAL,'api.cjs')),run=await api.bridge(readFileSync(resolve(LOCAL,'forces.wasm'))),rows=[];
let current;
const exports=process.argv.includes('--exports');
const server=process.argv.includes('--server')?nativeFixtures(exports):null;if(exports&&!server)throw Error('--exports requires --server');
function diff(a,b,path=''){if(Object.is(a,b))return null;if(!a||!b||typeof a!=='object'||typeof b!=='object')return {path,a,b};if(Object.keys(a).sort().join('|')!==Object.keys(b).sort().join('|'))return {path,keysA:Object.keys(a),keysB:Object.keys(b)};for(const k of Object.keys(a)){const d=diff(a[k],b[k],path+'.'+k);if(d)return d;}return null;}
try{for(const verb of arg('verbs',arg('verb','craterize')).split(','))for(const size of arg('sizes','128,256,512').split(',').map(Number))for(let k=Number(arg('start','0'));k<Number(arg('start','0'))+Number(arg('count','6'));k++){
 const j=(process.argv.includes('--random')?api.randomJob:api.job)(verb,size,k);current={verb,size,k,j};const input=api.encode(j,false),expectedResult=api.referenceWithRecord(j),expected=api.encode(expectedResult),task=run.create(j);let actual,wasmExport;const expectedExport=exports&&verb!=='footprint'&&!expectedResult.error?api.exportedBytes(j,expectedResult.map):null;try{try{task.plan();}catch(error){if(!api.decode(expected).error)throw error;}actual=task.pack();if(expectedResult.error){const m=task.map;if(!Buffer.from(api.encode([m.heights,m.lava,m.water,m.rockLayers,m.keep])).equals(Buffer.from(api.encode([j.map.heights,j.map.lava,j.map.water,j.map.rockLayers,j.keep]))))throw Error("Refusal changed retained map");}if(!api.decode(expected).error){const result=api.typedResult(task,j,api.F),direct=api.encode(result);if(expectedExport){wasmExport=api.exportedBytes(j,result.map);if(!Buffer.from(expectedExport).equals(wasmExport))throw Error("Wasm export bytes");}if(!Buffer.from(actual).equals(Buffer.from(direct))){console.log(diff(api.decode(actual),api.decode(direct)));throw Error("Direct typed result differs from diagnostic pack");}}}finally{task.dispose();}
 if(!Buffer.from(expected).equals(Buffer.from(actual))){writeFileSync(resolve(LOCAL,'expected.bin'),expected);writeFileSync(resolve(LOCAL,'actual.bin'),actual);writeFileSync(resolve(LOCAL,'failure-input.bin'),input);console.log({verb,size,k,diff:diff(api.decode(expected),api.decode(actual))});throw Error('Identity mismatch');}
 let native;if(server)native=await server.execute(input);else{writeFileSync(resolve(LOCAL,'input-'+arg('name','smoke')+'.bin'),input);execFileSync(resolve(LOCAL,'target/release/forces-batch.exe'),[resolve(LOCAL,'input-'+arg('name','smoke')+'.bin'),resolve(LOCAL,'output-'+arg('name','smoke')+'.bin')]);native=readFileSync(resolve(LOCAL,'output-'+arg('name','smoke')+'.bin'));}const orderedEntities=exports?api.decode(native.entities):null;native=exports?native.bytes:native;if(!Buffer.from(expected).equals(native))throw Error('Native identity');if(expectedExport){const result=api.decode(native),output=api.exportedBytes(j,result.map,orderedEntities);if(!Buffer.from(expectedExport).equals(output)){writeFileSync(resolve(LOCAL,'expected.timber'),expectedExport);writeFileSync(resolve(LOCAL,'actual.timber'),output);throw Error('Native export bytes');}}const row={verb,size,k,random:process.argv.includes('--random'),error:expectedResult.error??null,fingerprint,sha256:hash(expected),exportSha256:expectedExport?hash(expectedExport):null};rows.push(row);appendFileSync(resolve(LOCAL,'checks-'+arg('name','smoke')+'.jsonl'),JSON.stringify(row)+'\n');if(k%10===0)console.log(verb,size,k,'PASS');
}json('checks-'+arg('name','smoke')+'.json',rows);}catch(error){if(current){const prefix='failure-'+arg('name','smoke')+'-'+current.verb+'-'+current.size+'-'+current.k;writeFileSync(resolve(LOCAL,prefix+'.input.bin'),api.encode(current.j,false));json(prefix+'.json',{verb:current.verb,size:current.size,k:current.k,fingerprint,error:String(error)});console.error('Exact reproduction:',prefix);}throw error;}finally{server?.close();}
