import {launchOptions} from './browser-options.mjs';
import {readFileSync} from 'node:fs';
import {resolve,sep} from 'node:path';
import {createServer} from 'node:http';
import {createRequire} from 'node:module';
import {LOCAL,deps,json,hash} from './common.mjs';
import {nativeFixtures} from './native-fixtures.mjs';
const api=deps(resolve(LOCAL,'api.cjs')),wasm=readFileSync(resolve(LOCAL,'forces.wasm')),native=nativeFixtures();
function cases(api){
 const jobs=[];const q=api.job('quake',48,0);q.map=api.fixture('plain',48);q.settings={...api.QUAKE_DEFAULTS,mode:'lift',power:60,scarp:'sheer',seed:1};q.intent={side:1,path:[{x:25.2,y:25.4},{x:45.2,y:25.4}]};jobs.push({name:'quake-zero-length-resampled-segment',job:q});
 for(const verb of ['craterize','erupt','quake','carve','glaciate']){
  const power=api.job(verb,128,0);power.settings.power=101;jobs.push({name:verb+'-power-refusal',job:power});
  const floor=api.job(verb,128,0);floor.settings.power=0;floor.settings.floor=22;jobs.push({name:verb+'-zero-power-floor',job:floor});
 }
 return jobs;
}
function check(api,run,j){const expected=api.encode(api.referenceWithRecord(j)),task=run.create(j);let actual,direct;try{try{task.plan();}catch(error){if(!api.decode(expected).error)throw error;}actual=task.pack();if(!api.decode(expected).error)direct=api.encode(api.typedResult(task,j));}finally{task.dispose();}const same=(a,b)=>a.length===b.length&&a.every((v,i)=>v===b[i]);if(!same(expected,actual)||direct&&!same(expected,direct)){const at=expected.findIndex((v,i)=>v!==actual[i]),nanBits=(v)=>{const b=new ArrayBuffer(8);new DataView(b).setFloat64(0,v,true);return Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join('');};throw Error('Edge case byte mismatch '+JSON.stringify({verb:j.verb,at,expected:Array.from(expected.slice(at-8,at+8)),actual:Array.from(actual.slice(at-8,at+8)),directMatches:direct&&same(expected,direct),expectedFault:api.referenceWithRecord(j).fault?.segments.map(s=>({dx:nanBits(s.dx),dy:nanBits(s.dy)})),actualFault:api.decode(actual).fault?.segments.map(s=>({dx:nanBits(s.dx),dy:nanBits(s.dy)}))}));};return expected;}
const rows=[];try{const run=await api.bridge(wasm);for(const {name,job} of cases(api)){const expected=check(api,run,job),actual=await native.execute(api.encode(job));if(!Buffer.from(expected).equals(actual))throw Error('Native edge '+name);rows.push({target:'native/node-wasm',name,sha256:hash(expected)});}}finally{native.close();}
const server=createServer((req,res)=>{const path=resolve(LOCAL,new URL(req.url,'http://localhost').pathname.slice(1));if(!path.startsWith(LOCAL+sep)){res.writeHead(404).end();return;}try{res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript':'application/wasm');res.end(readFileSync(path));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const pw=createRequire(resolve(process.env.DGM_BROWSER_DEPS??resolve(LOCAL,'browser-deps'),'package.json'))('playwright');try{for(const engine of ['chromium','firefox','webkit']){const browser=await pw[engine].launch(launchOptions(engine));try{const page=await browser.newPage();await page.goto(url+'/api.js');const results=await page.evaluate(async({url,casesSource,checkSource})=>{const api=await import(url+'/api.js'),run=await api.bridge(await(await fetch(url+'/forces.wasm')).arrayBuffer()),cases=eval('('+casesSource+')'),check=eval('('+checkSource+')'),rows=[];for(const {name,job} of cases(api)){const expected=check(api,run,job),bytes=new Uint8Array(await crypto.subtle.digest('SHA-256',expected));rows.push({name,sha256:Array.from(bytes,v=>v.toString(16).padStart(2,'0')).join('')});}return rows;},{url,casesSource:cases.toString(),checkSource:check.toString()});for(const r of results){if(r.sha256!==rows.find(v=>v.name===r.name).sha256)throw Error('Engine edge '+engine+'/'+r.name);rows.push({target:engine,...r});}console.log(engine,results.length,'edge cases PASS');}finally{await browser.close();}}}finally{server.close();}json('edge-cases.json',{status:'pass',wasmSha256:hash(wasm),rows});
