// Round 3: separate adapter completeness from the full statistical corpus.
import {readFileSync,writeFileSync,existsSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {HERE,ROOT,LOCAL,hash} from './common.mjs';
import {portableSha256,guardSha256} from './shared-math.mjs';
import {FORCES,SIZES,REQUIRED_COUNTS,validateCounts} from './acceptance.mjs';
const read=name=>existsSync(resolve(LOCAL,name))?JSON.parse(readFileSync(resolve(LOCAL,name))):null;
const digest=name=>existsSync(resolve(LOCAL,name))?hash(readFileSync(resolve(LOCAL,name))):null;
const build=read('build.json'),math=read('ir.json'),matrix=read('identity-matrix.json'),cross=read('cross-engine.json'),machine=read('pilot-machine.json');
const baseline=JSON.parse(readFileSync(resolve(HERE,'baseline-check.json')));
const nativeFingerprint=hash(Buffer.concat(['forces.wasm','api.cjs','target/release/forces-batch.exe'].map(n=>readFileSync(resolve(LOCAL,n))))),browserFingerprint=hash(Buffer.concat(['forces.wasm','worker.js'].map(n=>readFileSync(resolve(LOCAL,n)))));
const current=new Map();
for(const name of readdirSync(LOCAL).filter(n=>/^(checks|browser)-matrix-.*\.jsonl$/.test(n)))for(const line of readFileSync(resolve(LOCAL,name),'utf8').split(/\r?\n/)){
 if(!line)continue;let r;try{r=JSON.parse(line);}catch{continue;}
 const native=name.startsWith('checks-');if(r.fingerprint!==(native?nativeFingerprint:browserFingerprint)||!native&&r.ok!==true)continue;
 const id=native?`${r.verb}/${r.size}/${r.k}/random`:r.id,key=(native?'native':r.engine)+'/'+id;
 if(current.has(key)&&current.get(key).sha256!==r.sha256)throw Error('Conflicting checkpoint '+key);current.set(key,r);
}
const checks=[...current].filter(([k])=>k.startsWith('native/')).map(([,r])=>r),browsers=[...current].filter(([k])=>!k.startsWith('native/')).map(([,r])=>r),counts={};
for(const r of checks)for(const target of ['native','node-wasm'])counts[`${target}/${r.verb}/${r.size}`]=(counts[`${target}/${r.verb}/${r.size}`]??0)+1;
for(const r of browsers){const [verb,size]=r.id.split('/');counts[`${r.engine}/${verb}/${size}`]=(counts[`${r.engine}/${verb}/${size}`]??0)+1;}
const requiredFields={craterize:['raw','map','literal','arrival','total'],erupt:['raw','map','literal','heat','flows','total'],quake:['raw','map','literal','arrival','source','dx','dy','extras','finalWater','total'],carve:['raw','map','literal','changes','heads','lengths','rawChanges','stepMetrics','stepObjectChanges','initialEntities','oxbows','edgeLeaks','oxbowBasin','closure','retained','unleashedId','badwater','total'],glaciate:['raw','map','literal','arrival','mask','floor','nearest','stream','fan','retained','basins','hanging','joins','finished','total']};
const recordCoverage={},exportCoverage={};
for(const target of Object.keys(REQUIRED_COUNTS))for(const verb of FORCES.filter(v=>v!=='footprint'))for(const size of SIZES){
 const rows=target==='native'||target==='node-wasm'?checks.filter(r=>r.verb===verb&&r.size===size):browsers.filter(r=>r.engine===target&&r.id.startsWith(`${verb}/${size}/`));
 const accepted=rows.filter(r=>!r.error),key=`${target}/${verb}/${size}`;
 recordCoverage[key]=accepted.filter(r=>r.typedRecordsChecked===true&&requiredFields[verb].every(k=>r.recordFields?.includes(k))).length;
 exportCoverage[key]=accepted.filter(r=>r.productWriterChecked===true&&/^[a-f0-9]{64}$/.test(r.exportSha256??'')).length;
}
const recordsPass=Object.values(recordCoverage).every(n=>n>0),exportsPass=Object.values(exportCoverage).every(n=>n>0);
let countsPass=false;try{validateCounts(checks,browsers);countsPass=matrix?.pilot===false&&matrix.status==='pass'&&cross?.status==='pass'&&cross.checksSha256===digest('checks-random-final.json')&&cross.browserSha256===digest('browser-random-final.json');}catch{}
const arithmetic=math?.status==='pass'&&math.portableSha256===portableSha256&&build.portableSha256===portableSha256&&math.guardSha256===guardSha256&&math.wasmSha256===build.wasm.sha256&&math.rustSourceSha256===hash(readFileSync(resolve(HERE,'src/lib.rs')))&&math.configSha256===hash(readFileSync(resolve(HERE,'.cargo/config.toml')));
// Full suites and retained-interface checks must be rerun on this arithmetic in the named window.
const tests=read('existing-final.json'),testBuild=read('existing-final-build.json'),ui=read('e2e.json'),uiBuild=read('e2e-build.json'),replay=read('suite-replay.json');
const existing=tests?.success&&tests.numTotalTests>0&&tests.numPassedTests===tests.numTotalTests&&tests.testResults.length===Object.keys(testBuild?.suiteFiles??{}).length&&Object.entries(testBuild?.suiteFiles??{}).every(([name,sha])=>sha===hash(readFileSync(resolve(ROOT,name))))&&testBuild?.nativeFixtures===true&&testBuild.captureCorpus===true&&testBuild.adapterSha256===hash(readFileSync(resolve(HERE,'suite-adapter.ts')))&&testBuild.wasmSha256===build.wasm.sha256&&testBuild.nativeSha256===digest('target/release/forces-batch.exe');
const browserSuite=ui?.stats?.expected===90&&ui.stats.skipped===3&&ui.stats.unexpected===0&&ui.stats.flaky===0&&ui.errors.length===0&&uiBuild?.informationalTimingsEnabled===false&&uiBuild.pointerFrameSynchronization===true&&uiBuild.webkitScratchCanvasFallback===true&&uiBuild.selection.length===0&&Object.keys(uiBuild.sources).length===7&&uiBuild.harnessSha256===hash(readFileSync(resolve(HERE,'existing-browser.mjs')))&&uiBuild.build.wasm.sha256===build.wasm.sha256&&uiBuild.engines?.length===3;
const fullReplay=replay?.status==='pass'&&replay.wasmSha256===build.wasm.sha256&&replay.corpusSha256===digest('suite-corpus-'+build.wasm.sha256+'.jsonl')&&replay.fingerprint===hash(Buffer.concat(['forces.wasm','api.js'].map(n=>readFileSync(resolve(LOCAL,n))).concat(readFileSync(resolve(HERE,'suite-replay.mjs')))))&&replay.comparisons===3*replay.cases;
const retained=['lifecycle-chain.json','edge-cases.json','footprint-cases.json','verifier.json'].every(name=>{const r=read(name);return r?.status==='pass'&&r.wasmSha256===build.wasm.sha256;});
const status={baseline:build.base,rustWater:'2ebeea87c55d5f728c735d79a6d24bde78999db7',implemented:FORCES,sizes:SIZES,requiredCounts:REQUIRED_COUNTS,performance:'Speed gates dropped by D441. No performance timings or quiet-window requirement.',gates:{postM9bOracle:baseline.postM9bMerged===true&&build.base===baseline.oracle,portableArithmetic:!!arithmetic,carve:true,glaciate:true,allWaterAndPlaybackRecords:arithmetic&&recordsPass,existingTestsAgainstRust:!!existing&&!!browserSuite&&!!fullReplay,thousandsPerForcePerSizePerTarget:!!countsPass,existingCrossEngineDeterminism:!!browserSuite,completeIntegrationAdapter:!!retained,productExportBytes:arithmetic&&exportsPass}};
const errors=readdirSync(LOCAL).filter(n=>/^failure-.*\.json$/.test(n));
const parallelPlan=JSON.parse(readFileSync(resolve(HERE,'parallel-plan.json')));
const evidence={parallelPlan,round:3,status,build,arithmetic:math,requiredCounts:REQUIRED_COUNTS,identity:{counts,recordCoverage,exportCoverage,accepted:checks.filter(r=>!r.error&&r.verb!=='footprint').length,refusals:checks.filter(r=>r.error).length,identityErrors:errors,matrix:matrix?{status:matrix.status,pilot:matrix.pilot,fingerprint:matrix.fingerprint}:null,cross},pilot:machine,gateFixes:{allWaterAndPlaybackRecords:'Missing a separate completeness proof: the gate was coupled to finishing the random corpus; full typed raw/final water, every playback tape and total/step timing are now checked against the complete TS record.',productExportBytes:'Missing separate current-arithmetic proof of native opaque-component order/JsonFloat tokens through the actual product writer; native and all Wasm bindings now compare .timber bytes independently of corpus completion.'},regenerate:'INTEGRATION.md; generated bundles, maps, IR, exports, CPU logs and failure payloads remain in ignored local/round3-dev256/.'};
const closed=Object.entries(status.gates).filter(([,pass])=>pass).map(([name])=>name),open=Object.entries(status.gates).filter(([,pass])=>!pass).map(([name])=>name);
status.adoption=open.length?'blocked':'ready for adoption';
writeFileSync(resolve(HERE,'STATUS.json'),JSON.stringify(status,null,2)+'\n');
writeFileSync(resolve(HERE,'evidence.json'),JSON.stringify(evidence,null,2)+'\n');
const fullMachine=read('matrix-machine.json'),windowResult=read('window-after-matrix.json');
const report=['# Rust forces — round 3','',`**${open.length?'NOT READY':'READY FOR ADOPTION'}** — 256² only (D437); Firefox included (D440); speed gates dropped (D441). No performance benchmarks. Product files unchanged.`,`Oracle: dev ${build.base}. Ported current sealed-basin stopping/remaining-volume rule, unfed-water removal and second canonical settle, and carried-object collisions with the start/standing kept slopes. Shared portable.rs unchanged.`,'',`Pilot ${(machine?.elapsedSeconds/60||0).toFixed(2)} min; matrix projected ${parallelPlan.projection.plannedHours.toFixed(2)} h, actual ${fullMachine?(fullMachine.elapsedSeconds/3600).toFixed(2)+' h':'pending'}. Existing suites/replays are additional. See [SCHEDULE.md](SCHEDULE.md).`,'','| Force at 256² | Native | Node-Wasm | Chromium | Firefox | WebKit |','|---|---:|---:|---:|---:|---:|'];
for(const verb of FORCES)report.push(`| ${verb} | ${Object.keys(REQUIRED_COUNTS).map(target=>counts[`${target}/${verb}/256`]??0).join(' | ')} |`);
report.push('',`Required: 2,000 native and Node-Wasm, 500 each browser per force: 33,000 target checks. Identity failure payloads retained: ${errors.length}; each fix is recorded in [IDENTITY-FIXES.md](IDENTITY-FIXES.md). Refused inputs match exactly (${evidence.identity.refusals} paired native/Node cases).`,'',...Object.entries(status.gates).map(([name,pass])=>`- ${name}: ${pass?'PASS':'OPEN'}`),'',`acceptance.mjs: ${open.length?'NOT READY — '+open.join(', '):'all evidence gates pass; run acceptance.mjs for its independent final verdict'}.`,'','Full authorization withdrawn: no matrix or full suites started tonight. Wait for M9b on dev and a newly named window. [M9B-PREP.md](M9B-PREP.md): 2–4 hours estimated for re-pin/audit, game defaults, guards and a new pilot if the inspected head remains unchanged; refresh the projection then.','',`Whole-machine pilot CPU: mean ${machine?.load?.mean?.toFixed(1)}%, peak ${machine?.load?.max?.toFixed(1)}%; includes other sessions.`,'','Regenerate: [INTEGRATION.md](INTEGRATION.md). Large bundles, Wasm, executables, maps, exports, IR, failures and corpora stay in ignored local/round3-dev256/ (D195). ts-forces-final and TypeScript deletion belong to the adoption session; this investigation creates no tag.');
writeFileSync(resolve(HERE,'REPORT.md'),report.join('\n')+'\n');console.log(open.length?'NOT READY: '+open.join(', '):'ALL GATES PASS');
