// Only pinned, complete evidence can turn the adoption gate green.
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {HERE,LOCAL,arg,hash} from './common.mjs';
const read=name=>existsSync(resolve(LOCAL,name))?JSON.parse(readFileSync(resolve(LOCAL,name))):null;
const digest=name=>existsSync(resolve(LOCAL,name))?hash(readFileSync(resolve(LOCAL,name))):null;
const checksName=arg('checks','checks-random-final.json'),crossName=arg('cross','cross-engine.json'),testsName=arg('tests','existing-final.json');
const build=read('build.json'),checks=read(checksName),cross=read(crossName),matrix=read('identity-matrix.json'),tests=read(testsName),testBuild=read(testsName.replace('.json','-build.json')),browserTests=read('e2e.json'),browserBuild=read('e2e-build.json'),math=read('ir.json'),lifecycle=read('lifecycle-chain.json'),edge=read('edge-cases.json'),footprints=read('footprint-cases.json'),pilot=read('checks-codec-final.json');
const nativeSha256=digest('target/release/forces-batch.exe'),wasmSha256=build.wasm.sha256;
const nativeFingerprint=hash(Buffer.concat(['forces.wasm','api.cjs','target/release/forces-batch.exe'].map(n=>readFileSync(resolve(LOCAL,n)))));
const matrixFingerprint=hash(Buffer.concat(['forces.wasm','api.cjs','api.js','worker.js','target/release/forces-batch.exe'].map(n=>readFileSync(resolve(LOCAL,n)))));
const counts={},accepted={},ids=new Map();
for(const r of checks??[]){const key=r.verb+'/'+r.size;if(!ids.has(key))ids.set(key,new Set());ids.get(key).add(r.k);counts[key]=(counts[key]??0)+1;accepted[key]=(accepted[key]??0)+Number(!r.error);}
const allRandom=['craterize','erupt','quake','carve','glaciate'].every(v=>[128,256,512].every(n=>{const set=ids.get(v+'/'+n);return set?.size>=2000&&Array.from({length:2000},(_,k)=>k).every(k=>set.has(k));}));
const randomPinned=allRandom&&matrix?.fingerprint===matrixFingerprint&&checks.every(r=>r.fingerprint===nativeFingerprint)&&cross?.status==='pass'&&cross.checksSha256===digest(checksName)&&cross.wasmSha256===wasmSha256&&cross.comparisons===3*checks.length&&cross.engines.length===3;
const exportPass=randomPinned&&checks.every(r=>r.error||r.exportSha256)&&cross.exportCases===checks.filter(r=>!r.error).length;
const currentSuite=!!tests?.success&&tests.numTotalTests>=186&&tests.numPassedTests===tests.numTotalTests&&tests.testResults.length===27&&testBuild?.nativeFixtures===true&&testBuild.wasmSha256===wasmSha256&&testBuild.nativeSha256===nativeSha256&&testBuild.adapterSha256===hash(readFileSync(resolve(HERE,'suite-adapter.ts')));
function attachments(suites){let total=0;for(const s of suites??[]){for(const spec of s.specs??[])for(const test of spec.tests??[])for(const result of test.results??[])for(const a of result.attachments??[])if(a.name==='rust-comparisons'&&a.body)total+=JSON.parse(Buffer.from(a.body,'base64').toString()).reduce((sum,n)=>sum+n,0);total+=attachments(s.suites);}return total;}
const browserComparisons=attachments(browserTests?.suites),replay=read('suite-replay.json');
const replayPass=replay?.status==='pass'&&replay.wasmSha256===wasmSha256&&replay.corpusSha256===digest('suite-corpus-'+wasmSha256+'.jsonl')&&replay.comparisons===3*replay.cases&&testBuild?.captureCorpus===true&&currentSuite;
const fullBrowser=browserTests?.stats?.unexpected===0&&browserTests.stats.flaky===0&&browserTests.stats.skipped===0&&browserTests.errors.length===0&&browserBuild?.informationalTimingsEnabled===true&&browserBuild?.engines?.length===3&&browserBuild.selection.length===0&&Object.keys(browserBuild.sources).length===7&&browserBuild.build.wasm.sha256===wasmSha256&&browserBuild.harnessSha256===hash(readFileSync(resolve(HERE,'existing-browser.mjs')))&&browserComparisons>0;
const measurements=JSON.parse(readFileSync(resolve(HERE,'measurement-evidence.json'))),timingPinned=measurements.build.wasm.sha256===wasmSha256&&measurements.build.inputs['src/lib.rs']===build.inputs['src/lib.rs'];
const timingPass=timingPinned&&measurements.firstThree.pass&&measurements.allForces.pass&&measurements.rows.length===144&&measurements.rows.every(r=>r.pass);
const retained=lifecycle?.status==='pass'&&lifecycle.wasmSha256===wasmSha256&&edge?.status==='pass'&&edge.wasmSha256===wasmSha256&&footprints?.status==='pass'&&footprints.wasmSha256===wasmSha256&&footprints.rows.length===36;
const status={baseline:build.base,rustWater:'2ebeea87c55d5f728c735d79a6d24bde78999db7',implemented:['footprint','craterize','erupt','quake','carve','glaciate'],gates:{portableArithmetic:math?.status==='pass'&&math.rustSourceSha256===build.inputs['src/lib.rs']&&math.configSha256===build.inputs['.cargo/config.toml']&&build.wasm.imports?.length===0,carve:true,glaciate:true,allWaterAndPlaybackRecords:!!randomPinned,existingTestsAgainstRust:!!currentSuite&&!!fullBrowser&&!!replayPass,thousandsPerForcePerSizePerTarget:!!randomPinned,existingCrossEngineDeterminism:!!fullBrowser,performanceAcceptance:!!timingPass,completeIntegrationAdapter:!!retained,productExportBytes:!!exportPass&&!!currentSuite&&!!fullBrowser}};
const remaining=Object.entries(status.gates).filter(([,pass])=>!pass).map(([name])=>name);
const evidence={status:remaining.length?'incomplete-do-not-adopt':'all-gates-passed',baseline:build.base,rustWater:status.rustWater,build,nativeSha256,mathGuard:math,identity:{counts,accepted,refusals:(checks?.length??0)-Object.values(accepted).reduce((a,b)=>a+b,0),randomPinned,randomFile:{name:checksName,sha256:digest(checksName)},matrix:{name:'identity-matrix.json',sha256:digest('identity-matrix.json'),fingerprint:matrix?.fingerprint},pilot:{cases:pilot?.length??0,sha256:digest('checks-codec-final.json')},crossEngine:cross,lifecycle,edge,footprints,scope:'Exact IEEE fixture bytes: raw/final land, water, ordered objects, geometry, literal changes, all playback tapes and timings. Every accepted random gesture also compares actual .timber writer bytes with fixed fixture metadata, no thumbnail and zero soil. Existing contracts/browser suites cover editor, project, worker and finalizer exports.'},existingTests:tests?{name:testsName,sha256:digest(testsName),build:testBuild,files:tests.testResults.length,total:tests.numTotalTests,passed:tests.numPassedTests,failed:tests.numFailedTests,success:tests.success,currentSuite}:null,suiteReplay:replay?{sha256:digest('suite-replay.json'),status:replay.status,wasmSha256:replay.wasmSha256,corpusSha256:replay.corpusSha256,cases:replay.cases,comparisons:replay.comparisons,counts:replay.counts,replayPass}:null,existingBrowser:browserTests?{sha256:digest('e2e.json'),build:browserBuild,stats:browserTests.stats,rustComparisons:browserComparisons,fullBrowser}:null,measurements:{file:'measurement-evidence.json',sha256:hash(readFileSync(resolve(HERE,'measurement-evidence.json'))),firstThree:measurements.firstThree,allForces:measurements.allForces,timingPinned},remaining};
writeFileSync(resolve(HERE,'STATUS.json'),JSON.stringify(status,null,2)+'\n');writeFileSync(resolve(HERE,'evidence.json'),JSON.stringify(evidence,null,2)+'\n');
const r=measurements.rows.find(r=>r.target==='native'&&r.verb==='erupt'&&r.size===512&&r.k===1),pair=s=>s.median.toFixed(2)+' / '+s.worst.toFixed(2),load=measurements.rows.map(r=>r.load.mean).filter(n=>n!=null);
const report=['# Rust forces — round 2','',`**${remaining.length?'Not adoptable yet':'All gates passed'}.** ${remaining.length?remaining.join(', ')+'.':'Ready for the separate adoption session.'}`,'',`All five forces and footprints use typed Rust structs/flat arrays, numeric object slots and stable shared Wasm map buffers. One operation call; serde_json is cold fixture/debug only. TypeScript keeps presentation. AGPL-3.0-or-later. Dev \`4aab909e\`; rust-water \`2ebeea87\`, including its isolated Firefox debugger fix. Product files unchanged.`,'',`**Speed:** first-three ${timingPass?'PASS':'not pinned/passed'} (${measurements.firstThree.cells}/72 cells); all-five ${timingPass?'PASS':'not pinned/passed'} (${measurements.allForces.cells}/120), plus 24 footprint cells. Five repeats, median / worst. Full-Power Erupt Fissure 512² native: TypeScript ${pair(r.ts)} ms; Rust compute ${pair(r.compute)}; Rust + boundary ${pair(r.boundary)}. Shared-PC CPU mean range ${Math.min(...load).toFixed(1)}–${Math.max(...load).toFixed(1)}%. [All columns, modes, engines and loads](MEASUREMENTS.md). Earlier nested diagnostic reconstruction failures remain in \`diagnostic-measurement-evidence.json\`.`,'',`**Identity:** ${checks?.length??0} sealed random native/Node-Wasm cases; ${cross?.comparisons??0} browser comparisons; required: 2,000 per force/size/target. Accepted gestures include .timber byte checks. Existing native/Wasm contracts ${tests?.numPassedTests??0}/${tests?.numTotalTests??186}; full three-engine browser suites ${fullBrowser?'PASS':'unfinished'}, including existing determinism. Retained-map/edge gate ${retained?'PASS':'unfinished'}. Counts, refusal counts, hashes and exact scope: [evidence.json](evidence.json).`,'',`**Download:** ${build.wasm.bytes} B raw / ${build.wasm.gzip} B gzip / ${build.wasm.brotli} B Brotli; no production Wasm imports. Strict native/Wasm arithmetic guard ${math?.status??'unrun'}. [Regeneration and adoption](INTEGRATION.md). Large generated outputs stay ignored. The adoption session tags \`ts-forces-final\` and deletes adopted TypeScript in the Rust order; this investigation performs neither. \`node acceptance.mjs\` remains red while a required gate is open.`];
writeFileSync(resolve(HERE,'REPORT.md'),report.join('\n')+'\n');console.log(evidence.status,remaining);
