// Round 3: separate adapter completeness from the full statistical corpus.
import {readFileSync,writeFileSync,existsSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {HERE,LOCAL,hash} from './common.mjs';
import {portableSha256,guardSha256} from './shared-math.mjs';
import {FORCES,SIZES,REQUIRED_COUNTS,validateCounts} from './acceptance.mjs';
const read=name=>existsSync(resolve(LOCAL,name))?JSON.parse(readFileSync(resolve(LOCAL,name))):null;
const digest=name=>existsSync(resolve(LOCAL,name))?hash(readFileSync(resolve(LOCAL,name))):null;
const build=read('build.json'),math=read('ir.json'),matrix=read('identity-matrix.json'),cross=read('cross-engine.json'),machine=read('pilot-machine.json');
const nativeFingerprint=hash(Buffer.concat(['forces.wasm','api.cjs','target/release/forces-batch.exe'].map(n=>readFileSync(resolve(LOCAL,n))))),browserFingerprint=hash(Buffer.concat(['forces.wasm','worker.js'].map(n=>readFileSync(resolve(LOCAL,n)))));
const current=new Map();
for(const name of readdirSync(LOCAL).filter(n=>/^(checks|browser)-matrix-.*\.jsonl$/.test(n)))for(const line of readFileSync(resolve(LOCAL,name),'utf8').split(/\r?\n/)){
 if(!line)continue;let r;try{r=JSON.parse(line);}catch{continue;}
 const native=name.startsWith('checks-');if(r.fingerprint!==(native?nativeFingerprint:browserFingerprint)||!native&&r.ok!==true)continue;
 const id=native?`${r.verb}/${r.size}/${r.k}/random`:r.id,key=(native?'native':r.engine)+'/'+id;
 if(current.has(key)&&current.get(key).sha256!==r.sha256)throw Error('Conflicting checkpoint '+key);current.set(key,r);
}
const checks=[...current].filter(([k])=>k.startsWith('native/')).map(([,r])=>r),browsers=[...current].filter(([k])=>!k.startsWith('native/')).map(([,r])=>r),counts={};
for(const r of checks)for(const target of ['native','node-wasm'])counts[`${target}/${r.verb}/${r.size}`]=(counts[`${target}/${r.verb}/${r.size}`]??0)+1;
for(const r of browsers){const [verb,size]=r.id.split('/');counts[`${r.engine}/${verb}/${size}`]=(counts[`${r.engine}/${verb}/${size}`]??0)+1;}
const requiredFields={craterize:['raw','map','literal','arrival','total'],erupt:['raw','map','literal','heat','flows','total'],quake:['raw','map','literal','arrival','source','dx','dy','extras','finalWater','total'],carve:['raw','map','literal','changes','heads','lengths','rawChanges','stepMetrics','stepObjectChanges','initialEntities','oxbows','edgeLeaks','oxbowBasin','closure','retained','unleashedId','badwater','total'],glaciate:['raw','map','literal','arrival','mask','floor','nearest','stream','fan','retained','basins','hanging','joins','finished','total']};
const recordCoverage={},exportCoverage={};
for(const target of Object.keys(REQUIRED_COUNTS))for(const verb of FORCES.filter(v=>v!=='footprint'))for(const size of SIZES){
 const rows=target==='native'||target==='node-wasm'?checks.filter(r=>r.verb===verb&&r.size===size):browsers.filter(r=>r.engine===target&&r.id.startsWith(`${verb}/${size}/`));
 const accepted=rows.filter(r=>!r.error),key=`${target}/${verb}/${size}`;
 recordCoverage[key]=accepted.filter(r=>r.typedRecordsChecked===true&&requiredFields[verb].every(k=>r.recordFields?.includes(k))).length;
 exportCoverage[key]=accepted.filter(r=>r.productWriterChecked===true&&/^[a-f0-9]{64}$/.test(r.exportSha256??'')).length;
}
const recordsPass=Object.values(recordCoverage).every(n=>n>0),exportsPass=Object.values(exportCoverage).every(n=>n>0);
let countsPass=false;try{validateCounts(checks,browsers);countsPass=matrix?.pilot===false&&matrix.status==='pass'&&cross?.status==='pass'&&cross.checksSha256===digest('checks-random-final.json')&&cross.browserSha256===digest('browser-random-final.json');}catch{}
const arithmetic=math?.status==='pass'&&math.portableSha256===portableSha256&&build.portableSha256===portableSha256&&math.guardSha256===guardSha256&&math.wasmSha256===build.wasm.sha256&&math.rustSourceSha256===hash(readFileSync(resolve(HERE,'src/lib.rs')))&&math.configSha256===hash(readFileSync(resolve(HERE,'.cargo/config.toml')));
// Full suites and retained-interface checks must be rerun on this arithmetic in the named window.
const tests=read('existing-final.json'),testBuild=read('existing-final-build.json'),ui=read('e2e.json'),uiBuild=read('e2e-build.json'),replay=read('suite-replay.json');
const existing=tests?.success&&tests.numTotalTests>=186&&tests.numPassedTests===tests.numTotalTests&&tests.testResults.length===27&&testBuild?.nativeFixtures===true&&testBuild.captureCorpus===true&&testBuild.adapterSha256===hash(readFileSync(resolve(HERE,'suite-adapter.ts')))&&testBuild.wasmSha256===build.wasm.sha256&&testBuild.nativeSha256===digest('target/release/forces-batch.exe');
const browserSuite=ui?.stats?.expected===90&&ui.stats.skipped===3&&ui.stats.unexpected===0&&ui.stats.flaky===0&&ui.errors.length===0&&uiBuild?.informationalTimingsEnabled===false&&uiBuild.pointerFrameSynchronization===true&&uiBuild.webkitScratchCanvasFallback===true&&uiBuild.selection.length===0&&Object.keys(uiBuild.sources).length===7&&uiBuild.harnessSha256===hash(readFileSync(resolve(HERE,'existing-browser.mjs')))&&uiBuild.build.wasm.sha256===build.wasm.sha256&&uiBuild.engines?.length===3;
const fullReplay=replay?.status==='pass'&&replay.wasmSha256===build.wasm.sha256&&replay.corpusSha256===digest('suite-corpus-'+build.wasm.sha256+'.jsonl')&&replay.fingerprint===hash(Buffer.concat(['forces.wasm','api.js'].map(n=>readFileSync(resolve(LOCAL,n))).concat(readFileSync(resolve(HERE,'suite-replay.mjs')))))&&replay.comparisons===3*replay.cases;
const retained=['lifecycle-chain.json','edge-cases.json','footprint-cases.json','verifier.json'].every(name=>{const r=read(name);return r?.status==='pass'&&r.wasmSha256===build.wasm.sha256;});
const status={baseline:build.base,rustWater:'2ebeea87c55d5f728c735d79a6d24bde78999db7',implemented:FORCES,requiredCounts:REQUIRED_COUNTS,performance:'Round 2 accepted by user; provisional until a quiet window. No round-3 timings.',gates:{portableArithmetic:!!arithmetic,carve:true,glaciate:true,allWaterAndPlaybackRecords:arithmetic&&recordsPass,existingTestsAgainstRust:!!existing&&!!browserSuite&&!!fullReplay,thousandsPerForcePerSizePerTarget:!!countsPass,existingCrossEngineDeterminism:!!browserSuite,performanceAcceptance:true,completeIntegrationAdapter:!!retained,productExportBytes:arithmetic&&exportsPass}};
const errors=readdirSync(LOCAL).filter(n=>/^failure-.*\.json$/.test(n));
const parallelPlan=JSON.parse(readFileSync(resolve(HERE,'parallel-plan.json')));
const evidence={parallelPlan,round:3,status,build,arithmetic:math,requiredCounts:REQUIRED_COUNTS,identity:{counts,recordCoverage,exportCoverage,accepted:checks.filter(r=>!r.error&&r.verb!=='footprint').length,refusals:checks.filter(r=>r.error).length,identityErrors:errors,matrix:matrix?{status:matrix.status,pilot:matrix.pilot,fingerprint:matrix.fingerprint}:null,cross},pilot:machine,gateFixes:{allWaterAndPlaybackRecords:'Missing a separate completeness proof: the gate was coupled to finishing the random corpus; full typed raw/final water, every playback tape and total/step timing are now checked against the complete TS record.',productExportBytes:'Missing separate current-arithmetic proof of native opaque-component order/JsonFloat tokens through the actual product writer; native and all Wasm bindings now compare .timber bytes independently of corpus completion.'},regenerate:'INTEGRATION.md; generated bundles, maps, IR, exports, CPU logs and failure payloads remain in ignored local/round3/.'};
for(const [name,value]of [['STATUS.json',status],['evidence.json',evidence]])writeFileSync(resolve(HERE,name),JSON.stringify(value,null,2)+'\n');
const closed=Object.entries(status.gates).filter(([,pass])=>pass).map(([name])=>name),open=Object.entries(status.gates).filter(([,pass])=>!pass).map(([name])=>name);
const report=['# Rust forces — round 3','',`**Identity only; ${open.length?'not adoptable':'all gates pass'}.** Round-2 speed is accepted provisionally; no timing work this round. Product files unchanged.`, '',`Overnight plan: 8 independent workers, 25 cases/shard, 2,520 shards; estimated ${parallelPlan.projection.plannedHours.toFixed(1)} hours (${parallelPlan.projection.rangeHours.map(n=>n.toFixed(1)).join('–')}); projected peak CPU budget 100%, unmeasured. Longest remaining shards first; at most 6 simultaneous 512² shards, 2 browsers/engine; stop admission below 10 GiB free RAM. Uses the existing pilot only, with 20% contention allowance. Full counts unchanged.`, '', 'Scheduling handoff: [SCHEDULE.md](SCHEDULE.md) gives the full share of the one assigned machine and observed pilot duration per target/size. All round 3 workloads remain stopped until Kyler explicitly authorizes a window; the other measurement job has priority.', '', `Shared portable.rs applied; strict native/Wasm source, IR, assembly and unstripped Wasm guard ${arithmetic?'PASS':'pending'}.`, '',`allWaterAndPlaybackRecords ${status.gates.allWaterAndPlaybackRecords?'closed':'pending'}: ${evidence.gateFixes.allWaterAndPlaybackRecords}`,`productExportBytes ${status.gates.productExportBytes?'closed':'pending'}: ${evidence.gateFixes.productExportBytes}`, '',`Pilot: ${machine?`${(machine.elapsedSeconds/60).toFixed(1)} minutes; projected sequential full matrix ${(machine.projectedFullSeconds/3600).toFixed(1)} hours; mean / peak total CPU ${machine.load.mean?.toFixed(1)}% / ${machine.load.max?.toFixed(1)}% (shared PC, including other sessions).`:'running/not sealed; projection and peak CPU pending.'} Projection includes cold verification and browser startup, not force planning timings.`, '', 'Counts are Native / Node-Wasm / Chromium / Firefox / WebKit for each cell.','', '| Force | 128² | 256² | 512² |','|---|---|---|---|'];
for(const verb of FORCES)report.push(`| ${verb} | ${SIZES.map(size=>Object.keys(REQUIRED_COUNTS).map(target=>counts[`${target}/${verb}/${size}`]??0).join('/')).join(' | ')} |`);
report.push('',`Required per cell: native/Node-Wasm 2,000; browsers 500. Identity errors: ${errors.length}; refused gestures are compared exactly and reported separately (${evidence.identity.refusals} paired native/Node cases).`, '',`acceptance.mjs verdict: ${open.length?'NOT READY — '+open.join(', '):'PASS'}. Full matrix awaits a user-named window. Final-arithmetic suites/retained checks also wait for that window; their time is excluded from the projection.`, '', 'Regenerate: [INTEGRATION.md](INTEGRATION.md). Large generated outputs and exact failure payloads stay in ignored local/round3/. Adoption tags ts-forces-final and deletes TypeScript in the separate milestone session; this investigation creates no tag.');
writeFileSync(resolve(HERE,'REPORT.md'),report.join('\n')+'\n');console.log(open.length?'NOT READY: '+open.join(', '):'ALL GATES PASS');
