import {resolve,dirname} from 'node:path';
import {readFileSync,writeFileSync,globSync} from 'node:fs';
import {spawn} from 'node:child_process';
import {HERE,ROOT,LOCAL,deps,json,hash} from './common.mjs';
import {testPath,code as upstreamTest,provenance} from './upstream-tests.mjs';
const aliases=Object.fromEntries(['vitest','fflate','preact','preact/hooks','preact/jsx-runtime','preact/jsx-dev-runtime','preact/compat','@preact/signals','comlink','three'].map(name=>[name,deps.resolve(name)]));
aliases['ajv/dist/2020']=deps.resolve('ajv/dist/2020');
aliases.vitest=resolve(dirname(deps.resolve('vitest/package.json')),'dist/index.js');
const report=process.env.DGM_TEST_REPORT??'existing-tests.json';if(!/^[a-z0-9-]+\.json$/.test(report))throw Error('Invalid test report name');
const config={root:ROOT,cacheDir:resolve(LOCAL,'vite-cache'),resolve:{alias:Object.entries(aliases).sort(([a],[b])=>b.length-a.length).map(([find,replacement])=>({find,replacement}))},test:{setupFiles:[resolve(HERE,'suite-adapter.ts')],include:['tests/unit/*force*.test.ts','tests/contract/*force*.test.ts','tests/contract/carve*.test.ts','tests/contract/curvedFault.test.ts','tests/contract/glaciate*.test.ts','tests/contract/erupt*.test.ts','tests/contract/unleash.test.ts'],maxWorkers:4,bail:1,testTimeout:1200000,hookTimeout:1200000,reporters:['default','json'],outputFile:resolve(LOCAL,report)}};
const suiteFiles=Object.fromEntries([...new Set(globSync(config.test.include,{cwd:ROOT}))].sort().map(name=>[name.replaceAll('\\','/'),hash(readFileSync(resolve(ROOT,name)))]));
const plugin=`{name:'rust-forces-suite',enforce:'pre',transform(code,id){if(id.endsWith('/'+${JSON.stringify(testPath)}))return ${JSON.stringify(upstreamTest)};if(id.endsWith('/investigation/rust-forces/suite-adapter.ts'))return code.replaceAll('./local/checkout/',${JSON.stringify(ROOT.replaceAll("\\","/")+"/")});if(id.endsWith('/src/core/forces/carve/run.ts'))return code.replace('    const N = input.W * input.H;','    (this as any).__rustBefore = input; (this as any).__rustOptions = options;\\n    const N = input.W * input.H;');if(id.endsWith('/src/core/forces/glaciate/plan.ts'))return code.replace('  return best!;','  return (globalThis as any).__rustGlaciate(best!, input, settings, intent);');}}`;
writeFileSync(resolve(LOCAL,'vitest.config.mjs'),'export default {...'+JSON.stringify(config)+',plugins:['+plugin+']};\n');
const cli=resolve(dirname(deps.resolve('vitest/package.json')),'vitest.mjs');
json(report.replace('.json','-build.json'),{upstreamTest:provenance,nativeFixtures:process.env.DGM_SUITE_NATIVE==='1',captureCorpus:process.env.DGM_SUITE_CAPTURE==='1',include:config.test.include,suiteFiles,wasmSha256:hash(readFileSync(resolve(LOCAL,'forces.wasm'))),nativeSha256:hash(readFileSync(resolve(LOCAL,'target/release/forces-batch.exe'))),adapterSha256:hash(readFileSync(resolve(HERE,'suite-adapter.ts'))),build:JSON.parse(readFileSync(resolve(LOCAL,'build.json')))});
const child=spawn(process.execPath,[cli,'run','--config',resolve(LOCAL,'vitest.config.mjs'),...process.argv.slice(2)],{cwd:ROOT,windowsHide:true,stdio:'inherit'});child.on('exit',code=>{process.exitCode=code??1;});
