// Run unchanged existing browser suites against an investigation-only Rust adapter.
// Product source is read only. Generated builds, rewritten import paths and results
// stay in local/. The adapter is diagnostic: it computes an independent TS oracle.
import {readFileSync,writeFileSync,mkdirSync,copyFileSync} from 'node:fs';
import {resolve,dirname,sep} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import {createServer} from 'node:http';
import {spawn} from 'node:child_process';
import {HERE,ROOT,LOCAL,deps,hash,json,arg} from './common.mjs';
const slash=s=>s.replaceAll('\\','/'),url=p=>pathToFileURL(p).href;
const adapter=readFileSync(resolve(HERE,'suite-adapter.ts'),'utf8').replace(/^import .*from 'node:.*';\r?\n/gm,'').replace(/^import \{afterAll\} from 'vitest';\r?\n/m,'').replaceAll('./local/checkout/',slash(ROOT)+'/');
const start=adapter.indexOf('const runDir='),end=adapter.indexOf('let comparisons=');
let browserAdapter=adapter.slice(0,start)+`import * as api from ${JSON.stringify(slash(resolve(LOCAL,'api.js')))};\nconst bridge=await api.bridge(await(await fetch(new URL('./forces.wasm',import.meta.url))).arrayBuffer());\n`+adapter.slice(end);
browserAdapter=browserAdapter.replace('const x=Buffer.from(api.encode(a)),y=Buffer.from(api.encode(b));if(!x.equals(y))','const x=api.encode(a),y=api.encode(b);if(x.length!==y.length||!x.every((v:any,i:number)=>v===y[i]))');
const nativeStart=browserAdapter.indexOf("  if(process.env.DGM_SUITE_NATIVE==='1')"),nativeEnd=browserAdapter.indexOf('  return cloneFixture(r);',nativeStart);
browserAdapter=browserAdapter.slice(0,nativeStart)+browserAdapter.slice(nativeEnd);
browserAdapter=browserAdapter.replace(/afterAll\(\(\)=>appendFileSync[^\n]+/,'(globalThis as any).__rustSuiteComparisons=()=>comparisons;');
writeFileSync(resolve(LOCAL,'browser-suite.ts'),browserAdapter);
const browserDeps=createRequire(resolve(process.env.DGM_BROWSER_DEPS??resolve(HERE,'local/browser-deps'),'package.json'));
const playwrightEntry=resolve(dirname(browserDeps.resolve('@playwright/test/package.json')),'index.mjs');
// Playwright's Node oracle imports the read-only product tree; supply its dependencies here.
const nodeAliases=Object.fromEntries(['fflate','preact','preact/hooks','preact/jsx-runtime','preact/jsx-dev-runtime','preact/compat','@preact/signals','comlink','three','ajv/dist/2020'].map(name=>[name,[slash(deps.resolve(name))]]));
const testTsconfig=resolve(LOCAL,'e2e-tsconfig.json');
writeFileSync(testTsconfig,JSON.stringify({compilerOptions:{baseUrl:slash(ROOT),paths:nodeAliases}}));
const aliases=Object.fromEntries(['fflate','preact','preact/hooks','preact/jsx-runtime','preact/jsx-dev-runtime','preact/compat','@preact/signals','comlink','three'].map(name=>[name,deps.resolve(name)]));
aliases.fflate=resolve(dirname(deps.resolve('fflate')),'../esm/browser.js');
aliases.three=resolve(dirname(deps.resolve('three')),'three.module.js');
aliases['ajv/dist/2020']=deps.resolve('ajv/dist/2020');
const bootstrap=resolve(LOCAL,'worker-bootstrap.js');
writeFileSync(bootstrap,`// Buffer messages while the investigation-only Wasm adapter initializes.
const pending=[];let ready=false;const capture=e=>{if(!ready){pending.push(e);e.stopImmediatePropagation();}};self.addEventListener('message',capture,true);self.__rustReleaseStartup=()=>{ready=true;self.removeEventListener('message',capture,true);for(const e of pending)self.dispatchEvent(new MessageEvent('message',{data:e.data,ports:e.ports,origin:e.origin,lastEventId:e.lastEventId}));pending.length=0;};
`);
const transform=`function rust(){return {name:'rust-force-suite',enforce:'pre',transform(code,id){if(id.endsWith('/src/main.tsx'))return 'import '+${JSON.stringify(JSON.stringify(slash(resolve(LOCAL,'browser-suite.ts')))+';\n')}+code;if(id.endsWith('/src/worker/generator.worker.ts'))return ${JSON.stringify('import '+JSON.stringify(slash(bootstrap))+';\nimport '+JSON.stringify(slash(resolve(LOCAL,'browser-suite.ts')))+';\n')}+code+'\\n(globalThis).__rustReleaseStartup();';if(id.endsWith('/src/core/forces/carve/run.ts'))return code.replace('    const N = input.W * input.H;','    (this as any).__rustBefore=input;(this as any).__rustOptions=options;\\n    const N = input.W * input.H;');if(id.endsWith('/src/core/forces/glaciate/plan.ts'))return code.replace('  return best!;','  return (globalThis as any).__rustGlaciate(best!, input, settings, intent, finish);').replace('  if (!finish) return yield* planOnce(input, settings, intent, valley, null);','  if (!finish) { const p = yield* planOnce(input, settings, intent, valley, null); return (globalThis as any).__rustGlaciate(p, input, settings, intent, finish); }');}}}`;
const dist=resolve(LOCAL,'e2e-dist'),base='/dam-good-maps/';
if(!dist.startsWith(resolve(HERE,'local')+sep))throw Error('Build output escapes investigation local directory');
const viteConfig={root:ROOT,base,cacheDir:resolve(LOCAL,'e2e-vite-cache'),resolve:{alias:Object.entries(aliases).sort(([a],[b])=>b.length-a.length).map(([find,replacement])=>({find,replacement}))},build:{target:'es2022',outDir:dist,emptyOutDir:true,assetsInlineLimit:0,rollupOptions:{input:resolve(ROOT,'index.html')}},worker:{format:'es'}};
writeFileSync(resolve(LOCAL,'e2e-vite.config.mjs'),`import preset from ${JSON.stringify(url(deps.resolve('@preact/preset-vite')))};\nconst preact=preset.default??preset;\n${transform}\nexport default {...${JSON.stringify(viteConfig)},plugins:[preact(),rust()],worker:{format:'es',plugins:()=>[rust()]}};\n`);
const run=(command,args,options={})=>new Promise((done,reject)=>{const child=spawn(command,args,{windowsHide:true,stdio:'inherit',...options});child.on('error',reject);child.on('exit',code=>code===0?done():reject(Error(command+' exited '+code)));});
await run(process.execPath,[resolve(dirname(deps.resolve('vite/package.json')),'bin/vite.js'),'build','--mode','e2e','--configLoader','native','--config',resolve(LOCAL,'e2e-vite.config.mjs')],{cwd:ROOT});
const tests=['forces','carve','glaciate','unleash','forceKeys','forceSpeed','determinism'],testDir=resolve(LOCAL,'e2e-tests');mkdirSync(testDir,{recursive:true});const sources={};
for(const name of tests){const file=resolve(ROOT,'tests/e2e/'+name+'.spec.ts'),text=readFileSync(file,'utf8');sources[name]=hash(Buffer.from(text));writeFileSync(resolve(testDir,name+'.spec.ts'),text.replaceAll('"@playwright/test"',JSON.stringify(url(playwrightEntry))).replaceAll('../../src/',slash(ROOT)+'/src/')+`\ntest.beforeEach(async({page,browserName})=>{const move=page.mouse.move.bind(page.mouse);page.mouse.move=async(...args:any[])=>{await move(...args);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));};if(browserName==='webkit')await page.addInitScript(()=>{if(typeof(globalThis as any).OffscreenCanvas==='undefined')(globalThis as any).OffscreenCanvas=function(width:number,height:number){const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;return canvas;};});page.on('pageerror',error=>console.error('Browser exception:',error.stack));page.on('console',message=>{if(message.type()==='error')console.error('Browser error:',message.text());});});\ntest.afterEach(async({page},info)=>{const counts=[];for(const surface of [page,...page.workers()])try{counts.push(await surface.evaluate(()=>typeof(globalThis as any).__rustSuiteComparisons==='function'?(globalThis as any).__rustSuiteComparisons():0));}catch{counts.push(0);}await info.attach('rust-comparisons',{body:JSON.stringify(counts),contentType:'application/json'});});\n`);}
const server=createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(!pathname.startsWith(base)){res.writeHead(404).end();return;}const path=resolve(dist,pathname.slice(base.length)||'index.html');if(!path.startsWith(dist+sep)){res.writeHead(404).end();return;}try{const ext=path.split('.').at(-1),types={js:'text/javascript',css:'text/css',html:'text/html',wasm:'application/wasm',json:'application/json',svg:'image/svg+xml'};res.setHeader('Content-Type',types[ext]??'application/octet-stream');res.end(readFileSync(path));}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;
const pw=createRequire(resolve(process.env.DGM_BROWSER_DEPS??resolve(LOCAL,'browser-deps'),'package.json'))('playwright');
const config={testDir,tsconfig:testTsconfig,timeout:180000,workers:1,fullyParallel:false,outputDir:resolve(LOCAL,'e2e-results'),reporter:[['list'],['json',{outputFile:resolve(LOCAL,'e2e.json')}]],use:{baseURL:'http://127.0.0.1:'+port+base,storageState:{cookies:[],origins:[{origin:'http://127.0.0.1:'+port,localStorage:[{name:'dgm.look',value:'standard'}]}]}},projects:arg('engines','chromium,firefox,webkit').split(',').map(name=>({name,use:{browserName:name,launchOptions:{executablePath:(name==='chromium'?process.env.DGM_CHROMIUM:name==='firefox'?process.env.DGM_FIREFOX:process.env.DGM_WEBKIT)??pw[name].executablePath()}}}))};
writeFileSync(resolve(LOCAL,'e2e.config.mjs'),'export default '+JSON.stringify(config)+';\n');json('e2e-build.json',{build:JSON.parse(readFileSync(resolve(LOCAL,'build.json'))),suiteAdapterSha256:hash(Buffer.from(browserAdapter)),harnessSha256:hash(readFileSync(resolve(HERE,'existing-browser.mjs'))),engines:config.projects.map(p=>p.name),selection:process.argv.slice(2),sources,driver:browserDeps('@playwright/test/package.json').version,informationalTimingsEnabled:process.env.DGM_IDENTITY_ONLY!=='1',webkitScratchCanvasFallback:true,pointerFrameSynchronization:true});
try{await run(process.execPath,[resolve(dirname(browserDeps.resolve('@playwright/test/package.json')),'cli.js'),'test','--config',resolve(LOCAL,'e2e.config.mjs'),...process.argv.slice(2).filter((v,i,a)=>v!=='--engines'&&a[i-1]!=='--engines')],{cwd:ROOT,env:{...process.env,DGM_BENCH_FORCES:process.env.DGM_IDENTITY_ONLY==='1'?'':'1',NODE_PATH:resolve(dirname(deps.resolve('preact/package.json')),'..')}});}finally{server.close();}
